### ISSUE TITLE
[Bug]: 404 Not Found - Download demonstration data

### ISSUE THREAD

**Issue by felixm3** [epi2me-labs/wf-human-variation#1]
### What happened?

Trying to run your demo workflow here: https://github.com/epi2me-labs/wf-human-variation#quickstart

When I run this to download the demo data:

```
wget -O demo_data.tar.gz \
    https://ont-exd-int-s3-euwst1-epi2me-labs.s3.amazonaws.com/wf-human-variation/demo_data.tar.gz
tar -xzvf demo_data.tar.gz
```

I get `ERROR 404: Not Found`

Trying to click on the link directly https://ont-exd-int-s3-euwst1-epi2me-labs.s3.amazonaws.com/wf-human-variation/demo_data.tar.gz gives the error `NoSuchKeyThe specified key does not exist.wf-human-variation/demo_data.tar.gz7MMNS5R5HWJ7KYS65nv8NxbLPeMAPBchQV8s3P8h1HeIqF0sOH2Pg2zJaE6k3emHOrwDGjQu9K7q8sM+5xZE7j46Cdk=`

### Operating System

macOS

### Workflow Execution

Other (please describe)

### Workflow Execution - EPI2ME Labs Versions

Running in conda environment in a Jupyter notebook

### Workflow Execution - Execution Profile

Conda

### Workflow Version

Downloaded the workflow today 220826

### Relevant log output

```shell
--2022-08-26 11:23:45--  https://ont-exd-int-s3-euwst1-epi2me-labs.s3.amazonaws.com/wf-human-variation/demo_data.tar.gz
Resolving ont-exd-int-s3-euwst1-epi2me-labs.s3.amazonaws.com (ont-exd-int-s3-euwst1-epi2me-labs.s3.amazonaws.com)... 52.92.16.113
Connecting to ont-exd-int-s3-euwst1-epi2me-labs.s3.amazonaws.com (ont-exd-int-s3-euwst1-epi2me-labs.s3.amazonaws.com)|52.92.16.113|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2022-08-26 11:23:46 ERROR 404: Not Found.


gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: Error is not recoverable: exiting now
```

**Comment by cjw85** [comment]
@SamStudio8,

Looks like we haven't uploaded any demo data?

**Comment by SamStudio8** [comment]
Sorry @felixm3! This should have been uploaded now.

**Comment by felixm3** [comment]
Got it.

Thank you!
