### ISSUE TITLE
Not able to run pipeline in google cloud or aws batch

### ISSUE THREAD

**Issue by YussAb** [epi2me-labs/wf-human-variation#101]
### Operating System

macOS

### Other Linux

M1

### Workflow Version

v.1.8.3

### Workflow Execution

Command line

### CLI command run

nextflow run main.nf \
		 -profile google \
		 --snp \
		 --bam 'gs://mybucket/demo_data/demo.bam' \
		 --bed 'gs://mybucket/demo_data/demo.bed' \
		 --ref   'gs://mybucket/demo_data/demo.fasta' \
		 --basecaller_cfg dna_r10.4.1_e8.2_400bps_hac@v4.1.0 \
		 --sample_name MY_SAMPLE \
		 --out_dir 'gs://mybucket/results' \
		 --threads 8 \ 
		 -resume

### Workflow Execution - CLI Execution Profile

custom

### What happened?

Dear EPI2ME,

I'm trying to run your pipeline with your demo data.
I was able to run the entire pipeline on my local machine.
However, I'm not able to run it on google cloud or aws batch.
That's strange to me, because I have always been able to run pipelines on cloud after testing it locally.

### Relevant log output

```shell
Google:

Error executing process > 'cram_cache (1)'

Caused by:
  Process `cram_cache (1)` terminated with an error exit status (null)

Command executed:

  # Invoke from binary installed to container PATH
  seq_cache_populate.pl -root ref_cache/ demo.fasta
  REF_PATH="ref_cache/%2s/%2s/%s"

Command exit status:
  null

Command output:
  touch: cannot touch '/mnt/disks/mybuckt/DEV/scratch/29/e15c4c08737ec56fba80551948213b/.command.begin': Permission denied/mnt/disks/mybuckt/DEV/scratch/29/e15c4c08737ec56fba80551948213b/.command.run: line 304: /mnt/disks/mybuckt/DEV/scratch/29/e15c4c08737ec56fba80551948213b/.exitcode: Permission denied

Command error:
  cp: cannot create regular file '/mnt/disks/mybuckt/DEV/scratch/29/e15c4c08737ec56fba80551948213b/.command.log': Permission denied

AWS:

Error executing process > 'pipeline:process_references:combine'

Caused by:
  Essential container in task exited

Command executed:

  cat reference_*_.fasta > combined_refs.fasta
  # make sure all sequence IDs are unique
  if [ "$(grep "^>" combined_refs.fasta | sort | uniq -d)" ]; then
      echo "Sequence IDs in the reference files must be unique." 1>&2
      exit 1
  fi
  samtools faidx combined_refs.fasta

Command exit status:
  1

Command output:
  (empty)

Command error:
  mktemp: failed to create directory via template '/tmp/nxf.XXXXXXXXXX': Permission denied
  �[90m1:55PM�[0m �[32mINF�[0m shutdown filesystem start
  �[90m1:55PM�[0m �[32mINF�[0m shutdown filesystem done
```

**Comment by cjw85** [comment]
Our workflows contain too mechanisms to prevent users shooting themselves in the foot:
* our default containers run as a non-root user
* our workflows contain the following line to add the host user to a group within the container: [nextflow.config#L92](https://github.com/epi2me-labs/wf-alignment/blob/master/nextflow.config#L92)

Within cloud environments its typically assumed that a container is running with root permissions. This is the source of your issue. To use our images within cloud environments we rebuild them adding a layer that allows the container to run as root.

**Comment by YussAb** [comment]
Could you explain me better how; "To use our images within cloud environments we rebuild them adding a layer that allows the container to run as root."

**Comment by cjw85** [comment]
You would need to create images derived from ours which add an extra layer:

```
FROM ontresearch/wf-alignment

USER 1
```
