### ISSUE TITLE
What is the reason for the defined resource limit in the .nextflow.config?

### ISSUE THREAD

**Issue by parkerpayne** [epi2me-labs/wf-human-variation#104]
### Ask away!

When using the workflow and attempting to set the number of threads for various tasks, there is a limit that is stored in the .nextflow.config file. It usually has either 4 or 16 threads (I can't remember which) and 8 GB of memory. This limit is entirely arbitrary as far as I can tell, as increasing it allows the workflow to use the correct amount of threads.

My main question is whether this is something you have done, or if it is from nextflow themselves. If it was you, why does this limit exist?

Thank you,
Parker

**Comment by SamStudio8** [comment]
Hi Parker,
These limits were initially introduced by us to give workflows a sensible
resource ceiling when running our workflows on local compute. Each workflow
was configured with defaults that would enable the workflow to run on a
typical device (such as a laptop or a consumer grade desktop).

These limits have caused more trouble than they have solved and we are
actually in the process of phasing the local limits out. wf-human-variation
had these defaults removed in v1.8.2.
