### ISSUE TITLE
How is SVTYPE calculated in html report?

### ISSUE THREAD

**Issue by imdanique** [epi2me-labs/wf-human-variation#106]
### Ask away!

Calculation of SVTYPE in the HTML report does not match the manual calculation in BCFTools. I'm wondering if I'm calculating it correctly. For example, in my sample's HTML report, the INS count is 10,562. However, when I calculate it manually using the following command:
```bash
bcftools view -i 'SVTYPE="INS"' sample.vcf.gz | grep -vc "#"
```
The count is 10,744. I've checked the source function that calculates SVTYPE but couldn't determine why it differs from my calculation

**Comment by SamStudio8** [comment]
Hi @imdanique! Your command is correct, the report summarises variants on Chr 1..22,X,Y. The discrepancy you're observing is the report excluding counts for decoy sequences included with the reference. You should hopefully be able to confirm this with something like the following:

```
bcftools view -i 'SVTYPE="INS"' sample.vcf.gz | grep -v '#' | grep -c '^chr[0-9XY]*\s'
```

**Comment by imdanique** [comment]
@SamStudio8 Thanks for the help! Indeed, I've forgotten to filter out all the unplaced contigs. Now the numbers match
