### ISSUE TITLE
genome build BAM file 

### ISSUE THREAD

**Issue by stefvanbreemen** [epi2me-labs/wf-human-variation#109]
### Ask away!

i am using the wf-alignment workflow with hg38 before this workflow but i keep getting a "the genome build detected in the BAM is not compatible with this workflow", this error keeps accuring while executing the process 'getGenome (1)'. I am wondering what I'm doing wrong and how to do it properly? 
running it on ubuntu 20 and command line.

**Comment by SamStudio8** [comment]
@stefvanbreemen What reference are the reads in your BAM file aligned to? The workflow requires hg19 or hg38 depending on what subworkflows you have selected. Please see the "Genome build compatibility" section of the README https://github.com/epi2me-labs/wf-human-variation/blob/master/README.md.

**Comment by stefvanbreemen** [comment]
they were aligned to the hg38 version of the genome

**Comment by SamStudio8** [comment]
@stefvanbreemen Ah ok, can you open a bug report with the full logs please?
