### ISSUE TITLE
Using older model get dorado error

### ISSUE THREAD

**Issue by ffavero** [epi2me-labs/wf-human-variation#111]
### Operating System

CentOS 7

### Workflow Version

v1.8.3

### Workflow Execution

Command line

### CLI command run

NXF_SINGULARITY_CACHEDIR=$cachedir \
NXF_TEMP=$tmpdir \
NXF_HOME=$nfhome \
NXF_ASSETS=$nfhome/assets \
SINGULARITY_TMPDIR=$tmpdir \
TMPDIR=$tmpdir \
nextflow run /home/projects/cu_10027/data/pipelines/nextflow/epi2me-labs/wf-human-variation/main.nf \
    -c $config \
    -w ${OUTPUT}/workspace \
    -profile singularitypbs \
    --snp --sv --mod \
    --fast5_dir $fast5 \
    --basecaller_cfg 'dna_r9.4.1_e8_hac@v3.3'  \
    --remora_cfg 'dna_r9.4.1_e8_hac@v3.3_5mCG@v0' \
    --bed $target_bed \
    --ref $ref_fa \
    --sample_name $samplename \
    --out_dir ${OUTPUT} -resume

### Workflow Execution - CLI Execution Profile

custom

### What happened?

I initially run the pipeline with the model written in the README

```
    --basecaller_cfg 'dna_r10.4.1_e8.2_400bps_hac@v4.1.0'  
    --remora_cfg 'dna_r10.4.1_e8.2_400bps_hac@v4.1.0_5mCG_5hmCG@v2' 
```

(run first read the manual later)

And I had the problem that the majority of the resulting cram wasn't matching the quality score.
So I read the manual, and checked with those that generated the data, and changed the parameters to

```
    --basecaller_cfg 'dna_r9.4.1_e8_hac@v3.3'  
    --remora_cfg 'dna_r9.4.1_e8_hac@v3.3_5mCG@v0' 
```

And I've got the following error.
Looking at dorado page, it seems the dna_r9.4.1_e8 has been updated to v0.1, and it could also actually run 5mCG_5hmCG.

I can see in the nextflow schema you only give the choiche of dna_r9.4.1_e8_hac@v3.3_5mCG@v0 and not v0.1 (or 5mCG_5hmCG). Is there any reason (I've edited the schema and trying to run v0.1 model)

### Relevant log output

```shell
[56/69ed49] process > publish_artifact (1)                     [ 25%] 1 of 4
WARN: cpus directive is ignored when clusterOptions contains -l option
tip: clusterOptions = { "-l nodes=1:ppn=${task.cpus}:..." }
ERROR ~ Error executing process > 'basecalling:wf_dorado:dorado (2)'

Caused by:
  Process `basecalling:wf_dorado:dorado (2)` terminated with an error exit status (1)

Command executed:

  set +e
  source /opt/nvidia/entrypoint.d/*-gpu-driver-check.sh # runtime driver check msg
  set -e
  dorado basecaller         ${DRD_MODELS_PATH}/dna_r9.4.1_e8_hac@v3.3 .         --modified-bases-models ${DRD_MODELS_PATH}/dna_r9.4.1_e8_ha
c@v3.3_5mCG@v0                  --device cuda:all | samtools view --no-PG -b -o 1.ubam -

Command exit status:
  1

Command output:
  (empty)

Command error:
  INFO:    Converting SIF file to temporary sandbox...
  WARNING: underlay of /etc/localtime required more than 50 (83) bind mounts
  WARNING: underlay of /usr/bin/nvidia-smi required more than 50 (399) bind mounts
  [2023-11-07 14:41:24.102] [info] > Creating basecall pipeline
  [2023-11-07 14:41:25.262] [error] toml::parse: file open error -> /models/dna_r9.4.1_e8_hac@v3.3_5mCG@v0/config.toml
  [main_samview] fail to read the header from "-".
  INFO:    Cleaning up image...

Work dir:
  /home/projects/cu_10027/projects/prostate/data/data_processed/nanopore/analysis/ICGC_PCAL45_T01/workspace/95/9ae4efda36f7a298f24937a1d470
89

Tip: view the complete command output by changing to the process work dir and entering the command `cat .command.out`

 -- Check '.nextflow.log' file for details
```

**Comment by ffavero** [comment]
looking at the models from dorado, it looks like the combination provided in the schema doesn't match the one in the current dorado image

```
const ModelMap models = {

        // v3.{3,4}
        {"dna_r9.4.1_e8_fast@v3.4_5mCG@v0.1",
         {"dab18ae409c754ed164c0214b51d61a3b5126f3e5d043cee60da733db3e78b13"}},
        {"dna_r9.4.1_e8_hac@v3.3_5mCG@v0.1",
         {"349f6623dd43ac8a8ffe9b8e1a02dfae215ea0c1daf32120612dbaabb4f3f16d"}},
        {"dna_r9.4.1_e8_sup@v3.3_5mCG@v0.1",
         {"7ee1893b2de195d387184757504aa5afd76d3feda1078dbc4098efe53acb348a"}},

        {"dna_r9.4.1_e8_fast@v3.4_5mCG_5hmCG@v0",
         {"d45f514c82f25e063ae9e9642d62cec24969b64e1b7b9dffb851b09be6e8f01b"}},
        {"dna_r9.4.1_e8_hac@v3.3_5mCG_5hmCG@v0",
         {"4877da66a0ff6935033557a49f6dbc4676e9d7dba767927fec24b2deae3b681f"}},
        {"dna_r9.4.1_e8_sup@v3.3_5mCG_5hmCG@v0",
         {"7ef57e63f0977977033e3e7c090afca237e26fe3c94b950678346a1982f6116a"}},
```

so hopefully with `dna_r9.4.1_e8_hac@v3.3_5mCG@v0.1` it would work

**Comment by SamStudio8** [comment]
@ffavero Can you confirm the `basecaller_container` from your `nextflow.config`?

**Comment by ffavero** [comment]
> @ffavero Can you confirm the `basecaller_container` from your `nextflow.config`?

ohh, I forgot, I see I have commented out the original and pulled a more recent one.
the original docker image, I tried several time to pull it, all the time the process hanged (left there more that 24h), so I pulled a different image, and it generated the image instantly...

```
        //basecaller_container = "dorado:sha1433bfc3146fd0dc94ad9648452364f2327cf1b0"
        basecaller_container = "dorado:sha06c3f67311887d7976509748ae9357788fafce94"
```
Apologies, so probably this all bug reports loses its meaning

**Comment by SamStudio8** [comment]
@ffavero Ah indeed. The model you've requested appears to be in the `sha1433bfc3146fd0dc94ad9648452364f2327cf1b0` image that v1.8.3 is configured with:
```
singularity exec ontresearch-dorado-sha1433bfc3146fd0dc94ad9648452364f2327cf1b0.img stat /models/dna_r9.4.1_e8_hac@v3.3_5mCG@v0/config.toml
  File: /models/dna_r9.4.1_e8_hac@v3.3_5mCG@v0/config.toml
  Size: 348             Blocks: 1          IO Block: 1024   regular file
Device: 5bh/91d Inode: 9223372036854783643  Links: 1
Access: (0644/-rw-r--r--)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2023-05-25 15:54:16.000000000 +0100
Modify: 2023-05-25 15:54:16.000000000 +0100
Change: 2023-05-25 15:54:16.000000000 +0100
 Birth: -
```
Generally these images are not interchangeable. The schema is used to ensure users can only pick from models that are provided inside the container (hence the `file open error` from Dorado). If you use the container v1.8.3 ships with, you should have the model you are looking for!

With regards to your second question; we do our best to keep up with changes to Dorado and the basecalling models. We run each update to make sure there are no surprises in the workflow and sometimes this takes a little longer than we'd like.
