### ISSUE TITLE
CNV-calling with BED-file (Adaptive sampling)

### ISSUE THREAD

**Issue by fellen31** [epi2me-labs/wf-human-variation#112]
Hi, I would like to do CNV-calling within adaptive sampling target-regions (specified in BED-file). 

Am I right in thinking this is not really possible at the moment? Any suggestions on how this could be done?

**Comment by vlshesketh** [comment]
Hi @fellen31, yes that's correct, it's not possible to supply a BED file to QDNAseq to do the type of CNV calling you describe.  However we are actively exploring alternative CNV callers and will keep this requirement in mind - please do keep an eye on the repository for forthcoming updates.
