### ISSUE TITLE
vcf file from sv workflow have no header 

### ISSUE THREAD

**Issue by carolinehey** [epi2me-labs/wf-human-variation#118]
### Is your feature related to a problem?

The vcf file cant be used in eg. IGV unless you include the CHROM header line (starting with one #) 

### Describe the solution you'd like

The header should be included by default

### Describe alternatives you've considered

i have no alternatives

**Comment by RenzoTale88** [comment]
Hi @carolinehey could you provide us with more details on the run? What components did you run, which VCF presents the issue, system details etc

**Comment by carolinehey** [comment]
Hei,
This was my nextflow command: nextflow run epi2me-labs/wf-human-variation -r v1.8.2 -w /data/wf_hum_C -profile standard --phase_mod --cnv --sv --bin_size 50 -c /longread/resources/increase_memory.config --bam_min_coverage 1 --bam 112577795012_PAQ91410_ubam.bam --ref --ref /longread/resources/reference_genomes/GRCh38_Hg38/GRCh38_decoy_no_alt.fasta --sample_name 112577795012_PAQ91410_hg38 -resume.

It is the sv.vcf file that lack the header, but as far as i know it has never been there. None of our ealier produced vcf files form the sv workflow have it.  
![image](https://github.com/epi2me-labs/wf-human-variation/assets/98043249/7e885d4e-d46b-48a2-ba91-cef7ca30c298)

Let me know if you need more information.

**Comment by RenzoTale88** [comment]
@carolinehey I think we need to reverse engineer the issue here. Would you mind sharing the `.nextflow.log` file you obtained from the workflow? From there on, we can try to figure out where things have gone wrong and why.

**Comment by carolinehey** [comment]
[.nextflow.log](https://github.com/epi2me-labs/wf-human-variation/files/13456307/default.nextflow.log)

**Comment by RenzoTale88** [comment]
Weird, I can't see any error in the log. Could you try rerunning the workflow using the latest version (`v1.9.0`) and let us know whether you encounter the same issue?

**Comment by carolinehey** [comment]
There is no error in the run. It has been running just fine except that the output file is missing an important component if you want to use it further. As far as i see the header (#CHROM) has never been there, not in newer runs and versions and not in older runs and versions. I actually just want you to include it :)

**Comment by RenzoTale88** [comment]
@carolinehey would you be ok with running a test for me? Could you proceed as follow:

Clone the repository at the right version:
```
git clone -b v1.9.0 https://github.com/epi2me-labs/wf-human-variation
```

Replace the appropriate line:
```
sed 's/vcfsort/bcftools sort -m 2G -T .\/ -O v/g' wf-human-variation/modules/local/wf-human-sv
```

Try running the new workflow
```
nextflow run ./wf-human-variation [OPTIONS HERE]
```

**Comment by RenzoTale88** [comment]
@carolinehey I just realised a small mistake in one of the commands above. The second command should be:
```
sed -i 's/vcfsort/bcftools sort -m 2G -T .\/ -O v/g' wf-human-variation/modules/local/wf-human-sv.nf
```

**Comment by RenzoTale88** [comment]
@carolinehey could you please try using v1.9.1

**Comment by carolinehey** [comment]
Sorry for the delay in response. I have tried some tests now and the SV workflow gives this error in the repport. 
![image](https://github.com/epi2me-labs/wf-human-variation/assets/98043249/1abe3932-d2c3-4bf3-ba9c-d5c7fa88a954)

**Comment by RenzoTale88** [comment]
@carolinehey is this with `v1.9.1` of the workflow?

**Comment by carolinehey** [comment]
Yes 
![image](https://github.com/epi2me-labs/wf-human-variation/assets/98043249/e62a749a-72bd-4fe3-a82f-6f2a6a11eba2)

**Comment by RenzoTale88** [comment]
Thanks for confirming this. Does the resulting VCF appears well formed this time? Or do you still have the missing header line?

**Comment by RenzoTale88** [comment]
Could you please check that the VCF file in here:
```
/data/wf_hum_var_work_E1/2b/43e78ca*/*.vcf.gz
```

Has the correct header?

**Comment by RenzoTale88** [comment]
Ok thanks for confirming this. I'll close this issue as fixed, and could you please open a new github issue with the details of this new error? Thanks in  advance!
