### ISSUE TITLE
targeted gVCF file

### ISSUE THREAD

**Issue by stefvanbreemen** [epi2me-labs/wf-human-variation#119]
### Ask away!

for my workflow  i need to have a gVCF with only certain regions of the genome. I have tried this with the --bed option but this doesn't seem to do the right thing.  so my question is:

should it work via a bed file with the --bed option?

if not:
is it possible within this pipeline?

**Comment by RenzoTale88** [comment]
@stefvanbreemen thanks for letting us know about this. We are looking into it.

**Comment by RenzoTale88** [comment]
@stefvanbreemen could you please try with the latest version of the workflow and let us know if this fixes it?
```
nextflow run epi2me-labs/wf-human-variation -r v1.9.1 [OPTIONS HERE]
```

**Comment by stefvanbreemen** [comment]
sorry for the late reaction, it did work. 
thank you very much!
