### ISSUE TITLE
[Bug]: workflow fails with a stranded BAM file.

### ISSUE THREAD

**Issue by mattloose** [epi2me-labs/wf-human-variation#12]
### What happened?

Passing a stranded BED file with overlapping co-ordinates can cause the pipeline to crash.

As an example the following BED file will cause the pipeline to crash:

`chr1    1393173 1421564 .       .       +
chr1    1393173 1421564 .       .       -`

This will result in mosdepth producing a bed file wiht an extra column which will subsequently cause the script get_filter_calls_command.py to error out as it attempts to convert a "." character into a float.

This can be solved by removing all strand info from the bam file. But in our case we would like to keep that if possible.

### Operating System

ubuntu 20.04

### Workflow Execution

Command line

### Workflow Execution - Execution Profile

Singularity

### Workflow Version

0.4.0

### Relevant log output

```shell
Sorry - did not capture helpful log output for you.
```

**Comment by SamStudio8** [comment]
Sorry @mattloose, managed to miss this one! @RenzoTale88 is plotting to fix this as we speak.

**Comment by mattloose** [comment]
That's what I call speedy service.

**Comment by mattloose** [comment]
Actually - just been caught out by this yet again! Weird.

**Comment by SamStudio8** [comment]
Better late that never, this has now been fixed in wf-human-variation 1.6.0. Please let me know how you get on, thanks!

**Comment by mattloose** [comment]
I can assure you that I will provide you with many updates.

**Comment by RenzoTale88** [comment]
Close as fixed in v1.6.0
