### ISSUE TITLE
Process snp:pileup_variants (102) terminated with an error exit status (135) -> runtime: cannot allocate memory

### ISSUE THREAD

**Issue by sklages** [epi2me-labs/wf-human-variation#127]
### Operating System

Other Linux (please specify below)

### Other Linux

inhouse Linux, 64bit, based on LFS

### Workflow Version

v1.9.1-gdfde912

### Workflow Execution

Command line

### CLI command run

```bash
nextflow run epi2me-labs/wf-human-variation \
    -w ${OUTPUT}/workspace \
    -profile singularity \
    -offline \
    --snp \
    --disable_ping \
    --bam /path/to/aligned.bam \
    --basecaller_cfg "dna_r9.4.1_e8_sup@v3.3" \
    --ref /path/to/hg19.fa \
    --sample_name SAMPLE \
    --out_dir ${OUTPUT}
```

### Workflow Execution - CLI Execution Profile

singularity

### What happened?

I actually tried a few different command lines (without alignment), always running into OOM issues when using `--snp`. Others like `--mod` work just fine (probably because `modkit` does not use java?).
System has around 850G free memory .. 

After java fails with OOM, there are still a bunch of `clair3.py CallVariantsFromCffi` jobs running ... 

### Relevant log output

```shell
OpenJDK 64-Bit Server VM warning: INFO: os::commit_memory(0x00007f132a200000, 65536, 0) failed; 
  error='Not enough space' (errno=12)

# There is insufficient memory for the Java Runtime Environment to continue.
# Native memory allocation (mmap) failed to map 65536 bytes for committing reserved memory.
# An error report file with more information is saved as:
# /path/to/wf-human-variation/hs_err_pid12377.log
[796.249s][warning][os] Loading hsdis library failed
```

- complete log: https://comanche.molgen.mpg.de/external/error-reform.txt

**Comment by SamStudio8** [comment]
Thanks for this report @sklages. My guess is we're running so many Clair3 SNP tasks simultaneously we're crippling your box and the Nextflow head job cannot continue. We are updating all our workflows to declare more sensible memory requirements to try and avoid this going forward. In the mean time you should be able to effectively throttle these large parallel processes by forcing them to use more CPUs:

If you create a file named `throttle_clair.config` with the contents:
```
process {
    withName:pileup_variants {
        cpus = 2
    }
    withName:evaluate_candidates {
        cpus = 2
    }
}
```

You can add `-c throttle_clair.config` to your `nextflow run` invocation to supply this additional configuration. This will cause Nextflow to run half as many of the parallel Clair3 jobs at a time (as these processes declare 1 CPU by default). You may need to tweak this a little if the problem continues.

**Comment by sklages** [comment]
@SamStudio8 - thanks for your hint.

with `cpus = 2` I still get an OOM error,   "MemoryError". This time directly thrown by clair3/python.

Just trying to understand how this works: 
My server (physically) has N cores, so Clair3 starts N jobs on that server (not taking actual load into account) with `cpus=1`. When increasing to `cpus=2`, there are just N/2 jobs started. The most extreme case would be if I set `cpus=N` which would start just a single job? 

Did I get it right?

**Comment by SamStudio8** [comment]
@sklages Thanks for trying that. We're making progress if it's at least Clair being killed now! Yes that's right, although perhaps a more straightforward way to tweak this might be to use `maxForks` which directly sets how many parallel tasks of a particular process Nextflow is allowed to start:

```
process {
    withName:pileup_variants {
        maxForks = N
    }
    withName:evaluate_candidates {
        maxForks = N
    }
}
```

As I mentioned we're working on re-releasing all our workflows with better CPU and Memory declarations but I'd recommend in the interim that you set N here to something around (<total RAM GB> / 8). As you mentioned, in the extreme case you can use this directive to force the jobs in serial with N=1. I hope this helps but please get in touch otherwise!

**Comment by sklages** [comment]
@SamStudio8 - ok, got it :-)

.. given `my_server` → 128 Cores, ~850G free memory

### cpus variation
- `cpus=1` → OOM (java)
- `cpus=2` → OOM (clair3/python)
- `cpus=12` → OK, `mem usage ~210G`
- `cpus=33` → OK, `mem usage ~64G`

### maxForks variation
- `maxForks=24 cpus=1` → OK, `mem usage ~515G`
- `maxForks=10 cpus=1` → OK, `mem usage ~207G` (this roughly corresponds to `cpus=12` when leaving `maxForks` untouched. Both setting result in ~ 10 tasks).

**Comment by SamStudio8** [comment]
@sklages Great! You might find you can tune your maxForks a little higher as it would seem that 24 processes is not hitting your maximum memory. I'll close this issue now as it looks like you're able to continue running the workflow, but please open another issue if you encounter other troubles!
