### ISSUE TITLE
EPI2ME Error : Validation of pipeline parameters failed!

### ISSUE THREAD

**Issue by handoko12u** [epi2me-labs/wf-human-variation#128]
### Ask away!

Below is my command:

sysadmin@sysadmin:~/Downloads/nextflow$ nextflow run epi2me-labs/wf-human-variation –help
N E X T F L O W  ~  version 23.10.0
NOTE: Your local project version looks outdated - a different revision is available in the remote repository [04c3b27058]
Launching `https://github.com/epi2me-labs/wf-human-variation` [happy_church] DSL2 - revision: 91dc78c063 [master]

ERROR ~ ERROR: Validation of pipeline parameters failed!

 -- Check '.nextflow.log' file for details
ERROR ~ * Bad parameter configuration. You must select at least one of:
    --sv
    --snp
    --cnv
    --str
    --methyl

 -- Check '.nextflow.log' file for details
ERROR ~ * Missing required parameter: --ref

 -- Check '.nextflow.log' file for details
ERROR ~ * Bad parameter configuration. You must select only one option of:
    --fast5_dir
    --bam

 -- Check '.nextflow.log' file for details

Questions:

1. When running this command, I suppose it will show help, displaying various options available, but why it turned out to be error?

2. It stated my local project looks outdated, what should I do? Prior to this, I have updated my nextflow  to version 23.10.0.5889.

Please anyone can help me? 

Thank you very much

**Comment by hyunjokoo** [comment]
1. Please make sure you typed `--help` instead of `–help`.

2. The version is not about Nestflow but about wf-human-variation. I think wf-human-variation is updated automatically. Although v1.9.2 was released my version is still v1.9.1. I think it takes some time for the update.

**Comment by cjw85** [comment]
Nextflow workflows are not updated automatically by nextflow. See the Nextflow documentation for how to [update workflows](https://www.nextflow.io/docs/latest/sharing.html#pulling-or-updating-a-project).

**Comment by hyunjokoo** [comment]
> Nextflow workflows are not updated automatically by nextflow. See the Nextflow documentation for how to [update workflows](https://www.nextflow.io/docs/latest/sharing.html#pulling-or-updating-a-project).

Oh. Thank you. Good information!!
