### ISSUE TITLE
Enable output of mitochondrial variants

### ISSUE THREAD

**Issue by phillip-richmond-alamya** [epi2me-labs/wf-human-variation#130]
### Is your feature related to a problem?

There are no mitochondrial variants reported in the output SNP file

### Describe the solution you'd like

It looks like the haplotagged.bam doesn't output reads over chrM, but the pre-haplotagging BAM does. 

### Describe alternatives you've considered

I'm using this pipeline, it should output these well covered genomic variants. 

### Additional context

I think clair3 should still call them?

**Comment by RenzoTale88** [comment]
@phillip-richmond-alamya the default behaviour of the workflow is to consider only the chromosomal sequences. You can override this behaviour by setting `--include_all_ctgs` at run time, and you should also generate the variants for chrM.

**Comment by phillip-richmond-alamya** [comment]
Ahhhh thank you!! Simple fix!
