### ISSUE TITLE
4.3.0 clair3 models

### ISSUE THREAD

**Issue by mulderdt** [epi2me-labs/wf-human-variation#132]
### Ask away!

Hi,

The 4.3.0 models are out in the rerio repository. They are also available in the wf-basecalling workflow. But it seems if I use the 4.3.0 model there then I cannot use the wf-human-variation workflow since it is not in the definition file set.

I thought I could side load it using the basecaller_cfg custom and basecaller_model_path parameters but then I am blocked on clair3 because it is not defined in the https://github.com/epi2me-labs/wf-human-variation/blob/master/data/clair3_models.tsv set.

Is there any way to get small variant calling on a 4.3.0 model basecalled bam set with the current workflow version or do I have to wait for an update to this workflow?

Thanks

**Comment by RenzoTale88** [comment]
Hi @mulderdt you can provide custom models to the workflow via the `--clair3_model_path /PATH/TO/model/`

Andrea
