### ISSUE TITLE
Calculate repeat expansion of RFC1

### ISSUE THREAD

**Issue by vroni** [epi2me-labs/wf-human-variation#135]
I have tried the wf-human-variation on a few of our samples and there is no calculation of the repeat expansion of the RFC1 locus. The other loci are calculated as expected.
RFC1 does not show up in the str-report and does not appear in the wf_str.straglr.tsv output file. However, when looking at the code I can see that RFC1 is configured correctly in the wf_str_repeats.bed regions file as well as the variant_catalog_hg38.json annotation file. I was not able to find anything in the code that pointed to an exclusion of the region but I am wondering if there is a deliberate omission within the nextflow workflow of RFC1 that I am not seeing?

According to [this GitHub Issue](https://github.com/bcgsc/straglr/issues/19) it looks like the straglr developers have already considered RFC1 and implemented for the locus.

**Comment by vlshesketh** [comment]
Hi @vroni thank you for reporting this. We are aware that there is an issue reporting the repeat expansion on RFC1 and will update with a fix shortly.
