### ISSUE TITLE
Joint phasing with methylations

### ISSUE THREAD

**Issue by ythuang0522** [epi2me-labs/wf-human-variation#137]
### Is your feature related to a problem?

No. This is from the LongPhase team. We saw the new [release](https://github.com/epi2me-labs/wf-human-variation?tab=readme-ov-file#8-phasing-variants) includes joint phasing of SNPs, indels, and SVs by LongPhase. My understanding of the "phased bedMethyl" seems not jointly phasing SNPs, indels, and SVs from the beginning (correct me if I am wrong). We have implemented [joint phasing with (5mC) modifications ](https://github.com/twolinin/longphase?tab=readme-ov-file#snp-and-modification-co-phasing)in LongPhase. It looked to us the phasing range (N50) can be significantly improved by SNP-modification co-phasing (see attached figure, HG002, R10.4). Do you consider joint phasing with methylations from the beginning?
![image](https://github.com/epi2me-labs/wf-human-variation/assets/6086073/1fd4917d-4ac3-49e7-bc45-7af64e90f679)

### Describe the solution you'd like

Adding option for joint phasing of SNPs and methylations in LongPhase.

### Describe alternatives you've considered

The SNP-modification co-phasing is based on the (haplotype-specific) methylations called by [modcall](https://github.com/twolinin/longphase?tab=readme-ov-file#modcall-command) in LongPhase. We know you have developed modkit for similar purpose. But we can't find the option for calling haplotype-specific methylations, as well as outputting the read IDs carrying methylations, which are both essential for phasing. Would be helpful to know if we should direct the request to the modkit team, such that LongPhase could also take the output of modkit for joint phasing. Or it's not your priority to jointly phase methylations in the near future. Thank you.

**Comment by asalhab** [comment]
I support @ythuang0522 suggestion. I believe considering DNA methylation information along with SV and SNVs for phasing is an important point. However, wether to include 5mc or 5hmc (or merged) it is another question. Maybe @ythuang0522 has an opinion about it

**Comment by cjw85** [comment]
Hi @ythuang0522,

Thanks for this. You are correct that curretnly the methylation information isn't used to perform phasing. Thank you for taking the time to implement and test this. We'll take a look to see if we can weave this into the workflow.

**Comment by ythuang0522** [comment]
> I support @ythuang0522 suggestion. I believe considering DNA methylation information along with SV and SNVs for phasing is an important point. However, wether to include 5mc or 5hmc (or merged) it is another question. Maybe @ythuang0522 has an opinion about it

 @asalhab The number of 5hmc was much less than that of 5mc by several orders of magnitude when tested one year ago (hundreds v.s. millions, R10.4). We then decided to focus on SNP-5mc co-phasing because the inclusion of 5hmc does not help extend the phasing range. We are not sure if it's due to the limitation of the 5hmc model in ONT. If the sensitivity has improved, we can add 5hmc back.

**Comment by asalhab** [comment]
@ythuang0522 thanks for the clarification. I see your point. it can be related to the data being used. 5hmc is not found dominantly in all cell types. it is found in certain ell types like  neurons and stem cells.
