### ISSUE TITLE
docker: failed to register layer

### ISSUE THREAD

**Issue by lmallin** [epi2me-labs/wf-human-variation#139]
### Operating System

Other Linux (please specify below)

### Other Linux

Ubuntu 20:04

### Workflow Version

v1.10.1

### Workflow Execution

Command line

### CLI command run

nextflow run epi2me-labs/wf-human-variation -w out/output/workspace -profile standard --bam sampleA.cram --ref genome.fasta --snp --threads 32 --sample_name sampleA --sex female --basecaller_cfg dna_r10.4.1_e8.2_400bps_hac@v4.1.0 --out_dir out/output

### Workflow Execution - CLI Execution Profile

standard (default)

### What happened?

I've encountered an issue running **v1.10** wf-human-variation, specifically with the `--snp` option.  

`docker: failed to register layer: ApplyLayer exit status 1 stdout:  stderr: failed to Lchown "/home/epi2melabs/models/r941_prom_sup_g5014" for UID 1000088, GID 100 (try increasing the number of subordinate IDs in /etc/subuid and /etc/subgid): lchown /home/epi2melabs/models/r941_prom_sup_g5014: invalid argument.`

I encountered this issue previously in **v1.3.0** (bug report #35 ) and it was fixed in **v1.4.0**.  I've been running the workflow since then on DNAnexus cloud platform with no issues until **v1.10** was released.

Is it possible to get this issue fixed again please?

### Relevant log output

```shell
Feb-07 13:04:11.685 [Task monitor] DEBUG n.processor.TaskPollingMonitor - Task completed > TaskHandler[id: 8; name: report_snp:getParams; status: COMPLETED; exit: 125; error: -; workDir: /home/dnanexus/out/output/workspace/d6/dc16c10f622ffcf3d11055e280c3de]
Feb-07 13:04:11.689 [Task monitor] DEBUG nextflow.processor.TaskProcessor - Handling unexpected condition for
  task: name=report_snp:getParams; work-dir=/home/dnanexus/out/output/workspace/d6/dc16c10f622ffcf3d11055e280c3de
  error [nextflow.exception.ProcessFailedException]: Process `report_snp:getParams` terminated with an error exit status (125)
Feb-07 13:04:11.698 [Task monitor] ERROR nextflow.processor.TaskProcessor - Error executing process > 'report_snp:getParams'

Caused by:
  Process `report_snp:getParams` terminated with an error exit status (125)

Command executed:


Command exit status:
  125

Command output:
  (empty)

  docker: failed to register layer: ApplyLayer exit status 1 stdout:  stderr: failed to Lchown "/home/epi2melabs/models/r941_prom_sup_g5014" for UID 1000088, GID 100 (try increasing the number of subordinate IDs in /etc/subuid and /etc/subgid): lchown /home/epi2melabs/models/r941_prom_sup_g5014: invalid argument.

  Feb-07 13:04:11.868 [Task monitor] DEBUG n.processor.TaskPollingMonitor - Task completed > TaskHandler[id: 4; name: report_snp:getVersions; status: COMPLETED; exit: 125; error: -; workDir: /home/dnanexus/out/output/workspace/6e/d7199f6352b9a25be78447be9cdadc]
Feb-07 13:04:11.869 [Task monitor] DEBUG nextflow.processor.TaskProcessor - Handling unexpected condition for
  task: name=report_snp:getVersions; work-dir=/home/dnanexus/out/output/workspace/6e/d7199f6352b9a25be78447be9cdadc
  error [nextflow.exception.ProcessFailedException]: Process `report_snp:getVersions` terminated with an error exit status (125)
Feb-07 13:04:11.871 [Task monitor] DEBUG n.processor.TaskPollingMonitor - Task completed > TaskHandler[id: 7; name: lookup_clair3_model (1); status: COMPLETED; exit: 125; error: -; workDir: /home/dnanexus/out/output/workspace/93/6159d3b94689c3d75ca0638c3537dc]
Feb-07 13:04:11.872 [Task monitor] DEBUG nextflow.processor.TaskProcessor - Handling unexpected condition for
  task: name=lookup_clair3_model (1); work-dir=/home/dnanexus/out/output/workspace/93/6159d3b94689c3d75ca0638c3537dc
  error [nextflow.exception.ProcessFailedException]: Process `lookup_clair3_model (1)` terminated with an error exit status (125)
```

### Were you able to successfully run the latest version of the workflow with the demo data?

no

**Comment by SamStudio8** [comment]
Thanks for the report @lmallin, will investigate.

**Comment by ilivyatan** [comment]
I'm getting the same error on DNAnexus on a whole genome sequence, already aligned, so starting with the BAM file.
I ran the exact same workflow about two months ago and it was fine.
The workflow pulls the latest version of the wf-human-variation from git so something changed in the later version.
I was using an instance with 125GB RAM, >500GB ssd and 16 cores.

Some of the error msgs:
ERROR ~ Error executing process > 'report_snp:getParams'
Caused by:
Process `report_snp:getParams` terminated with an error exit status (125)
...
21946decad33: Pull complete
433c130e6e79: Download complete
docker: failed to register layer: ApplyLayer exit status 1 stdout: stderr: failed to Lchown "/home/epi2melabs/models/r941_prom_sup_g5014" for UID 1000088, GID 100 (try increasing the number of subordinate IDs in /etc/subuid and /etc/subgid): lchown /home/epi2melabs/models/r941_prom_sup_g5014: invalid argument.

**Comment by SamStudio8** [comment]
@ilivyatan We have identified the regression that caused this and will be updated the image shortly. We'll squeeze this in to the imminent wf-human-variation v1.11.0 release.

**Comment by lmallin** [comment]
@SamStudio8 amazing, thanks very much!  I'll keep an eye out for the new release.
