### ISSUE TITLE
Using singularity to test the demo data 

### ISSUE THREAD

**Issue by heksaani** [epi2me-labs/wf-human-variation#140]
### Ask away!

Hey I am trying to run the workflow in HPC which does not have docker, how could I use singularity to run the pipeline ?

**Comment by SamStudio8** [comment]
@heksaani The workflow has a Singularity profile which can be activated with `-profile singularity`. You may need to speak to your HPC administrator to find out if you need to set [additional configuration options](https://www.nextflow.io/docs/latest/config.html#config-singularity) for Nextflow to work with Singularity on your HPC.

**Comment by heksaani** [comment]
Thank you !
