### ISSUE TITLE
missing bedgraph

### ISSUE THREAD

**Issue by VICTO160** [epi2me-labs/wf-human-variation#141]
### Operating System

CentOS 7

### Workflow Version

v1.10.1

### Workflow Execution

Command line

### CLI command run

$NEXTFLOW -c .threads.txt run epi2me-labs/wf-human-variation -revision v1.10.1 \
    -profile singularity \
    -w ${OUTPUT}/variation_workspace \
    --bam ${SAMPLE}.sorted.aligned.bam \
    --ref ${REFS} \
    --tr_bed $TRBED \
    --sample_name ${SAMPLE} \
    --out_dir ${OUTPUT} \
    --threads 36 \
    --cnv \
    --bin_size 1 \
    --depth_intervals

### Workflow Execution - CLI Execution Profile

singularity

### What happened?

depth_intervals flag was supposed to output a bedgraph file (initially offered in v1.4).  No *.bedgraph was written.  The data is probably equivalent to what's in the *per-base.bed.gz or *regions.bed.gz output.  I'm just confused if the file was written correctly but with the wrong extension.

### Relevant log output

```shell
NA
```

### Were you able to successfully run the latest version of the workflow with the demo data?

other (please describe below)

### Other demo data information

```shell
The workflow executed fine with the aforementioned issue.
```

**Comment by SamStudio8** [comment]
Hi @VICTO160, the depth_intervals flag turns on the additional processing in mosdepth to output the per-base files you've mentioned. You have the correct files - but we'll make this clearer in our documentation for our next release. Thanks!
