### ISSUE TITLE
Input: Tandem repeat  BED file: should specify file rather than directory

### ISSUE THREAD

**Issue by nikelau** [epi2me-labs/wf-human-variation#143]
### Operating System

Windows 11

### Workflow Version

1.11.0

### Workflow Execution

EPI2ME Desktop application

### EPI2ME Version

EPI2ME V5.1.9

### Workflow Execution - CLI Execution Profile

None

### What happened?

Hi developers just a minor issue - for the bed file input the default only allows input of a folder directory, but a .bed file is actually required. Would be great if that issue can be fixed. Thanks! 

### Relevant log output

```shell
nil
```

### Were you able to successfully run the latest version of the workflow with the demo data?

yes

**Comment by SamStudio8** [comment]
Hi @nikelau, looks like tr_bed is listed as a Path in the schema which should allow for selection of files and directories, but you're right in that we don't need to support directories for this parameter at all. We'll fix this in our next release! Thanks for your feedback.

**Comment by nikelau** [comment]
> Hi @nikelau, looks like tr_bed is listed as a Path in the schema which should allow for selection of files and directories, but you're right in that we don't need to support directories for this parameter at all. We'll fix this in our next release! Thanks for your feedback.

Thank you Sam! I tried choosing the bed file but it seemed I could only select a folder directory. Would be great to have it working soon!

**Comment by f-marchi** [comment]
+1 - It seems that the appropriate bed file cannot be added, and if a dir containing that file is used, the workflow crashes.

**Comment by vlshesketh** [comment]
Hi @nikelau and @f-marchi, this has now been fixed in the workflow, so you can now select a file for the `tr_bed` parameter.

**Comment by nikelau** [comment]
Thanks to the Epi2me team!
