### ISSUE TITLE
For non-model reference genome?

### ISSUE THREAD

**Issue by CWYuan08** [epi2me-labs/wf-human-variation#146]
### Ask away!

hi, I am running this analysis again for other non-model species:

nextflow run epi2me-labs/wf-human-variation --bam final_merged.bam --basecaller_cfg 'clair3:dna_r10.4.1_e8.2_260bps_sup@v4.0.0' --ref ref.dna.toplevel.fasta --sample_name barcode01 --snp --sv -profile singularity --phased, I am getting this issue again:

Caused by:
Process getGenome (1) terminated with an error exit status (65)

Command executed:

samtools idxstats final_merged.bam > final_merged.bam_genome.txt
get_genome.py --chr_counts final_merged.bam_genome.txt -o output.txt
genome_build=cat output.txt

what should I change for the current version?

Thank you very much for your help!!

**Comment by vlshesketh** [comment]
Hi @CWYuan08, for non-human genomes, you will need to set `--annotation false`, otherwise the workflow will try to determine which human genome build is being used, which leads to the `getGenome` error you've seen. Switching off annotation will bypass this stage, allowing you to analyse non-human genomes with the workflow.

**Comment by CWYuan08** [comment]
Dear @vlshesketh, 

thank you very much for prompt reply! I added --annotation false (nextflow run epi2me-labs/wf-human-variation --bam final_merged.bam  --ref ref.dna.toplevel.fasta --sample_name barcode01 --snp --sv  -profile singularity  --annotation false), but I'm still getting this error:

ERROR ~ Error executing process > 'getGenome (1)'

Caused by:
  Process `getGenome (1)` terminated with an error exit status (65)

Command executed:

  samtools idxstats final_merged.bam > final_merged.bam_genome.txt
  get_genome.py --chr_counts final_merged.bam_genome.txt -o output.txt 
  genome_build=`cat output.txt`

Command exit status:
  65

Command output:
  (empty)

Command error:
  The genome build detected in the BAM is not compatible with this workflow.

I'm not sure why...

Thank you very much for your help!

Best,
CW

**Comment by vlshesketh** [comment]
Hi @CWYuan08 thank you for the update - I'll see if I can replicate this and get back to you.

**Comment by vlshesketh** [comment]
Hi @CWYuan08 can you please confirm which version of the workflow you are running? I have just run the most [recent version](https://github.com/epi2me-labs/wf-human-variation/releases/tag/v1.11.0) using the snp demo data, with annotation set to false, and this has bypassed the `getGenome` process as expected, so I'm unable to replicate the the issue as you've described - if you can double check the workflow version that would be really helpful.

**Comment by CWYuan08** [comment]
Dear @vlshesketh,
I checked nextflow info epi2me-labs/w-human-variation 
I got:
 project name: epi2me-labs/wf-human-variation
 repository  : https://github.com/epi2me-labs/wf-human-variation
 local path  : /mnt/user/.nextflow/assets/epi2me-labs/wf-human-variation
 main script : main.nf
 description : Basecalling, SNV calling, SV calling, methylation calling of human samples.
 author      : Oxford Nanopore Technologies 
 revisions   :
 * master (default)

should I switch to v1.11.0?

Thank you very much for your help!

**Comment by CWYuan08** [comment]
Dear @vlshesketh,

thank you for your help I have managed to run the pipeline. As this is not a model organism, it has different number of chromosomes compared to human. I found out the variant vcf file stopped at chromosome 22, is this because the default is human?

Best,
CW

**Comment by vlshesketh** [comment]
Hi @CWYuan08, I'm glad you're now able to run the pipeline! For non-human genomes, you will need to use the parameter `--include_all_ctgs`, to ensure all contigs in your reference genome are used for variant calling. Please let us know if you are able to run the workflow successfully with this parameter.

**Comment by Aravind-mss** [comment]
Hi There, I am unable to progress any further with a similar issue. But in my case it's with the Human genome. I tried a couple of versions (hg38 & T2Tv2) and it aborts at the same step of getGenome(). I tried with both mapped and unmapped BAM as input, but no luck. Any pointers to get around this issue are much appreciated. Thanks.

**Comment by vlshesketh** [comment]
Hi @Aravind-mss, apologies for the delay in responding. Please can you try with the recommended human genome build - as mentioned in the workflow documentation, we would advise the use of [this reference](http://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/000/001/405/GCA_000001405.15_GRCh38/seqs_for_alignment_pipelines.ucsc_ids/GCA_000001405.15_GRCh38_no_alt_analysis_set.fna.gz) as per [this](https://lh3.github.io/2017/11/13/which-human-reference-genome-to-use) blog post. You shouldn't need to re-align your BAM as the workflow will perform this for you.

**Comment by vlshesketh** [comment]
Hi @Aravind-mss I'm closing this issue now as there have been no further replies, but please open a new issue if you require further support.
