### ISSUE TITLE
Update wf-human-variation in an environment without internet access

### ISSUE THREAD

**Issue by ParkShinHyun** [epi2me-labs/wf-human-variation#147]
### Ask away!

I installed wf-human-variation for the first time last year and have been using version v1.9.0. To use it in an environment without internet access, I initially initialized wf-human-variation and then copied the singularity image to an environment without internet access. If I want to use the latest version, v1.11.0, should I move the existing v1.9.0 image file elsewhere and then initialize wf-human-variation? Also, if I need to use version v1.9.0 again depending on the situation, is there a way to do that?

**Comment by SamStudio8** [comment]
You can download the v1.11 images to the same directory as you have stored your v.1.9 images as they will have different file names. There are a few ways to support swapping the versions of the workflow depending on how you have installed the workflow. If you run the workflow from Github (eg. `nextflow run epi2me-labs/wf-human-variation`, you can use the `-r` option to set the version). Alternatively if you clone the repository to run the workflow, you can use git to change the currently checked out version.
