### ISSUE TITLE
Speeding up snp variant calling?

### ISSUE THREAD

**Issue by Krysasp** [epi2me-labs/wf-human-variation#148]
### Ask away!

Hi there. Is there anyway to run the subprocess of Clair3 variant caller, 'CallVariantsFromCffi ' in parallel or allocating more chuncks to speed it up? I noticed there isn't an option to multi-thread it, only python Clair3 does..  the snp calling using Cffi progresses slow on my local cluster. ...

**Comment by SamStudio8** [comment]
wf-human-variation already parallelises the CallVariantsFromCffi steps across all chunks generated by Clair3. If you are seeing performance issues with wf-human-variation on your cluster, please can you provide more information by [opening a Bug report](https://github.com/epi2me-labs/wf-human-variation/issues/new?assignees=&labels=triage&projects=&template=bug_report.yml) for us to take a look.
