### ISSUE TITLE
Specifying bin_size for Spectre cnv

### ISSUE THREAD

**Issue by fidibidi** [epi2me-labs/wf-human-variation#153]
### Ask away!

Hello, 

I see as of yesterday with the newest release qdnaseq is no longer the default CNV caller. 
One feature I'm curious about is the ability to specify bin_size to spectre, as this was a feature of the QDNAseq. Is this not possible currently? 

Thanks.

**Comment by vlshesketh** [comment]
Hi @fidibidi, that's correct. Spectre is optimised to work with a mosdepth window size of 1000 and so we haven't exposed a parameter to change this.
