### ISSUE TITLE
How do I find out which version has been used?

### ISSUE THREAD

**Issue by sklages** [epi2me-labs/wf-human-variation#156]
### Ask away!

- How do I find out which version of the workflow has been used in some results data sets?
- Is there a way to specify a specific version when running the workflow?

**Comment by SamStudio8** [comment]
Hi @sklages, thanks for your question - it would appear that the reports
for some of our workflows are not correctly passing through the workflow
version, I've opened a ticket to take a look at this.

To run a particular version, you can use the revision flag -r with the
"nextflow pull" and "nextflow run" commands. See
https://www.nextflow.io/docs/latest/sharing.html#handling-revisions for
more information.

**Comment by SamStudio8** [comment]
I should add if you're using the EPI2ME Desktop application, the workflow
options screen also has options for version management.

**Comment by SamStudio8** [comment]
@ajeffs @sklages Thanks for your requests on this issue - the workflow HTML reports now feature the workflow version as part of the banner and footer.
