### ISSUE TITLE
.apptainer/cache

### ISSUE THREAD

**Issue by selmapichot** [epi2me-labs/wf-human-variation#159]
### Ask away!

Hi, 
is it possible to change the directory of the .apptainer/cache ? the .apptainer/cache seems to be located in my home directory, and I would like to move it to another directory with sufficient free space. Many thanks

**Comment by RenzoTale88** [comment]
Hi @selmapichot you can change the directories by setting the `NXF_SINGULARITY_CACHEDIR`. You can find more details in the Nextflow's web page [here](https://www.nextflow.io/docs/latest/singularity.html).

**Comment by selmapichot** [comment]
Excellent thank you.
