### ISSUE TITLE
Does the phasing run despite the configuration not to run phasing?

### ISSUE THREAD

**Issue by ilivyatan** [epi2me-labs/wf-human-variation#160]
### Ask away!

Hi,
In my experience with the earlier versions of the workflow, the phasing stage takes a considerable amount of time and dramatically slows the workflow ( days versus hours of runtime).
Therefore, I run it with all the phasing settings off, and then run phasing post-hoc to the workflow.
I've updated to the latest workflow version (11) and the behavior of the long run time has returned.
I reached out to the support and they informed me that running with --str for repeat expansion analysis, will initiate a phasing step even if I haven't configured one.
So now, I've only run with --sv --snv --cnv. But the runtime is still very long (Over 20 hours for a ~20x covered human genome on a cloud platform with 16 cores, 64GB RAM, 600 GB storage).
How can I run the workflow now without invoking any phasing?
Thanks!

**Comment by RenzoTale88** [comment]
Hi @ilivyatan running the workflow with the `--snp --sv --cnv` options should not trigger the generation of phased genotypes and haplotagged reads, unless explicitly requested with `--phased`.

However, please notice that there is still a phasing step as part of the Clair3 software, which cannot be skipped as it is an intrinsic part of the [Clair3 software](https://github.com/HKU-BAL/Clair3/blob/main/scripts/clair3_c_impl.sh#L221).

The processes involved in the generation of phased variants are the following:
1) `post_clair_phase_contig`
2) `post_clair_contig_haplotag`
3) `phase_all`

Do you see any of them running?

**Comment by ilivyatan** [comment]
Actually, I took a closer look and it's the 
cnv_spectre:callCNV (0 of 1) that just stays at 0% for over 16 hours so far.
I ran it again with only --snv and --sv and it finished after 1.5 hours.
Why isn't the CNV analysis advancing?

**Comment by RenzoTale88** [comment]
This is a distinct issue, please create a new ticket providing the information requested.
