### ISSUE TITLE
dbNSFP for snps annotation

### ISSUE THREAD

**Issue by blanleung** [epi2me-labs/wf-human-variation#162]
### Ask away!

Hi,
As I understand we can annotate SNPs with ClinVar. Would it be possible to add dbNSFP annotation too?
Thanks

**Comment by vlshesketh** [comment]
Hi again @blanleung - sorry it's taken a while to get back to you! As we have some integration with tertiary analysis partners planned for this workflow via the[ EPI2ME desktop application](https://labs.epi2me.io/downloads/), we have no plans at the moment to include any further annotation sources directly in wf-human-variation.
