### ISSUE TITLE
wrong STR thresholds in STR-report

### ISSUE THREAD

**Issue by tamara-nano** [epi2me-labs/wf-human-variation#163]
### Operating System

Ubuntu 22.04

### Workflow Version

v2.0.0-g52e3698

### Workflow Execution

Command line

### Workflow Execution - CLI Execution Profile

None

### What happened?

Hello!

When running the STR-workflow on epi2me I noticed that I've got some wrong thresholds for the pathogenity of some str-expansions in the report. There it seems that the threshold is set to the base count and not the repeat count. These are HG002-data.

F.ex. PABPN1: normal max: 10 repeats, pathogenity starts at 11 repeats. Here the threshold is set at base 11 and not repeat 11, you see in both alleles only 6 repeats (fig: hg002)
![PABPN1](https://github.com/epi2me-labs/wf-human-variation/assets/98809861/951843ee-9497-49df-8c1e-75288392bbbb)
Also one allele has a wrong repeat-count (?) In the mapping you see 6/6 repeats for both alleles. This happened with a few repeats. It also enforces a repeat count when one allele is missing.
![pabpn1-rep](https://github.com/epi2me-labs/wf-human-variation/assets/98809861/f722e2ae-5b34-4c02-922f-399d5d828657)
Mapping of PABPN1
![pabpn1-map](https://github.com/epi2me-labs/wf-human-variation/assets/98809861/884ae03e-0f1a-4180-8446-69100b97d25d)

RFC1: normal repeat range 11-200 repeats, pathogenity 400 - >2000 repeats (source GeneReviews), also wrong threshold (fig: hg002 with 12/115 repeats for both alleles, ref-hg38 has 11 rep ) 
![rfc1](https://github.com/epi2me-labs/wf-human-variation/assets/98809861/01ca4ea6-e4fe-44b0-9056-58caf1ecc5fa)

Please could you have a look into this and check the thresholds? 

Else I find this pipeline pretty convenient with a nice report-output! Great work!

Best,
Tamara

### Relevant log output

```shell
-
```

### Were you able to successfully run the latest version of the workflow with the demo data?

yes

**Comment by vlshesketh** [comment]
Hi @tamara-nano, thank you for your positive feedback on the workflow! I will review the STR reporting script and get back to you shortly.

**Comment by vlshesketh** [comment]
Hi @tamara-nano, this has now been fixed in [v2.2.0](https://github.com/epi2me-labs/wf-human-variation/releases/tag/v2.2.0).
