### ISSUE TITLE
cnv_spectre: callCNV gets stuck

### ISSUE THREAD

**Issue by ilivyatan** [epi2me-labs/wf-human-variation#167]
### Operating System

Ubuntu 22.04

### Workflow Version

11

### Workflow Execution

Command line (Local)

### CLI command run

~/nextflow run epi2me-labs/wf-human-variation -profile standard --snp --sv --cnv --bam 20240303_1209_2B_PAO92639_a95fbad5/30169_dorado_aligned_sorted.bam --ref /data/referncess/GCA_000001405.15_GRCh38_no_alt_plus_hs38d1_analysis_set.fna --out_dir epi2me_out --basecaller_cfg 'dna_r10.4.1_e8.2_400bps_hac@v4.3.0' --sample_name '30169_dorado_aligned_sorted'

### Workflow Execution - CLI Execution Profile

standard (default)

### What happened?

The pipeline completed the snp and sv analyses, but just got stuck at the CNV analysis, which stayed at 0% (0 out of 1) for 24 hours till forced termination.

### Relevant log output

```shell
I can provide trace.txt and other reports
```

### Were you able to successfully run the latest version of the workflow with the demo data?

yes

**Comment by TBradley27** [comment]
Hey,

Have you tried allocating more memory like described here (#65)?

**Comment by TBradley27** [comment]
Hey,

This is just informal advice from another user, but try playing around with memory and/or threads allocation (as explained in #65)

I had a process in another ONT workflow take >18 hours. I terminated the job, allocated a lot more memory and threads and this particular process completed <2 hours next time I ran it

**Comment by ilivyatan** [comment]
Thanks for the advice, in this case it seems that the process doesn't even start.

**Comment by vlshesketh** [comment]
Hi @ilivyatan, please can you provide the .nextflow.log so we investigate this further?

**Comment by vlshesketh** [comment]
Hi @ilivyatan please can you let us know if this is still causing an issue, and send the .nextflow.log if so?

**Comment by vlshesketh** [comment]
HI @ilivyatan, closing this through lack of response but please re-open if you require further support.
