### ISSUE TITLE
Can CNV calling via Spectre run without --snv?

### ISSUE THREAD

**Issue by SkabbiVML** [epi2me-labs/wf-human-variation#171]
Hi

I recently updated the wf-human-variation workflow. The default CNV caller has been changed to Spectre so I thought I'd give it a go. I use the pipeline to call CNVs, SVs and aggregate methylation. However, once initiated, the pipeline spawned multiple snp-calling jobs that ate up all the RAM and swap partitions on my machine. The spectre documentation states: 

"To calculate CNVs Spectre uses primarily the coverage (Read depth) data. However, it can also use SNV data to detect loss of heterozygosity (LoH) regions. Additionally, Spectre can use the breakpoint (SNF) data from Sniffles to improve the CNV calling." 

It seems that wf-human-variation needs the snp data for the whole genome to perform CNV calling via Spectre. This is very time consuming and computationally heavy. There is a parameter in Spectre, `--snv`, to add a snv .vcf file. Is there a way I can remove this?

Cheers

S

**Comment by SkabbiVML** [comment]
@vlshesketh Question closed without comment, did I do something wrong?

S

**Comment by vlshesketh** [comment]
Hi @SkabbiVML, apologies, I accidentally closed the ticket without commenting! The ONT implementation of Spectre requires a SNP VCF and as such this parameter can't be switched off. Please refer to the [minimum requirements](https://github.com/epi2me-labs/wf-human-variation?tab=readme-ov-file#compute-requirements) which outline the very least you will need in terms of compute and memory to run the workflow.

**Comment by SkabbiVML** [comment]
Hi @vlshesketh 

No worries. I guess I'll stick to qDNAseq for now. 

cheers

S
