### ISSUE TITLE
 The genome build detected in the BAM is not compatible with this workflow.

### ISSUE THREAD

**Issue by selmapichot** [epi2me-labs/wf-human-variation#172]
### Ask away!

Hi, 
I am trying to run this workflow with the T2T reference genome, but I had this error message :  The genome build detected in the BAM is not compatible with this workflow.
Is the issue due to the T2T reference ? if so, is there a way to work around it ? Many thanks.
All the best,
Selma.

**Comment by vlshesketh** [comment]
Hi @selmapichot, this is because you are most likely attempting to run a sub-workflow that is not currently supported for the T2T genome. Please refer to the documentation for the options that are compatible with this genome (i.e. the `Other human` section): https://github.com/epi2me-labs/wf-human-variation#10-genome-compatibility-and-running-the-workflow-on-non-human-genomes

**Comment by selmapichot** [comment]
Hi, 
Many thanks for your reply. I'm calling snp (it seems that the correct flag is --snv instead of --snp as written in the documentation ...?).
If I understand correctly the documentation, it should be possible to call --snv with another human reference genome, which is what I am trying to do with the T2T, but I am still having this error message " The genome build detected in the BAM is not compatible with this workflow." 
Any advise on how to work around it will be greatly appreciated.
All the best,
Selma.

**Comment by selmapichot** [comment]
Hi, 
many thanks again for the reply. I got another arror message when using the --annotation false which is :
The exit status of the task that caused the workflow execution to fail was: 0.

The full error message was:

Error executing process > 'snv:wf_build_regions (1)'

Caused by:
  Missing output file(s) `snv_TB23_00177_T1/tmp/CONTIGS` expected by process `snv:wf_build_regions (1)`

**Comment by selmapichot** [comment]
Many thanks for your reply.
