### ISSUE TITLE
cannot detect snv with adaptive sampling

### ISSUE THREAD

**Issue by dhlee3342** [epi2me-labs/wf-human-variation#173]
### Ask away!

Hi,

I used wf-human-variation to detect snp in my genes of interest with adaptive sampling. Most mutations were normally detected, but some mutations were not detected, in one bed region. When I checked the bam file with IGV, there's a low coverage groove in the region that mutations were not detected. Roughly, the reads number is lower than 20. 
Question is, If there is a low depth region in one bed area, does the caller skip only that part?

Thank you.

**Comment by dhlee3342** [comment]
Hi,

I found all the variants with `--bam_min_coverage 10` option. 
I think I knew the mechanism. 

Thank you.

**Comment by vlshesketh** [comment]
Hi @dhlee3342, thanks for your interest in the workflow. As you have identified the parameter required, I'll close this issue, but please don't hesitate to get in touch again in the future if you have any other questions.
