### ISSUE TITLE
Explicit support for SLURM and other  schedulers

### ISSUE THREAD

**Issue by adbeggs** [epi2me-labs/wf-human-variation#176]
### Is your feature related to a problem?

Although you can submit to a slurm cluster, the subjobs are not submitted using SLURM meaning that it is less efficient

### Describe the solution you'd like

Explicit support of job schedulers in tasks, along the line of NF-Core

### Describe alternatives you've considered

Doing it myself, but I don't have the time!

**Comment by cjw85** [comment]
Slurm is supported through Nextflow's integrations with slurm. The precise config file used is intimately reliant on the end-user's HPC systems. Its not something we can support to include configuration files for all our users (and neither do we condone the idea of people submitting private cluster config profiles to a public respository).

**Comment by adbeggs** [comment]
Hi Chris

That’s kind of what Nextflow already support here:

https://github.com/nf-core/configs

Looking at your Nextflow config, I would have to rewrite your pipeline to explicitly support Slurm as it is not mentioned in the Nextflow.config and so doesn’t support it out of the box (unlike nf-core)

Happy to do this myself

A

**Comment by cjw85** [comment]
We're very aware of https://github.com/nf-core/configs, this is what we find it hard to condone. Many IT professionals would consider information in that repository a security risl for their infrastructure.

You don't need to rewrite the pipeline. You need only to provide an additional config file containing the configuration required.
