### ISSUE TITLE
Unknown Clair 3 model, (khz prefix)

### ISSUE THREAD

**Issue by Brynjar-H** [epi2me-labs/wf-human-variation#185]
### Ask away!

Hello, i am trying to run the human variation pipeline on my data basecalled with: dna_r10.4.1_e8.2_5khz_400bps_sup@v4.2.0. It seems Clair3 does not recognize this model, is the only option to re-basecall the data with a version supported by Clair3? This very similar model: dna_r10.4.1_e8.2_400bps_sup@v4.2.0 is supported and by looking at the release notes i can see that at some timepoint the 5khz prefix was dropped seemingly leading to my incompatabillity. Is it generally ok to manually change the file to drop the 5khz prefix hopefully allowing Clair3 to run? Also if anyone has a suggestion on what would be the best way to do that feel free :) For reference.... ERROR ~ Error executing process > 'lookup_clair3_model (1)'

Caused by:
  Process `lookup_clair3_model (1)` terminated with an error exit status (65)

Command executed:

  clair3_model=$(resolve_clair3_model.py lookup_table 'dna_r10.4.1_e8.2_5khz_400bps_sup@v4.2.0')
  cp -r ${CLAIR_MODELS_PATH}/${clair3_model} model
  echo "Basecall model: dna_r10.4.1_e8.2_5khz_400bps_sup@v4.2.0"
  echo "Clair3 model  : ${clair3_model}"

Command exit status:
  65

Command output:
  (empty)

Command error:
  --------------------------------------------------------------------------------
  [CRITICAL ERROR] Unknown basecaller configuration.

  The input basecaller configuration 'dna_r10.4.1_e8.2_5khz_400bps_sup@v4.2.0'
  does not have a suitable Clair3 model because the basecaller configuration has
  not been recognised.

  Check your --basecaller_cfg has been provided correctly.

**Comment by RenzoTale88** [comment]
Hi @Brynjar-H yes, that is indeed the 5KHz model, as shown in the table [here](https://github.com/nanoporetech/dorado#DNA-models). Simply providing the model you mentioned will work.

Andrea

**Comment by Brynjar-H** [comment]
Thank you for the quick response @RenzoTale88 this is the code i ran
nextflow run epi2me-labs/wf-human-variation \
    --bam '/proj/hpcdata/Mimir/shared/brynjar/nanopore/dna_met/10_d492M2/merged.bam' \
    --basecaller_cfg 'dna_r10.4.1_e8.2_400bps_sup@v4.2.0' \
    --mod True \
    --ref '/hpcdata/Mimir/snaevar/Homo_sapiens.GRCh38.dna.primary_assembly.fa' \
    --sample_name '10_d492M-2' \
    --snp True \
    --sv True \
    --phased True \
    --sex XY \
    -profile singularity \
    --outdir '/proj/hpcdata/Mimir/shared/brynjar/nanopore/human_var/gogn/10_d492M-2'
however Clair3 searches the bamfile for the basecaller that was used (which has the 5khz prefix)? so whatever i specify in the --basecaller_cfg doesnt do anything? is there a simple way to disable the search so it just takes the model i specify with --basecaller_cfg?
