### ISSUE TITLE
Problem while multithreading with slurm

### ISSUE THREAD

**Issue by remyvander** [epi2me-labs/wf-human-variation#187]
### Ask away!

Hi ! 
When I run the demo command on a machine, the workflow runs smoothly without a hitch.
I'd like to try running this command on a slurm cluster to try and save some computation time.
But the workflow gets an error on the job: makeAlignmentReport
Here's the error command: 

![Capture d’écran 2024-06-03 à 09 07 48](https://github.com/epi2me-labs/wf-human-variation/assets/22117181/e52fca53-7737-4e0e-9c62-2c548af21793)

So my question is: which process provides the files that MakeAlignement Report needs?
and do you have any ideas on how to temporize this job or another solution?

Thank you very much for your help

Rémy

**Comment by RenzoTale88** [comment]
Hi @remyvander Thank you for notifying this, we'll work on  a patch.
In the meanwhile, the reporting processes can be skipped by setting `--output_report false`.
I'll leave this open until a fix is available.

Andrea

**Comment by RenzoTale88** [comment]
@remyvander can you try with the latest version of the workflow (v2.3.0) and let us know if it works?
Please, note that it is better to drop the old version of the workflow before retrying:
```
nextflow drop epi2me-labs/wf-human-variation
nextflow run epi2me-labs/wf-human-variation -r v2.3.0 ...
```

**Comment by RenzoTale88** [comment]
@remyvander I'll close this issue due to inactivity. Feel free to reopen in case you need further assistance with the workflow.

Andrea
