### ISSUE TITLE
Can you use a GPU to run this workflow, either through commandline or epi2me?

### ISSUE THREAD

**Issue by lucy924** [epi2me-labs/wf-human-variation#196]
### Ask away!

Hi,
In the documentation you give the recommended and minimum CPU requirements, but I was wondering if it's possible to get this to run with an available GPU? I have the minimum CPU requirements but not the recommended - and the computer is set up with the optimal GPU for dorado basecalling. If I can run it with the GPU could you point me in the right direction for getting it set up please? Ideally I'd like to use the epi2me GUI but I can also use commandline.
Thank you!

**Comment by cjw85** [comment]
The workflow does not use GPU compute.
