### ISSUE TITLE
[Bug]: Cannot create work-dir: /workspace -- Make sure you have write permissions or specify a different directory by using the `-w` command line option

### ISSUE THREAD

**Issue by felixm3** [epi2me-labs/wf-human-variation#2]
### What happened?

Trying to run your demo workflow here in a conda environment on an HPC: 

https://github.com/epi2me-labs/wf-human-variation#quickstart 

When I run this:

```
# The workflow can be run with the demonstration data using:

!OUTPUT=output
!nextflow run epi2me-labs/wf-human-variation \
    -w ${OUTPUT}/workspace \
    -c my_config.cfg \
    -profile fixed_conda \
    --snp --sv \
    --bam demo_data/demo.bam \
    --bed demo_data/demo.bed \
    --ref demo_data/demo.fasta \
    --model demo_data/ont_r104_e81_sup_g5015 \
    --out_dir ${OUTPUT}

```

I get this error message:

```
N E X T F L O W  ~  version 22.04.5
Launching `[https://github.com/epi2me-labs/wf-human-variation`](https://github.com/epi2me-labs/wf-human-variation%60) [magical_swanson] DSL2 - revision: 4497a3b1ad [master]
Cannot create work-dir: /workspace -- Make sure you have write permissions or specify a different directory by using the `-w` command line option
```

### Operating System

macOS

### Workflow Execution

Other (please describe)

### Workflow Execution - EPI2ME Labs Versions

Running on an HPC in a conda environment from a Jupyter notebook

### Workflow Execution - Execution Profile

Conda

### Workflow Version

Unsure. How do I check this?

### Relevant log output

```shell
N E X T F L O W  ~  version 22.04.5
Launching `https://github.com/epi2me-labs/wf-human-variation` [tender_swirles] DSL2 - revision: 4497a3b1ad [master]
Cannot create work-dir: /workspace -- Make sure you have write permissions or specify a different directory by using the `-w` command line option
```

**Comment by SamStudio8** [comment]
Hi @felixm3, the example is assuming your environment is a shell that will set an `OUTPUT` variable in your environment so it can be used to set `-w` and `--out_dir` in the Nextflow command. That does not seem to be the case for you here. In the first instance you can just replace the `${OUTPUT}` variable with `output` (or any directory you wish):

```
nextflow run epi2me-labs/wf-human-variation \
    -w output/workspace \
    -c my_config.cfg \
    -profile fixed_conda \
    --snp --sv \
    --bam demo_data/demo.bam \
    --bed demo_data/demo.bed \
    --ref demo_data/demo.fasta \
    --model demo_data/ont_r104_e81_sup_g5015 \
    --out_dir output
```

**Comment by felixm3** [comment]
Thanks! This part appears to work.

But now I have a new error message. 😅

I'll start a new thread.
