### ISSUE TITLE
ERROR: SnpEff annotation

### ISSUE THREAD

**Issue by reshu23** [epi2me-labs/wf-human-variation#200]
### Ask away!

Dear Team, I have run pipeline on my datasets. I can see, there is an error of "Chromosome not found" generated by SnpEff. These error is reported on configs. Here is the screen shot. Meaning of this error is "these contigs are not available in SnpEff database". Should I expect this error for contigs as a part of annotation?Thank you. 
<img width="926" alt="image" src="https://github.com/user-attachments/assets/80ce3a17-8072-4aba-8e5c-dee4ee41b15a">
<img width="937" alt="Screenshot (21)" src="https://github.com/user-attachments/assets/d4c5c56d-5541-4449-a2dc-76c21da5a44f">
<img width="923" alt="Screenshot (25)" src="https://github.com/user-attachments/assets/dc934453-1f0a-4666-b45d-8cdaa17950f1">

**Comment by vlshesketh** [comment]
Hi @reshu23, this error means that the contigs in the input reference don't match those in the annotation database used by SnpEff. For your information, the workflow bundles the following SnpEff databases: `GRCh38.p13` and `GRCh37.p13`. If you aren't using a compatible reference genome then you will see the error above, and so we'd recommend using one of the genomes linked in the [README](https://github.com/epi2me-labs/wf-human-variation#1-input-and-data-preparation).

**Comment by reshu23** [comment]
Thank you. I am using recommended reference sequence. That is the reason, I was confused after getting "Chromosome not found error". Here it is: 
<img width="836" alt="Screenshot (42)" src="https://github.com/user-attachments/assets/1d097da7-bed0-407a-a6ff-766faccae351">

**Comment by reshu23** [comment]
I can see, contigs are present in my reference sequence.
<img width="896" alt="Screenshot (44)" src="https://github.com/user-attachments/assets/22578c2d-1722-4dc6-959e-e9d0f75a833b">

**Comment by reshu23** [comment]
Thank you. That makes sense.

**Comment by vlshesketh** [comment]
Thanks for your interest in the workflow!
