### ISSUE TITLE
 Process `getGenome (1)` terminated with an error exit status (65)

### ISSUE THREAD

**Issue by rajeshvalmiki** [epi2me-labs/wf-human-variation#202]
### Ask away!

The exit status of the task that caused the workflow execution to fail was: 65.

The full error message was:

Error executing process > 'getGenome (1)'

Caused by:
  Process `getGenome (1)` terminated with an error exit status (65)

Command executed:

  # use view -H rather than idxstats, as idxstats will still cause a scan of the whole CRAM (https://github.com/samtools/samtools/issues/303)
  samtools view -H SAMPLE.cram --no-PG | grep '^@SQ' | sed -nE 's,.*SN:([^[:space:]]*).*LN:([^[:space:]]*).*,\1\t\2,p' > SAMPLE.cram_genome.txt
  get_genome.py --chr_counts SAMPLE.cram_genome.txt -o output.txt --str --cnv 
  genome_build=`cat output.txt`

Command exit status:
  65

Command output:
  (empty)

Command error:
  The genome build detected in the BAM is not compatible with this workflow.
  Detected genome: hg19, but genotyping STRs and calling CNVs with Spectre can only be performed when aligned to build 38.

Work dir:
  /mnt/c/Users/CMC/epi2melabs/instances/wf-human-variation_01J43F0Z7KPWP6RZSXSAQFRFSP/work/8a/1299c71bf2be029c2e866e66ef2b48

Tip: you can replicate the issue by changing to the process work dir and entering the command `bash .command.run`

**Comment by rajeshvalmiki** [comment]
For the human variation workflow, I used hg19 reference.........

**Comment by RenzoTale88** [comment]
Hi @rajeshvalmiki, as reported in the error, the workflow can run `--str` and `--cnv` only with hg38, as detailed  [here](https://github.com/epi2me-labs/wf-human-variation?tab=readme-ov-file#6a-copy-number-variants-cnv-calling-with-spectre) and  [here](https://github.com/epi2me-labs/wf-human-variation?tab=readme-ov-file#7-short-tandem-repeat-str-genotyping-with-straglr).:
```
 Detected genome: hg19, but genotyping STRs and calling CNVs with Spectre can only be performed when aligned to build 38.
```

If you want to use hg19, you can run the workflow with `--snp`, `--sv` and `--mod`.
You can find further details in the documentation [here](https://github.com/epi2me-labs/wf-human-variation?tab=readme-ov-file#pipeline-overview).

Andrea
