### ISSUE TITLE
ERROR ~ * --sample_name: expected type: String, found: Integer (*******)

### ISSUE THREAD

**Issue by ParkShinHyun** [epi2me-labs/wf-human-variation#203]
### Operating System

Windows 10

### Other Linux

CentOS Linux 7

### Workflow Version

v.2.1.0

### Workflow Execution

Command line (Local)

### EPI2ME Version

v.2.1.0

### CLI command run

nextflow-23.10.0-all run epi2me-labs/wf-human-variation -r v2.1.0 -w wf-human-variation/workspace -profile singularity --snp --sv --cnv --mod --str --modkit_args '--cpg --ignore h --combine-strands' --bam (*******)_splitedBAM --ref Reference/hg19/Sequence/genome.fa --basecaller_cfg 'dna_r10.4.1_e8.2_400bps_hac@v4.2.0'     --sample_name (*******) --bam_min_coverage 0 --out_dir wf-human-variation --include_all_ctgs true --annotation false --GVCF --ubam_map_threads 40 --merge_threads 40

### Workflow Execution - CLI Execution Profile

singularity

### What happened?

I encountered an error while using the wf-human-variation program. The error message is as follows:

ERROR ~ * --sample_name: expected type: String, found: Integer

In my use case, the sample_name is an Integer, which causes this error. I am currently using version 2.1.0 of the workflow and cannot upgrade to a newer version.

Is there any way to resolve this error given the constraints? Any suggestions or workarounds to allow sample_name to accept Integer values would be greatly appreciated.

Thank you!

### Relevant log output

```shell
N E X T F L O W  ~  version 23.10.0
Launching `https://github.com/epi2me-labs/wf-human-variation` [awesome_dijkstra] DSL2 - revision: b82338d3d6 [v2.1.0]

ERROR ~ Validation of pipeline parameters failed!

 -- Check '.nextflow.log' file for details
ERROR ~ * --sample_name: expected type: String, found: Integer (*******)

 -- Check '.nextflow.log' file for details


** .nextflow.log

Aug-01 09:41:59.850 [main] DEBUG nextflow.script.ScriptRunner - > Launching execution
Aug-01 09:42:04.869 [main] ERROR nextflow.Nextflow - Validation of pipeline parameters failed!
Aug-01 09:42:04.875 [main] ERROR nextflow.Nextflow - * --sample_name: expected type: String, found: Integer (*******)


(*******) is some integer
```

### Were you able to successfully run the latest version of the workflow with the demo data?

yes

**Comment by RenzoTale88** [comment]
Hi @ParkShinHyun this has been notified to us in the past #14. It is a known issue in nextflow, as documented [here](https://github.com/nextflow-io/nextflow/issues/2083).
Closing as we currently have no workaround for this, and we are awaiting for upstream to implement an alternative input parser.
