### ISSUE TITLE
qdnaseq_bin_size measurement units not consistent

### ISSUE THREAD

**Issue by HudoGriz** [epi2me-labs/wf-human-variation#209]
### Operating System

CentOS 7

### Workflow Version

v2.3.1

### Workflow Execution

Command line (Cluster)

### Workflow Execution - CLI Execution Profile

singularity

### What happened?

There seems to be a discrepancy between:
 - `--qdnaseq_bin_size` where the number refers to kbp ([code line](https://github.com/epi2me-labs/wf-human-variation/blob/6a6daa65aa19257e1709753a31686515913ebf34/nextflow_schema.json#L459))
 -  `--binsize` for QDNAseq, where the referred number is MBp ([code line](https://github.com/epi2me-labs/wf-human-variation/blob/6a6daa65aa19257e1709753a31686515913ebf34/bin/run_qdnaseq.r#L23))

Kind regards,

Blaž

### Relevant log output

```shell
No log needed, pipeline works
```

### Were you able to successfully run the latest version of the workflow with the demo data?

yes

**Comment by vlshesketh** [comment]
Hi @HudoGriz thanks for notifying us of this - the units for bin size are in kbp. The `run_qdnaseq.r` script contains the incorrect unit in the parameter help text, so I'll make a ticket to get that updated to avoid confusion.
