### ISSUE TITLE
About STR analysis

### ISSUE THREAD

**Issue by EugeneKim76** [epi2me-labs/wf-human-variation#210]
### Ask away!

Dear all
I extracted recently str results using GRCh38 reference.
My understanding is that wf_str_repeats.bed is input bed file of straglr genotype stage.

My Questions
1. Does wf_str_repeats.bed contain enough str targets? Do we have to add targets by using genome scan stage of straglr or etc.? 

2. Is there any problem using our own bed file instead of wf_str_repeats.bed?

Best,

**Comment by vlshesketh** [comment]
Hi @EugeneKim76, thank you for your interest in the workflow. The `wf_str_repeats.bed` lists the STR loci that are inspected, and the results for each STR will be annotated using the metadata in `variant_catalog_hg38.json`. These are static files in the workflow, so if you wish to look at additional targets, then you are welcome to modify the contents in your own local copy of the workflow. Please be aware however that we can only support troubleshooting in relation to the original contents of these files, as they have been curated internally.

**Comment by vlshesketh** [comment]
I'll close this issue now but please feel free to open a new issue if you have any further questions about the workflow.
