### ISSUE TITLE
sniffles2 mosaic option?

### ISSUE THREAD

**Issue by kylematoba** [epi2me-labs/wf-human-variation#215]
### Is your feature related to a problem?

I want to be able to call sniffles2 like this: 
https://github.com/fritzsedlazeck/Sniffles?tab=readme-ov-file#c-mosaic-sv-calling-non-germline-or-somatic-svs

### Describe the solution you'd like

Generalize nextflow script

### Describe alternatives you've considered

not using wf human variation
(can I suggest not making this field mandatory? it's quite patronizing)

**Comment by RenzoTale88** [comment]
Hi @kylematoba we use v2.0.7 of sniffles, which doesn't have the `--mosaic` option. If you want to access that feature, you can try using `--sniffles_args='--non-germline'`, as described in #120.

**Comment by kylematoba** [comment]
Okay, and how do I phrase this to the "epi2me-labs" graphical application please? It apparently offers an "Advanced Options" section where this is not an option, and specifying it as "Additional nextflow configuration" throws a groovy parsing error.

**Comment by RenzoTale88** [comment]
You are right, the option is hidden within the app. I've opened a ticket internally to address this.

**Comment by RenzoTale88** [comment]
@kylematoba we just released v2.4.0, that expose this option in the app in the Advanced Options section.
