### ISSUE TITLE
running workflow with just --str command still runs clair3 SNP 

### ISSUE THREAD

**Issue by fidibidi** [epi2me-labs/wf-human-variation#217]
### Ask away!

Just curious, but is this because the SNP data is require for --str? Is there a way to bypass this step if you already have that data? 

```
		nextflow run epi2me-labs/wf-human-variation
		-w "${OUTPUT}/${SAMPLE}-workspace"
		-c optimize.cfg
		-profile standard
		--str
		--override_basecaller_cfg "dna_r10.4.1_e8.2_400bps_hac@v5.0.0"
		--bam "${BAM_FILE}"
		--ref "${REF}"
		--sample_name "${SAMPLE}"
		--bam_min_coverage 0
		--out_dir "${OUTPUT}"
```

**Comment by vlshesketh** [comment]
Hi @fidibidi, for STRs to be genotyped, a haplotagged BAM is required, which is generated as part of the `--snp` workflow (haplotagging is carried out suing whatshap), and therefore this must be run first and cannot be bypassed.
