### ISSUE TITLE
By-pass the depth requirements for sv wf

### ISSUE THREAD

**Issue by RxLoutre** [epi2me-labs/wf-human-variation#218]
### Ask away!

Hello !

I am trying my hands on this workflow for the first time.

I would like to get calls from an adaptive sampling run.

I started it the following way : 

`nextflow run epi2me-labs/wf-human-variation -config nextflow.config -profile singularity --sv --bam sushi/bam/my_cool.bam --ref References/human/UCSC/GRCh37/Sequence/hg19.fa --bed BED_Nanopore_AS/GRCh37_CTD_CM_SCD_panel.bed`

But sadly, it seems the coverage on the target area is a bit low and the workflow will not proceed : 

```
ERROR ~ File SAMPLE.cram will not be processed by the workflow because:
 - Depth: 11.637 < 20
```
 
 Is there no way to manually lower that requiremens to allow the workflow to run anyway ?
 
 Best,
 
 Roxane

**Comment by cjw85** [comment]
We cannot guarantee the workflow will function correctly or at all with lower coverage than the default of the `--bam_min_coverage` parameter.

Please see the [Options](https://github.com/epi2me-labs/wf-human-variation?tab=readme-ov-file#main-options) section of the README.

**Comment by RxLoutre** [comment]
Hello and thank you for your fast answer, I am sorry that I did not see the option earlier that was doing exactly what I was asking for. My bad.
Thank you and have a good day !
Best,
Roxane
