### ISSUE TITLE
Please document tools and tool versions corresponding to a particular release

### ISSUE THREAD

**Issue by oneillkza** [epi2me-labs/wf-human-variation#219]
### Is your feature related to a problem?

I'm in the process of helping write a methods section for a manuscript, for which wf-human-variation was used for part of the analysis. While we did document the workflow version we used (which is great for reproducibilty), I'm realizing that it's actually very difficult to find the exact tool versions that were run in this version of the workflow. They don't seem to be anywhere in the code, the readme, or even clearly discernible from the layers in the Docker container. (And the source code for the Docker containers doesn't seem to be available.) 

So I'm left with having to pull down all of the various containers used, and run the tools to get their versions.

### Describe the solution you'd like

Something similar to the nf-core convention of gathering tool versions at runtime and emitting them in a standard format (YAML, JSON, etc) as part of the workflow output.

### Describe alternatives you've considered

Including tool versions in the readme or other documentation would be great!

**Comment by SamStudio8** [comment]
Hi @oneillkza - each of the individual subworkflows for wf-human-variation do enumerate the versions used in the HTML reports that they generate but I'll raise a ticket with your suggestion as we're always looking for ways to improve our reporting!

**Comment by oneillkza** [comment]
Thanks @SamStudio8 ! Yep, I'd missed that.

But yes if you're up to it, something similar to the nf-core approach (ie producing a single text file with all the versions in one place) would be super helpful too.
