### ISSUE TITLE
Modify optional parameter --min-cnv-len in Spectre

### ISSUE THREAD

**Issue by fidibidi** [epi2me-labs/wf-human-variation#220]
### Ask away!

Is there a way to modify the input parameters for the cnv caller Spectre? 

in particular the setting, --min-cnv-len, which defaults to 80kb, I think.

form https://github.com/epi2me-labs/wf-human-variation/blob/64fe2fb11589c127eb07a9d011608a6dacb9a406/modules/local/wf-human-cnv.nf

"""
       spectre CNVCaller \
        --bin-size 1000 \
        --threshhold-quantile 10 \
        --dist-proportion 0.3 \
        --coverage readstats/ \
        --sample-id ${xam_meta.alias} \
        --output-dir spectre_output/ \
        --reference ${ref} \
        --blacklist grch38_blacklist_0.3 \
        --min-cnv-len 80000 \
        --snv ${vcf} \
        --metadata grch38_metadata
"""

**Comment by vlshesketh** [comment]
Hi @fidibidi, none of the Spectre default values, including `--min-cnv-len` can be modified as they haven't been exposed as parameters. Please see [here](https://github.com/epi2me-labs/wf-human-variation/issues/189#issuecomment-2163056626) for more information on parameter values. I have referred your question to the Applications team in case there is any further information they can provide on future plans to make parameters configurable by users.

**Comment by fidibidi** [comment]
Thank you!
