### ISSUE TITLE
IGV View

### ISSUE THREAD

**Issue by Szuchieh17** [epi2me-labs/wf-human-variation#229]
### Ask away!

Hi

I would like to inquire about the question regarding IGV view for wf-human-variation workflow. I found that I cannot view any profile for IGV view due to too huge data size. Hence, I used IGV software to load the VCF file generated by this workflow, and I can view the data. However, I would like to inquire whether the possibility of viewing VCF file and BAM file at the same time in order to view SNP location and alignment profile because I would like to know whether different sequencing sessions have any different SNP calling, and whether more reads can perform more depth of coverage. Additionally, I can view the IGV results directly from wf-alignment workflow, but when I try to use IGV software to load the BAM file generated by wf-alignment workflow, it did not show anything. I would like to how to adjust the parameters, and in such a situation, who I can ask for the support. I greatly appreciate your help.

**Comment by SamStudio8** [comment]
Hi @Szuchieh17, this repository is for opening issues with wf-human-variation, we cannot offer assistance with using the IGV software.
