### ISSUE TITLE
Use process selectors to request fewer cores for basecalling

### ISSUE THREAD

**Issue by aw1231** [epi2me-labs/wf-human-variation#23]
### What happened?

We are trying to using the human-variation workflow. When running it, we get the following error: Process requirement exceed available CPUs -- req: 8; avail: 6. This seems to stem from https://github.com/epi2me-labs/wf-human-variation/blob/master/workflows/_basecalling.nf#L12 but I can't see where to change it.

### Operating System

macOS

### Workflow Execution

EPI2ME Labs desktop application

### Workflow Execution - EPI2ME Labs Versions

4.1.3

### Workflow Execution - CLI Execution Profile

None

### Workflow Version

1.3.0

### Relevant log output

```shell
Mar-10 10:32:52.899 [Task submitter] ERROR nextflow.processor.TaskProcessor - Error executing process > 'basecalling:wf_dorado:dorado (2)'

 

Caused by:

  Process requirement exceed available CPUs -- req: 8; avail: 6

 

Command executed:

 

  echo '***'

  echo 'Available models:'

  list-models | sed 's,^,- ,' | sed "s,${DRD_MODELS_PATH}/,,"

  echo '***'

  echo 'You selected:'

  echo "Basecalling model: dna_r10.4.1_e8.2_400bps_sup@v4.0.0"

  echo "Remora model     : null"

  echo '***'

  echo 'A file open error below indicates that you have entered an unknown model name.'

  echo 'It is possible the model you selected worked previously but has been updated to a new version.'

  echo 'Resubmit this workflow with an appropriate model from the model list above.'

  echo '***'

 

  dorado basecaller         ${DRD_MODELS_PATH}/dna_r10.4.1_e8.2_400bps_sup@v4.0.0 .                           --device cuda:auto | samtools view -b -o 1.ubam -

 

Command exit status:

  -

 

Command output:

  (empty)

 

Work dir:

  /Users/hayley/epi2melabs/instances/wf-human-variation_41249971-8238-489c-bcd6-be9282fccd1e/work/19/e6463ebfc6babfc396fdfa2c42822e

 

Tip: you can try to figure out what's wrong by changing to the process work dir and showing the script file named `.command.sh`

Mar-10 10:32:52.903 [Task submitter] DEBUG nextflow.Session - Session aborted -- Cause: Process requirement exceed available CPUs -- req: 8; avail: 6
```

**Comment by SamStudio8** [comment]
Hi @aw1231, you can use [process selectors](https://www.nextflow.io/docs/latest/config.html#process-selectors) to apply configuration to particular parts of our workflow. When launching a workflow in Labs, you can specify additional Nextflow config options in the "Extra configuration" options section. To reduce the number of requested CPUs in this case you can use the following config:

```
process {
    withLabel:gpu {
        cpus = 6
    }
}
``` 

<img width="645" alt="Screenshot 2023-03-13 at 14 47 00" src="https://user-images.githubusercontent.com/1105722/224736983-e559435f-3821-427a-a6ee-c591accb934d.png">

I note from your report that you are running wf-human-variation on a Mac. Please be aware if you are using an ARM-based Mac you may notice that some processes have poor performance as the Rosetta compatibility for some CPU intensive tasks appears to not work efficiently.

**Comment by aw1231** [comment]
This worked! Thanks!
