### ISSUE TITLE
[Bug]: --GVCF does not create a gvcf in the output folder 

### ISSUE THREAD

**Issue by neurogenetics1** [epi2me-labs/wf-human-variation#28]
### What happened?

--GVCF does not create a gvcf in the output folder with the latest release. --GVCF option used to work with the previous release.

### Operating System

ubuntu 20.04

### Workflow Execution

Command line

### Workflow Execution - EPI2ME Labs Versions

wf-human-variation v1.3.0-gbc26fa0

### Workflow Execution - CLI Execution Profile

None

### Workflow Version

wf-human-variation v1.3.0-gbc26fa0

### Relevant log output

```shell
.
```

**Comment by SamStudio8** [comment]
@neurogenetics1 Are you still observing this?
