### ISSUE TITLE
[Bug]: only sex chromosomes are included in CNV wf

### ISSUE THREAD

**Issue by neurogenetics1** [epi2me-labs/wf-human-variation#29]
### What happened?

I use --cnv option for five samples. I obtain only sex chromosomal variants in the vcf files. Do i miss any parameter that should be included?

### Operating System

ubuntu 20.04

### Workflow Execution

Command line

### Workflow Execution - EPI2ME Labs Versions

wf-human-variation v1.3.0-gbc26fa0

### Workflow Execution - CLI Execution Profile

Singularity

### Workflow Version

wf-human-variation v1.3.0-gbc26fa0

### Relevant log output

```shell
.
```

**Comment by SamStudio8** [comment]
Hi @neurogenetics1, the VCF is only going to contain calls where a CNV is detected. If you know these samples are missing any calls please let us know.
