### ISSUE TITLE
[Bug]:  Error executing process > 'cram_cache (1)'

### ISSUE THREAD

**Issue by ChristopherRichie** [epi2me-labs/wf-human-variation#31]
### What happened?

A bug happened!

I am running this wf for the first time, so I do not have a positive control for my command line syntax, nor a "history" to suggest that this is a transient error.

I am new to nextflow, but I have demonstrated that my nextflow.config and profile settings work with the wf-basecalling.

Can anyone suggest what would cause a "failure to pull singularity image" or how to overcome this failure in the wf-human-variation?

thanks
chris

text dump from the Nextflow workflow report:
Error executing process > 'cram_cache (1)'

Caused by:
  Failed to pull singularity image
  command: singularity pull  --name ontresearch-wf-human-variation-shaa6d218582d6056ea970b73e61f138ebb0ce6c5b1.img.pulling.1681395671895 docker://ontresearch/wf-human-variation:shaa6d218582d6056ea970b73e61f138ebb0ce6c5b1 > /dev/null
  status : 255
  message:
    FATAL:   While making image from oci registry: error fetching image to cache: failed to get checksum for docker://ontresearch/wf-human-variation:shaa6d218582d6056ea970b73e61f138ebb0ce6c5b1: pinging container registry registry-1.docker.io: Get "https://registry-1.docker.io/v2/": proxyconnect tcp: dial tcp 10.1.200.237:3128: i/o timeout

### Operating System

Windows 10

### Workflow Execution

Other (please describe)

### Workflow Execution - EPI2ME Labs Versions

NIH HPC Biowulf, running nextflow and singularity with --cpus-per-task=14 --mem=16g --gres=lscratch:400,gpu:v100:1

### Workflow Execution - CLI Execution Profile

Singularity

### Workflow Version

pi2me-labs/wf-human-variation v1.3.0-gbc26fa0.

### Relevant log output

```shell
Workflow execution completed unsuccessfully!
The exit status of the task that caused the workflow execution to fail was: null.

The full error message was:

Error executing process > 'cram_cache (1)'

Caused by:
  Failed to pull singularity image
  command: singularity pull  --name ontresearch-wf-human-variation-shaa6d218582d6056ea970b73e61f138ebb0ce6c5b1.img.pulling.1681394243653 docker://ontresearch/wf-human-variation:shaa6d218582d6056ea970b73e61f138ebb0ce6c5b1 > /dev/null
  status : 255
  message:
    FATAL:   While making image from oci registry: error fetching image to cache: failed to get checksum for docker://ontresearch/wf-human-variation:shaa6d218582d6056ea970b73e61f138ebb0ce6c5b1: Get "https://auth.docker.io/token?scope=repository%3Aontresearch%2Fwf-human-variation%3Apull&service=registry.docker.io": proxyconnect tcp: dial tcp 10.1.200.237:3128: i/o timeout

Run times
13-Apr-2023 09:57:11 - 13-Apr-2023 09:59:09 (duration: 1m 58s)
Nextflow command
nextflow run epi2me-labs/wf-human-variation -w output/workspace -profile biowulf --snp --sv --fast5_dir ./fast5_pass/barcode03 --basecaller_cfg dna_r10.4.1_e8.2_400bps_hac@v3.5.2 --remora_cfg dna_r10.4.1_e8.2_400bps_hac@v3.5.2_5mCG@v2 --bed . --ref ./CR3292_ref.fa --out_dir output
CPU-Hours
(a few seconds)
Launch directory
/gpfs/gsfs12/users/chrisr/CR3292/no_sample/20230411_1859_MC-110461_ami007_cc5b0e70
Work directory
/gpfs/gsfs12/users/chrisr/CR3292/no_sample/20230411_1859_MC-110461_ami007_cc5b0e70/output/workspace
Project directory
/home/chrisr/.nextflow/22.10.2/assets/epi2me-labs/wf-human-variation
Script name
main.nf
Script ID
728c48f1ceb9f112b20feb2aaa7de125
Workflow session
330452d2-3858-439b-b035-7907ee8b530b
Workflow repository
https://github.com/epi2me-labs/wf-human-variation, revision master (commit hash bc26fa025ae58ab1765f9e5f8804d88c41a55a6b)
Workflow profile
biowulf
Workflow container
ontresearch/wf-human-variation:shaa6d218582d6056ea970b73e61f138ebb0ce6c5b1
Container engine
singularity
Nextflow version
version 22.10.4, build 5836 (09-12-2022 09:58 UTC)
```

**Comment by SamStudio8** [comment]
@ChristopherRichie Exactly, it would seem the request to reach the Docker registry timed out. Glad to hear the error resolved itself.
