### ISSUE TITLE
Methyl request

### ISSUE THREAD

**Issue by carolinehey** [epi2me-labs/wf-human-variation#39]
### What happened?

Request:
It would be very convenient if you could run both --methyl and --phase_methyl at the same time to get both unphased and phased methylation information. 

### Operating System

Windows 10

### Workflow Execution

EPI2ME Labs desktop application

### Workflow Execution - CLI Execution Profile

None

### Workflow Version

v1.4.0

### Relevant log output

```shell
1
```

**Comment by RenzoTale88** [comment]
Hi @carolinehey at this time the workflow does not allow to call phased and unphased methylation. 

However, you can take advantage of nextflow checkpointing by running the workflow twice:
1) Run the workflow once with `--phase_methyl`, to generate phased methylation
2) After it completes, run the workflow withouth `--phase_methyl` and with `-resume`
The second time will cause the workflow ro perform the methylation calling only, will save the output in the same directory.

If you prefer to keep the outputs separated, you can provide two distinct output directories with `--out_dir`, as this will not impact the ability of the workflow to resume.
