### ISSUE TITLE
[Documentation/feature request]: data/clair3_models.tsv is out of date

### ISSUE THREAD

**Issue by mp15** [epi2me-labs/wf-human-variation#45]
### What happened?

data/clair3_models.tsv is out of date. There's a fair number of the previously missing Clair models esp 260bps models which are now available from rerio (https://github.com/nanoporetech/rerio/tree/master/clair3_models).

### Workflow Version

v1.5.2

**Comment by SamStudio8** [comment]
Hi @mp15, thanks for reporting. wf-human-variation 1.6.0 has just been released with an updated selection of Clair3 models. As you probably know, the Clair3 model is automatically selected from the basecaller_cfg. As of 1.6.0 this field is now validated and options that are used for Clair3 but not basecalling are all prefixed with `clair3:`, so you'll want to refer to `--help` (or the data/clair3_models file in the repo) to find the right one. Please let me know how you get on with them.
