### ISSUE TITLE
[Bug]:Using this workflow through a proxy server

### ISSUE THREAD

**Issue by MarioCazalla** [epi2me-labs/wf-human-variation#48]
### What happened?

Hi all,
I am wondering if it is possible to use this workflow through a proxy server. I am using Ubuntu version 22.04

Thanks in advance.

### Operating System

ubuntu 20.04

### Workflow Execution

EPI2ME Labs desktop application

### Workflow Execution - EPI2ME Labs Versions

latest

### Workflow Execution - CLI Execution Profile

None

### Workflow Version

latest

### Relevant log output

```shell
WARN: Cannot read project manifest -- Cause: Unable to tunnel through proxy. Proxy returns "HTTP/1.1 407 Proxy Authentication Required"
Cannot find `epi2me-labs/wf-human-variation` -- Make sure exists a GitHub repository at this address `https://github.com/epi2me-labs/wf-human-variation`
```

**Comment by cjw85** [comment]
We are actively investigating how to enable use of proxies, there are various parts of the software that would need to be routed through proxies so it's a bit more than a simple feature for us to implement.

**Comment by MarioCazalla** [comment]
Do you know if there is another variant caller to use with Minion Sequencing data?
Thank you.

**Comment by cjw85** [comment]
We are working on support for proxy servers in the next release of EPI2ME Desktop. I will close this issue as its not specific to the use of wf-human-variation, but more a generic concern of the desktop application.
