### ISSUE TITLE
[Bug]: Depreciated python code

### ISSUE THREAD

**Issue by bounlu** [epi2me-labs/wf-human-variation#49]
### What happened?

I keep getting the below error. Depreciated `data type` error in `numpy`. It needs to be fixed.

### Operating System

ubuntu 20.04

### Workflow Execution

Command line

### Workflow Execution - CLI Execution Profile

Docker

### Workflow Version

1.5.2

### Relevant log output

```shell
Command error:
  /home/epi2melabs/conda/lib/python3.8/site-packages/bokeh/core/property/primitive.py:37: DeprecationWarning: `np.bool8` is a deprecated alias for `np.bool_`.  (Deprecated NumPy 1.24)
    bokeh_bool_types += (np.bool8,)
  [10:05:27 - workflow_glue] Starting entrypoint.
  .command.sh: line 10:   732 Killed                  workflow-glue report_al --name wf-human-variation --stats_dir readstats/ --reference_fai ref.fasta.fai --flagstat_dir flagstats/ --depths_dir depths/ --versions versions.txt --window_size 25000 --params params.json
```

**Comment by bounlu** [comment]
Yes you are right and I already fixed the actual error. But it is just disturbing to see the warning along the error, which needs to be eventually fixed I think, hence I reported.

**Comment by SamStudio8** [comment]
Thanks @bounlu, the `DeprecationWarning` comes from inside one of our dependencies. We pin our dependencies to known working conditions and review them from time to time when updating our Docker images.
