### ISSUE TITLE
[Bug]: annotate snps complains about the vcf entry.

### ISSUE THREAD

**Issue by mattloose** [epi2me-labs/wf-human-variation#52]
### What happened?

A bug happened!

A nasty bug.

A bug that is very infuriating.

Annotation appears to be failing.

### Operating System

ubuntu 20.04

### Workflow Execution

Command line

### Workflow Execution - CLI Execution Profile

None

### Workflow Version

1.6.0

### Relevant log output

```shell
ERROR ~ Error executing process > 'snp:annotate_snp_vcf (1)'

Caused by:
  Process `snp:annotate_snp_vcf (1)` terminated with an error exit status (1)

Command executed:

  # deal with samples which aren't hg19 or hg38
  if [[ "hg38" != "hg38" ]] && [[ "hg38" != "hg19" ]]; then
      # return the original VCF and index as the outputs
      cp input.vcf.gz 27hrs.wf_snp.vcf.gz
      cp input.vcf.gz.tbi 27hrs.wf_snp.vcf.gz.tbi
      # create an empty snpEff_genes file
      touch 27hrs.wf_snp.snpEff_genes.txt
      # create an empty ClinVar VCF
      touch 27hrs.wf_snp_clinvar.vcf
  else
      # do some annotation
      if [[ "hg38" == "hg38" ]]; then
          snpeff_db="GRCh38.105"
          clinvar_vcf="${CLINVAR_PATH}/clinvar_GRCh38.vcf.gz"

      elif [[ "hg38" == "hg19" ]]; then
          snpeff_db="GRCh37.75"
          clinvar_vcf="${CLINVAR_PATH}/clinvar_GRCh37.vcf.gz"
      fi

      # Specify 4G of memory otherwise SnpEff will crash with the default 1G
      snpEff -Xmx4g ann $snpeff_db input.vcf.gz > 27hrs.snpeff_annotated.vcf
      # Add ClinVar annotations
      SnpSift annotate $clinvar_vcf 27hrs.snpeff_annotated.vcf > 27hrs.wf_snp.vcf
      # Get the ClinVar-annotated variants into a separate VCF
      cat 27hrs.wf_snp.vcf | SnpSift filter "( exists CLNSIG )" > 27hrs.wf_snp_clinvar.vcf

      bgzip -c 27hrs.wf_snp.vcf > 27hrs.wf_snp.vcf.gz
      tabix 27hrs.wf_snp.vcf.gz

      # tidy up
      rm 27hrs.snpeff_annotated.vcf
      rm 27hrs.wf_snp.vcf
      mv snpEff_genes.txt 27hrs.wf_snp.snpEff_genes.txt
  fi

Command exit status:
  1

Command output:
  (empty)

Command error:
  INFO:    Converting SIF file to temporary sandbox...
  WARNING: underlay of /etc/localtime required more than 50 (78) bind mounts
  VcfFileIterator.parseVcfLine(133):plicFatal error reading file '27hrs.snpeff_annotated.vcf' (line: 1):
  [0.003s][warning][os,container] Duplicate cpuset controllers detected. Picking /sys/fs/cgroup/cpuset, skipping /home/plzmwl/anaconda3/envs/nextflow/var/singularity/mnt/session/final/sys/fs/cgroup/cpuset.
  Exception in thread "main" java.lang.RuntimeException: java.lang.RuntimeException: Impropper VCF entry: Not enough fields (missing tab separators?).
  [0.003s][warning][os,container] Duplicate cpuset controllers detected. Picking /sys/fs/cgroup/cpuset, skipping /home/plzmwl/anaconda3/envs/nextflow/var/singularity/mnt/session/final/sys/fs/cgroup/cpuset.
        at org.snpeff.fileIterator.VcfFileIterator.parseVcfLine(VcfFileIterator.java:134)
  INFO: at org.snpeff.fileIterator.VcfFileIterator.readNext(VcfFileIterator.java:185)
        at org.snpeff.fileIterator.VcfFileIterator.readNext(VcfFileIterator.java:58)
  rk dirat org.snpeff.fileIterator.FileIterator.hasNext(FileIterator.java:123)
  /data/at org.snpsift.SnpSiftCmdAnnotate.annotate(SnpSiftCmdAnnotate.java:77)
        at org.snpsift.SnpSiftCmdAnnotate.run(SnpSiftCmdAnnotate.java:410)
  p: youat org.snpsift.SnpSiftCmdAnnotate.run(SnpSiftCmdAnnotate.java:397)
        at org.snpsift.SnpSift.run(SnpSift.java:580)
  - Checat org.snpsift.SnpSift.main(SnpSift.java:76)
  Caused by: java.lang.RuntimeException: Impropper VCF entry: Not enough fields (missing tab separators?).
  [0.003s][warning][os,container] Duplicate cpuset controllers detected. Picking /sys/fs/cgroup/cpuset, skipping /home/plzmwl/anaconda3/envs/nextflow/var/singularity/mnt/session/final/sys/fs/cgroup/cpuset.
        at org.snpeff.vcf.VcfEntry.parse(VcfEntry.java:1035)
        at org.snpeff.vcf.VcfEntry.<init>(VcfEntry.java:247)
        at org.snpeff.fileIterator.VcfFileIterator.parseVcfLine(VcfFileIterator.java:131)
        ... 8 more
  INFO:    Cleaning up image...

Work dir:
  /data/test_data/sorted/workspace/3c/4e4a670dff7fda1738d498c38fe691

Tip: you can try to figure out what's wrong by changing to the process work dir and showing the script file named `.command.sh`

 -- Check '.nextflow.log' file for details
```

**Comment by SamStudio8** [comment]
Hey @mattloose, can you advise if `/data/test_data/sorted/workspace/3c/4e4a670dff7fda1738d498c38fe691/27hrs.snpeff_annotated.vcf` is non-empty and looks VCFy? I can send a data request to you if you're able to share the data.

If not, can you check both ` /data/test_data/sorted/workspace/3c/4e4a670dff7fda1738d498c38fe691/input.vcf.gz` and ` /data/test_data/sorted/workspace/3c/4e4a670dff7fda1738d498c38fe691/27hrs.snpeff_annotated.vcf` with `vcf-validate` or vcflib's `vcfcheck` to see what the specific malformation is?

**Comment by mattloose** [comment]
I can confirm that the first file is non empty and looks VCFy. Unfortunately I cannot share the whole data.

If I run that file through vcf-validator I get:

`
 vcf-validator /data/test_data/sorted/workspace/3c/4e4a670dff7fda1738d498c38fe691/27hrs.snpeff_annotated.vcf.gz
Could not parse the fileformat version string [[0.003s][warning][os,container] Duplicate cpuset controllers detected. Picking /sys/fs/cgroup/cpuset, skipping /home/plzmwl/anaconda3/envs/nextflow/var/singularity/mnt/session/final/sys/fs/cgroup/cpuset.], assuming VCFv4.2
Broken VCF header, no column names?
 at /usr/share/perl5/Vcf.pm line 172, <__ANONIO__> line 1.
        Vcf::throw(Vcf4_2=HASH(0x558e2756dc00), "Broken VCF header, no column names?") called at /usr/share/perl5/Vcf.pm line 867
        VcfReader::_read_column_names(Vcf4_2=HASH(0x558e2756dc00)) called at /usr/share/perl5/Vcf.pm line 602
        VcfReader::parse_header(Vcf4_2=HASH(0x558e2756dc00)) called at /usr/share/perl5/Vcf.pm line 2557
        VcfReader::run_validation(Vcf4_2=HASH(0x558e2756dc00)) called at /usr/bin/vcf-validator line 60
        main::do_validation(HASH(0x558e2753d470)) called at /usr/bin/vcf-validator line 14
`

The input.vcf.gz gives the following when checked with vcf-validator:

`
vcf-validator /data/test_data/sorted/workspace/3c/4e4a670dff7fda1738d498c38fe691/input.vcf.gz
The header tag 'reference' not present. (Not required but highly recommended.)
`

Thanks!

**Comment by SamStudio8** [comment]
Sorry just to check, is this "Duplicate cpuset controllers" message actually present in `27hrs.snpeff_annotated.vcf`? It sounds as though some Singularity debugging information has found its way in to the header.

**Comment by SamStudio8** [comment]
Is it also present in `input.vcf.gz`, or does it only appear after annotation with SnpEff?

**Comment by SamStudio8** [comment]
Java strikes again... https://bugs.openjdk.org/browse/JDK-8272121. Looks like we need to provide some extra flags to avoid this, thanks for the report.

**Comment by mattloose** [comment]
Glad you've been able to track it down to something more than just "Matt is really stupid".

**Comment by mattloose** [comment]
I can confirm that adding that JAVA option to the config fixes the problem and the workflow completes.

Thanks!

**Comment by SamStudio8** [comment]
Thanks for confirming! I've opened a ticket to patch this for our next release.

**Comment by SamStudio8** [comment]
This config now ships as standard in wf-human-variation 1.6.1, thanks for raising it!

**Comment by mattloose** [comment]
Great

As a distinct issue... have you benchmarked the speed of SNP calling when you provide a bed file vs not providing a bed file? There seems to be almost no difference in speed...
