### ISSUE TITLE
[Bug]: How does mapula calculate median quality score?

### ISSUE THREAD

**Issue by ymcki** [epi2me-labs/wf-human-variation#53]
### What happened?

Since the mapula github is gone, I suppose this is the place to discuss it. Please let me know if I am wrong.

I am running the pipeline with mapula flag to generate mapula files. On the way, it also generates unmapped bams and also mapped pass cram. 
mapula reported median_quality for each chromosome in the csv and json file.
Based on my understanding of the code, these stats are calculated from pass.cram. 

### Operating System

ubuntu 20.04

### Workflow Execution

Command line

### Workflow Execution - CLI Execution Profile

None

### Workflow Version

1.6.0

### Relevant log output

```shell
I then manually calculate the average base quality using a simple pysam script. 
My average base quality is significantly higher than the median_quality reported by mapula (e.g. Q30.6 vs Q20.5)
Then I also wrote a script to compute median quality for each read and then average it. It is a bit lower but it is still Q29.8.

I looked at several records of pass.cram, it doesn't seem to me it is possible the median quality is close to Q20.5.
So how does mapula compute this median quality value? Does it take into account of errors relative to the reference genome?
```

**Comment by RenzoTale88** [comment]
@ymcki thanks for getting in touch with this. We are in the process of discontinuing `mapula` within the workflow. We recommend you use the read-wise quality values generated by `bamstats` (the file `.readstats.tsv.gz` in your output directory ). You can find details on how the values are calculated on the [fastcat](https://github.com/epi2me-labs/fastcat) GitHub page.

**Comment by ymcki** [comment]
Thanks for your follow up.

This is one of the lines I extracted from one of my readstats.tsv.gz output
bdb097d1-5209-45ce-8f6d-fb7d7eeff5f2    HG002   haplotype1-0000034      99.7679 8.7590  2       3870    2118
        6194    4076    -       4131    3877    11.376  3813    55      263     81      97.876  90.341

How do I get the 11.376 mean quality? Is it calculated from reported base quality from the raw read file? 

If I use the error rate formula = 1.0 - (match/(match+ins+del+sub)), then I have an error rate of .90527065527065527065 which corresponds to a quality score of 10.235. Neither of these number agree with acc 90.341 and mean_quality 11.376.

On the other hand, mean_quality of 11.376 doesn't seem to be from acc 90.341 as the latter will give you a quality of 10.151.

Where can I find the doc of how "mean_quality", "iden" and "acc" were calculated?

**Comment by ymcki** [comment]
Find the formulas from the source code. NM is from the NM tag of bam file.

        size_t sub = NM - ins - delt;
        size_t length = match + ins + delt;
        float iden = 100 * ((float)(match - sub)) / match;
        float acc = 100 - 100 * ((float)(NM)) / length;

        uint32_t read_length = b->core.l_qseq;
        float mean_quality = mean_qual_from_bam(bam_get_qual(b), read_length);

So now I understand acc and iden. mean_quality is simply the average of the reported base quality from basecaller which I think is not that trustworthy. It would be great if acc is also translated to q score and reported in the output as well.

**Comment by ymcki** [comment]
Forget about it. Some reads have 100% identity, so Q score will be infinity. So I think the output is fine as is. I can calculate the median read quality from acc.
