### ISSUE TITLE
For non-model organisms? 

### ISSUE THREAD

**Issue by CWYuan08** [epi2me-labs/wf-human-variation#55]
### Ask away!

Dear all, 

I am wondering if I can run this pipeline for non-human data? Has anyone tried? What precautions I need to be aware of?

Many Thanks!
CW

**Comment by CWYuan08** [comment]
Hi, I tired to run the pipeline for our model organism, but got an errorr:

Process `getGenome (1)` terminated with an error exit status (65)

Command error:
  The genome build detected in the BAM is not compatible with this workflow.

--------------------------------------------------------------------------------
This is epi2me-labs/wf-human-variation v1.6.1-ge2f6b6a.
--------------------------------------------------------------------------------
WARN: Killing running tasks (3)
executor >  local (20)
[c3/42a85c] process > decompress_ref                 [100%] 1 of 1 ✔
[fa/d1f3ff] process > index_ref_fai                  [100%] 1 of 1 ✔
[1b/6a0af9] process > bam_ingress:check_for_align... [100%] 1 of 1 ✔
[-        ] process > bam_ingress:cram_to_bam        -
[b9/705eb9] process > bam_ingress:minimap2_alignm... [100%] 1 of 1 ✔
[4c/61ceb2] process > getGenome (1)                  [  0%] 0 of 1
[24/30e1de] process > cram_cache                     [100%] 1 of 1 ✔
[a6/04c8db] process > getAllChromosomesBed (1)       [100%] 1 of 1 ✔
[62/bb1c91] process > mosdepth (1)                   [  0%] 0 of 1
[92/07daec] process > readStats (1)                  [  0%] 0 of 1
[7c/cd63df] process > getVersions                    [100%] 1 of 1 ✔
[92/88edc7] process > getParams                      [100%] 1 of 1 ✔
[-        ] process > get_coverage                   -
[-        ] process > failedQCReport                 -
[-        ] process > makeAlignmentReport            -
executor >  local (20)
[c3/42a85c] process > decompress_ref                 [100%] 1 of 1 ✔
[fa/d1f3ff] process > index_ref_fai                  [100%] 1 of 1 ✔
[1b/6a0af9] process > bam_ingress:check_for_align... [100%] 1 of 1 ✔
[-        ] process > bam_ingress:cram_to_bam        -
[b9/705eb9] process > bam_ingress:minimap2_alignm... [100%] 1 of 1 ✔
[4c/61ceb2] process > getGenome (1)                  [100%] 1 of 1, failed: 1 ✘
[24/30e1de] process > cram_cache                     [100%] 1 of 1 ✔
[a6/04c8db] process > getAllChromosomesBed (1)       [100%] 1 of 1 ✔
[-        ] process > mosdepth (1)                   -
[-        ] process > readStats (1)                  -
[7c/cd63df] process > getVersions                    [100%] 1 of 1 ✔
[92/88edc7] process > getParams                      [100%] 1 of 1 ✔
[-        ] process > get_coverage                   -
[-        ] process > failedQCReport                 -
[-        ] process > makeAlignmentReport            -
executor >  local (20)
[c3/42a85c] process > decompress_ref                 [100%] 1 of 1 ✔
[fa/d1f3ff] process > index_ref_fai                  [100%] 1 of 1 ✔
[1b/6a0af9] process > bam_ingress:check_for_align... [100%] 1 of 1 ✔
[-        ] process > bam_ingress:cram_to_bam        -
[b9/705eb9] process > bam_ingress:minimap2_alignm... [100%] 1 of 1 ✔
[4c/61ceb2] process > getGenome (1)                  [100%] 1 of 1, failed: 1 ✘
[24/30e1de] process > cram_cache                     [100%] 1 of 1 ✔
[a6/04c8db] process > getAllChromosomesBed (1)       [100%] 1 of 1 ✔
[-        ] process > mosdepth (1)                   -
[-        ] process > readStats (1)                  -
[7c/cd63df] process > getVersions                    [100%] 1 of 1 ✔
[92/88edc7] process > getParams                      [100%] 1 of 1 ✔
[-        ] process > get_coverage                   -
[-        ] process > failedQCReport                 -
[-        ] process > makeAlignmentReport            -
[99/3fd032] process > lookup_clair3_model (1)        [100%] 1 of 1 ✔
[-        ] process > snp:make_chunks                -
[-        ] process > snp:pileup_variants            -
[-        ] process > snp:aggregate_pileup_variants  -
[-        ] process > snp:select_het_snps            -
[-        ] process > snp:phase_contig               -
[-        ] process > snp:get_qual_filter            -
[-        ] process > snp:create_candidates          -
[-        ] process > snp:evaluate_candidates        -
[-        ] process > snp:aggregate_full_align_va... -
[-        ] process > snp:merge_pileup_and_full_vars -
[-        ] process > snp:post_clair_phase_contig    -
[-        ] process > snp:aggregate_all_variants     -
[12/592801] process > snp:getVersions                [100%] 1 of 1 ✔
[0b/42b09b] process > snp:getParams                  [100%] 1 of 1 ✔
[-        ] process > snp:vcfStats                   -
[-        ] process > snp:makeReport                 -
[-        ] process > output_snp                     -
[-        ] process > configure_jbrowse (1)          -
[6c/5aac89] process > publish_artifact (5)           [100%] 5 of 5
ERROR ~ Error executing process > 'getGenome (1)'

What's the requirement for the reference genome build?

Thank you very much!

Best,
CW

**Comment by SamStudio8** [comment]
Hi @CWYuan08, the workflow should generally support non-human organisms however some aspects of the workflow require the hg38 or hg19 human reference specifically. This is missing from our README so I will make a ticket to document this better.

It looks like you just running SV and SNP parts of the workflow? I think our recent changes to provide automatic annotation may be enforcing a human reference for SNP and SV; which we should look at.

**Comment by CWYuan08** [comment]
Dear @SamStudio8,

many thanks for prompt reply! Yes I would like to do SNP variant calling, I also have an annotation, if this can be added as an option. 
Thank you very much for looking into this! We have a lot of samples ready to run this analysis with.

Best,
CW

**Comment by RenzoTale88** [comment]
@CWYuan08 the workflow should currently run for non-model organisms. Just be sure update the workflow to v1.7.1:
```
nextflow pull epi2me-labs/wf-human-genome -r v1.7.1
```

And then set `--annotation false --cnv false --str false`, and the workflow should run fine regardless of the

**Comment by CWYuan08** [comment]
Dear @SamStudio8, hi, I am running this analysis again for other non-model species: 

nextflow run epi2me-labs/wf-human-variation --bam final_merged.bam --basecaller_cfg 'clair3:dna_r10.4.1_e8.2_260bps_sup@v4.0.0' --ref ref.dna.toplevel.fasta --sample_name barcode01 --snp --sv -profile singularity --phased, I am getting this issue again: 

Caused by:
  Process `getGenome (1)` terminated with an error exit status (65)

Command executed:

  samtools idxstats final_merged.bam > final_merged.bam_genome.txt
  get_genome.py --chr_counts final_merged.bam_genome.txt -o output.txt 
  genome_build=`cat output.txt`

what should I change? 

Thank you very much for your help!!

**Comment by CWYuan08** [comment]
Dear @SamStudio8, 

hi, I am running this analysis again for other non-model species:

nextflow run epi2me-labs/wf-human-variation --bam final_merged.bam --basecaller_cfg 'clair3:dna_r10.4.1_e8.2_260bps_sup@v4.0.0' --ref ref.dna.toplevel.fasta --sample_name barcode01 --snp --sv -profile singularity --phased, I am getting this issue again:

Caused by:
Process getGenome (1) terminated with an error exit status (65)

Command executed:

samtools idxstats final_merged.bam > final_merged.bam_genome.txt
get_genome.py --chr_counts final_merged.bam_genome.txt -o output.txt
genome_build=cat output.txt

what should I change?

Thank you very much for your help!!
