### ISSUE TITLE
ID in VCF file

### ISSUE THREAD

**Issue by keenhl** [epi2me-labs/wf-human-variation#57]
### Ask away!

When I run the SV workflow I get a VCF file.  In the ID column, the values are similar to that below.  DEL = deletion and INS = insertion, but what what does the last part (i.e. FAS2) represent, or is this just a randomly generated ID?

Sniffles2.DEL.FAS2

**Comment by RenzoTale88** [comment]
Hi @keenhl, the SV name follow the pattern:
```
id=f"{svtype}.{task.sv_id:X}S{task.id:X}",
```
Where X indicates the hex-converted SV id and task ID.
Therefore, your SV `Sniffles.DEL.FAS2` == `Sniffles.DEL, task.sv_id=250, task.id=2`.
