### ISSUE TITLE
Fatal singularity pulling error

### ISSUE THREAD

**Issue by weishwu** [epi2me-labs/wf-human-variation#60]
Same issue was reported in this thread: https://github.com/epi2me-labs/wf-human-variation/issues/13
@SamStudio8 answered that it can be solved by manually pulling the image. Could anyone tell me how to do this exactly?

My command-line that triggered the error:

```
export NXF_SINGULARITY_CACHEDIR=${vardir}/nextflow_singularity_images/

nextflow run epi2me-labs/wf-human-variation \
    -profile singularity \
    --snp --sv --cnv --str \
    --bam ${alndir}/combined.sorted.aligned.bam \
    --ref ${ref_fasta} \
    --sample_name combined \
    --out_dir ${vardir} \
    --bam_min_coverage 10 \
    --tr_bed ${tf_bed} \
    --sv_types INS,DEL,DUP,INV \
    --sv_benchmark \
    --threads 10 \
    -c ${nf_conf} &
```

Error:
```
FATAL:   While making image from oci registry: while building SIF from layers: conveyor failed to get: no descriptor found for reference "518562e23732df1800d2659f573b65016f4ad99ee894002ae2b76b36ffbc8b90"
```

**Comment by SamStudio8** [comment]
Hi Weisheng, is the error consistent? This looks like a transient error
with pulling the image that should go away on a retry.

**Comment by weishwu** [comment]
The error is consistent when I retry, however, it's gone when I remove `--cnv --str`.
I got another error which is easy to solve:

```
ERROR ~ * --basecaller_cfg: dna_r10.4.1_e8.2_400bps_hac@v3.5.2 is not a valid choice, pick one of:
    - dna_r10.4.1_e8.2_260bps_fast@v4.1.0
    - dna_r10.4.1_e8.2_260bps_hac@v4.1.0
    - dna_r10.4.1_e8.2_260bps_sup@v4.1.0
    - dna_r10.4.1_e8.2_400bps_fast@v4.1.0
    - dna_r10.4.1_e8.2_400bps_fast@v4.2.0
    - dna_r10.4.1_e8.2_400bps_hac@v4.1.0
    - dna_r10.4.1_e8.2_400bps_hac@v4.2.0
    - dna_r10.4.1_e8.2_400bps_sup@v4.1.0
    - dna_r10.4.1_e8.2_400bps_sup@v4.2.0
    - dna_r9.4.1_e8_fast@v3.4
    - dna_r9.4.1_e8_hac@v3.3
    - dna_r9.4.1_e8_sup@v3.3
    - custom
    - clair3:dna_r10.4.1_e8.2_260bps_hac@v4.0.0
    - clair3:dna_r10.4.1_e8.2_260bps_sup@v4.0.0
    - clair3:dna_r10.4.1_e8.2_400bps_hac
    - clair3:dna_r10.4.1_e8.2_400bps_hac@v3.5.2
    - clair3:dna_r10.4.1_e8.2_400bps_hac@v4.0.0
    - clair3:dna_r10.4.1_e8.2_400bps_hac_prom
    - clair3:dna_r10.4.1_e8.2_400bps_sup@v3.5.2
    - clair3:dna_r10.4.1_e8.2_400bps_sup@v4.0.0
    - clair3:dna_r9.4.1_450bps_hac
    - clair3:dna_r9.4.1_450bps_hac_prom
 ```

The basecalling model was done by someone else, but I can see from the fastq files that it's `dna_r10.4.1_e8.2_400bps_hac@v3.5.2`. Is this the same as `clair3:dna_r10.4.1_e8.2_400bps_hac@v3.5.2`?

I don't need to redo basecalling, but just want to use the right model for SNP calling.

**Comment by weishwu** [comment]
Sorry, but got another error:
```
The genome build detected in the BAM is not compatible with this workflow
```

My genome is `Mus_musculus.GRCm38.dna_sm.primary_assembly.fa`.

**Comment by RenzoTale88** [comment]
@weishwu can you try running the workflow without `--cnv` and `--str`, and disable annotation with `--skip_annotation`. This should allow you to run the workflow

**Comment by SamStudio8** [comment]
Closing as this issue seems to have gone quiet, please open a new issue if there are any problems.
