### ISSUE TITLE
Speed of variant calling with a BED file.

### ISSUE THREAD

**Issue by cjw85** [epi2me-labs/wf-human-variation#61]
Great

As a distinct issue... have you benchmarked the speed of SNP calling when you provide a bed file vs not providing a bed file? There seems to be almost no difference in speed...

_Originally posted by @mattloose in https://github.com/epi2me-labs/wf-human-variation/issues/52#issuecomment-1601283346_

**Comment by mattloose** [comment]
Thanks for making this a distinct issue @cjw85 - it would be great if this could be looked at. My expectation is that providing a bed file for a small subset of the genome (say 1-10%) would result in a significant increase in speed for SNP calling - but this is not the case currently.

**Comment by SamStudio8** [comment]
@mattloose Can you send a log file from a run where you observe this? I suspect the chunking may be ignoring the provided BED if this is the case, but a log will help us narrow this down.

**Comment by SamStudio8** [comment]
@mattloose This should be fixed in 1.8.2

**Comment by mattloose** [comment]
Thanks - it is fixed although in our experience thus far it is still quicker to subset the bam file by the bed before running the workflow. Subsetting the bam allows the workflow to complete in around 2/3 of the time.
