### ISSUE TITLE
How to Align, Variant call, SV CNV from Fastq FIles GIAB

### ISSUE THREAD

**Issue by kiranpatil222** [epi2me-labs/wf-human-variation#62]
### Ask away!

Hi,

I have down loaded Fastq ( [HG002_ONT-UL_GIAB_20200122.fastq](https://ftp-trace.ncbi.nlm.nih.gov/ReferenceSamples/giab/data_indexes/AshkenazimTrio/sequence.index.AJtrio_UCSC_ONT_UL_guppy-V3.2.4_2020-01-22) ), I have run the variant calling  from Demo data,

https://github.com/genome-in-a-bottle/giab_data_indexes

Now How di run same from Fastq file

**Comment by SamStudio8** [comment]
Hi @kiranpatil222, wf-human-variation requires an unaligned or aligned BAM (or CRAM). You can generate an unaligned BAM from FASTQ with `samtools import` http://www.htslib.org/doc/samtools-import.html. I can see a corresponding BAM for the FASTQ you have downloaded on the NCBI FTP site in this directory: https://ftp.ncbi.nlm.nih.gov/ReferenceSamples/giab/data/AshkenazimTrio/HG002_NA24385_son/Ultralong_OxfordNanopore/guppy-V3.2.4_2020-01-22/.

You may also be interested in our recent data release https://labs.epi2me.io/giab-2023.05/.

**Comment by kiranpatil222** [comment]
Hi i ran samtools, as follows.
`samtools import HG002_ONT-UL_GIAB_20200122.fastq >HG002_ONT-UL_GIAB_20200122.bam`

is this the right command, i could get bam from above but when i try to sort / index it , i get below error,
` [E::sam_index_build3] SAM file "HG002_ONT-UL_GIAB_20200122.bam" not BGZF compressed
  samtools index: failed to create index for "HG002_ONT-UL_GIAB_20200122.bam"`

Please correct me if i am doing anything wrong here
