### ISSUE TITLE
The math about threshold_lookup

### ISSUE THREAD

**Issue by weishwu** [epi2me-labs/wf-human-variation#63]
I looked into the code in `bin/get_filter_calls_command.py` and found the lines that determine the depth cutoff:
```
threshold_lookup = ['0'] + ['2'] * 10 + ['3'] * 9 + ['5'] * 20 + ['8'] * 100
var_depth_filter_cutoff = int(threshold_lookup[int(round(avg_depth))])
```
What's the mathematics explanation of the first line?
Thanks.

**Comment by RenzoTale88** [comment]
Hi @weishwu the code is a simple heuristic, extracting the thresholds at different coverage values
