### ISSUE TITLE
How to select --basecaller_cfg:

### ISSUE THREAD

**Issue by kiranpatil222** [epi2me-labs/wf-human-variation#66]
### Ask away!

Hi,

I have down loaded Fastq ( [HG002_ONT-UL_GIAB_20200122.fastq](https://ftp-trace.ncbi.nlm.nih.gov/ReferenceSamples/giab/data_indexes/AshkenazimTrio/sequence.index.AJtrio_UCSC_ONT_UL_guppy-V3.2.4_2020-01-22) ), I have run the variant calling from Demo data,

https://github.com/genome-in-a-bottle/giab_data_indexes

Converted Fastq to BAM then sot index through Minimap2 / samtools,  In order to run SNP CNV SV as shown in the demo data

How to i chose what to give to parameter `--basecaller_cfg:` and Is `'--bed` should be the callable regions from WGS fasta Ref file?

and Where can i find the documentation for this WF-Human variation workflow, i do not see any help from `nextflow run epi2me-labs/wf-human-variation --help` it just says `Launching `https://github.com/epi2me-labs/wf-human-variation` [fervent_swirles] DSL2 - revision: e2f6b6a62e [master]
Cannot enable more than one container engine -- Choose either one of: docker, singularity``

**Comment by SamStudio8** [comment]
Hi @kiranpatil222:

 `--basecaller-cfg` should be set to the basecaller configuration that was used to generate the data in question and is used to determine the correct Clair3 model to use for SNP calling. The data set you are referring to seems to be the "Oxford Nanopore ultralong (guppy-V3.2.4_2020-01-22)", according to the medata CSV I could find here [HG002_ONT-UL_GIAB_20200122.metadata.csv](https://ftp-trace.ncbi.nlm.nih.gov/ReferenceSamples/giab/data/AshkenazimTrio/HG002_NA24385_son/Ultralong_OxfordNanopore/guppy-V3.2.4_2020-01-22/HG002_ONT-UL_GIAB_20200122.metadata.csv), the "dna_r9.4.1_450bps_hac.cfg" model was used. The correct choice for this workflow is therefore `--basecaller_cfg clair3:dna_r9.4.1_450bps_hac`.

The `--bed` file is optional, you can leave this empty to analyse the entire genome, or provide a BED file to only analyse parts of the genome you are interested in (such as the callable regions you mentioned).

On your issue with `--help`, you should open a Bug report to allow us to diagnose your problem, but it would seem that you have enabled docker and singularity simultaneously. This could have occurred if you have a Nextflow configuration file that enables these profiles somewhere that Nextflow looks for them by default (eg. $HOME/.nextflow/config).

You may be interested in our EPI2ME application that allows you to run workflows through a graphical interface that describes all of the different workflow options. This can be downloaded for free from our website https://labs.epi2me.io/downloads/.

**Comment by kiranpatil222** [comment]
@SamStudio8 ,

Thank you, i have got below error with the `basecaller_cfg` you provided, even i cross checked in meta file it is same
* --basecaller_cfg: dna_r9.4.1_450bps_hac is not a valid choice, pick one of:
    - dna_r10.4.1_e8.2_260bps_fast@v4.1.0
    - dna_r10.4.1_e8.2_260bps_hac@v4.1.0
    - dna_r10.4.1_e8.2_260bps_sup@v4.1.0
    - dna_r10.4.1_e8.2_400bps_fast@v4.1.0
    - dna_r10.4.1_e8.2_400bps_fast@v4.2.0
    - dna_r10.4.1_e8.2_400bps_hac@v4.1.0
    - dna_r10.4.1_e8.2_400bps_hac@v4.2.0
    - dna_r10.4.1_e8.2_400bps_sup@v4.1.0
    - dna_r10.4.1_e8.2_400bps_sup@v4.2.0
    - dna_r9.4.1_e8_fast@v3.4
    - dna_r9.4.1_e8_hac@v3.3
    - dna_r9.4.1_e8_sup@v3.3
    - custom
    - clair3:dna_r10.4.1_e8.2_260bps_hac@v4.0.0
    - clair3:dna_r10.4.1_e8.2_260bps_sup@v4.0.0
    - clair3:dna_r10.4.1_e8.2_400bps_hac
    - clair3:dna_r10.4.1_e8.2_400bps_hac@v3.5.2
    - clair3:dna_r10.4.1_e8.2_400bps_hac@v4.0.0
    - clair3:dna_r10.4.1_e8.2_400bps_hac_prom
    - clair3:dna_r10.4.1_e8.2_400bps_sup@v3.5.2
    - clair3:dna_r10.4.1_e8.2_400bps_sup@v4.0.0
    - clair3:dna_r9.4.1_450bps_hac
    - clair3:dna_r9.4.1_450bps_hac_prom

**Comment by kiranpatil222** [comment]
Now i am trying with `clair3:dna_r9.4.1_450bps_hac`
