### ISSUE TITLE
EPI2ME Human Variant Analysis 

### ISSUE THREAD

**Issue by kiranpatil222** [epi2me-labs/wf-human-variation#67]
### Ask away!

Hi, @SamStudio8 

Where can i find How to install and quick start WF-Variant analysis through epi2me Application,

In my Server, I have NextFlow, Docker and Singularity installed and I have installed epi2me from the download link you provided Debian file with sudo apt install epi2me_5.1.0_amd64.deb,

Next I have no idea how to use /run the pipeline if you can provide quick start like in Windows, it will be helpful.?
Like you have commands mentioned here for [wf-human-variation](https://github.com/epi2me-labs/wf-human-variation)

**Comment by SamStudio8** [comment]
Hi @kiranpatil222, the EPI2ME application is a desktop GUI application intended to be used to manage analyses from your local machine. If your server supports submitting jobs via a scheduler then you can work with your system administrator to configure Nextflow to submit jobs from our application. You can find more information about the EPI2ME application on our website https://labs.epi2me.io/quickstart/.

If you wish to conduct your analysis on your server, then your best bet is using the command line examples provided in the README.
