### ISSUE TITLE
--resume option

### ISSUE THREAD

**Issue by kiranpatil222** [epi2me-labs/wf-human-variation#68]
### Ask away!

Hi,

I ran pipeline, unfortunately i did not use `-bg`  to run in the background after several hours my VPN got interrupted, then when i restarted pipeline with `-resume` it all restarted over again?

Isnt there resume option for this pipeline or is that i need some any other option ?

**Comment by SamStudio8** [comment]
@kiranpatil222 The option is `-resume` (single dash). This should recover and resume the most recently run workflow but there are cases in which this will not work. There is a useful Nextflow article describing the behaviour of resume in detail here https://www.nextflow.io/blog/2019/demystifying-nextflow-resume.html. If you are still having problems resuming our workflows, please open a bug report (and not a question) and fill in the additional information we require to help diagnose your issues.
