### ISSUE TITLE
--resume option

### ISSUE THREAD

**Issue by kiranpatil222** [epi2me-labs/wf-human-variation#69]
### Operating System

Linux/Ubuntu 22

### Workflow Version

v1.6.1

### Workflow Execution

EPI2ME CLI NextFlow

### EPI2ME Version

v1.6.1

### CLI command run

OUTPUT=output
nextflow -bg run epi2me-labs/wf-human-variation \
    -w ${OUTPUT}/workspace \
    -profile singularity \
    --snp --sv \
    --threads 16 \
    --bam /data/shared/clinical/LongRead/ONT/output/HG002_ONT-UL_GIAB_20200122_Sort.bam \
    --bed /data/shared/clinical/ExomeAnalysis/clinical/Scratch/Resources/BedFiles/Hg38_WGS.bed \
    --ref /data/shared/clinical/LongRead/Data/resources/Homo_sapiens_assembly38.fasta \
    --basecaller_cfg 'clair3:dna_r9.4.1_450bps_hac'  \
    --sample_name GIAB_20200122 \
    --out_dir ${OUTPUT} -resume

### Workflow Execution - CLI Execution Profile

None

### What happened?

I ran pipeline, unfortunately i did not use -bg to run in the background after several hours my VPN got interrupted, then when i restarted pipeline with -resume it all restarted over again?

Isnt there resume option for this pipeline or is that i need some any other option ?

### Relevant log output

```shell
Long is too long its not taking
```

### Application activity log entry

```shell
Long is too long its not taking
```

**Comment by SamStudio8** [comment]
Hi @kiranpatil222, thanks for this report.

`-resume` is indeed the correct option to be using, so resuming the workflow should work for you here. The command needs to be called from the same directory that you started Nextflow from the first time (as the Nextflow history data is written to the current directory by default). By default the `-resume` option will resume the last workflow that was executed in the current directory.

Please note that when resuming, Nextflow will check the integrity of completed files which may take some time and appear as if the workflow is starting from scratch. You should see the word "cached" in the Nextflow output on your command line. Additionally, if you changed any of the input parameters or options, this may cause the workflow to begin from scratch.

You may find this page on troubleshooting resume helpful https://training.nextflow.io/basic_training/cache_and_resume/#resume-troubleshooting, as it lists most of the scenarios that would trigger the workflow to start over.

If the workflow you wish to restart was not the most recent workflow in the current directory, the section at the end of the page I sent you previously shows you how to use `nextflow log` to find the session ID of the workflow you want to restart and how to resume it: https://www.nextflow.io/blog/2019/demystifying-nextflow-resume.html.

**Comment by kiranpatil222** [comment]
First time when i ran, i ran without `'-bg` and without `-resume` when pipeline broke because of network issue, i added `-bg -resume` Do you yhink is this the cause of restart from scratch ?
