### ISSUE TITLE
wf-human-variation (current) uses outdated version of modbam2bed (0.6.2)

### ISSUE THREAD

**Issue by s-batalov** [epi2me-labs/wf-human-variation#71]
### Is your feature related to a problem?

wf-human-variation (current) uses outdated version of modbam2bed (0.6.2).
Current version of modbam2bed 0.9.5 and contains multiple changes (and corrections).

### Describe the solution you'd like

Use current version of modbam2bed 0.9.5.
Also under --phase_methyl option, compute both phased methylation BEDs and total methylation BEDs, i.e.

> if (params.phase_methyl) {
>             haps = Channel.of(0, 1, 2)

### Describe alternatives you've considered

I run modbam2bed 0.9.5 externally after the wf-human-variation pipeline

**Comment by SamStudio8** [comment]
Hi @s-batalov, thanks for your comments, I'm glad to hear that 1.7.0 has added the phasing feature you were looking for! Indeed the workflow is a little behind on modbam2bed but as it is deprecated now, updating the workflow to use modkit is on the radar instead.
