### ISSUE TITLE
CNV calling failed

### ISSUE THREAD

**Issue by Ligerd5** [epi2me-labs/wf-human-variation#73]
### Is your feature related to a problem?

I executed this command
nextflow run epi2me-labs/wf-human-variation --cnv --bam /srv/nabi/EPIMOL_Malaria/BAM_hg38/isolate03.bam --ref /srv/nabi/EPIMOL_Malaria/copy_number/hg38.fa.gz --bin_size 500

N E X T F L O W  ~  version 23.04.3
NOTE: Your local project version looks outdated - a different revision is available in the remote repository [75ed626313]
Launching `https://github.com/epi2me-labs/wf-human-variation` [serene_mccarthy] DSL2 - revision: decd849f57 [master]

||||||||||   _____ ____ ___ ____  __  __ _____      _       _
||||||||||  | ____|  _ \_ _|___ \|  \/  | ____|    | | __ _| |__  ___
|||||       |  _| | |_) | |  __) | |\/| |  _| _____| |/ _` | '_ \/ __|
|||||       | |___|  __/| | / __/| |  | | |__|_____| | (_| | |_) \__ \
||||||||||  |_____|_|  |___|_____|_|  |_|_____|    |_|\__,_|_.__/|___/
||||||||||  wf-human-variation v1.7.0-gdecd849
--------------------------------------------------------------------------------
Core Nextflow options
  revision           : master
  runName            : serene_mccarthy
  containerEngine    : docker
  container          : ontresearch/wf-human-variation:sha0337567399c09ef14d1ab9cc114f77de86398e12
  launchDir          : /home/nabi
  workDir            : /home/nabi/work
  projectDir         : /home/nabi/.nextflow/assets/epi2me-labs/wf-human-variation
  userName           : nabi
  profile            : standard
  configFiles        : /home/nabi/.nextflow/assets/epi2me-labs/wf-human-variation/nextflow.config

Workflow Options
  cnv                : true

Main options
  bam                : /srv/nabi/EPIMOL_Malaria/BAM_hg38/isolate03.bam
  ref                : /srv/nabi/EPIMOL_Malaria/copy_number/hg38.fa.gz

Multiprocessing Options
  ubam_map_threads   : 8
  ubam_sort_threads  : 3
  ubam_bam2fq_threads: 1

!! Only displaying parameters that differ from the pipeline defaults !!
--------------------------------------------------------------------------------
If you use epi2me-labs/wf-human-variation for your analysis please cite:

* The nf-core framework
  https://doi.org/10.1038/s41587-020-0439-x

--------------------------------------------------------------------------------
This is epi2me-labs/wf-human-variation v1.7.0-gdecd849.
--------------------------------------------------------------------------------
WARN: CNV calling subworkflow does not support CRAM. You don't need to do anything, but we're just letting you know that:
WARN: - If your input file is CRAM, it will be converted to a temporary BAM inside the workflow automatically.
WARN: - If your input requires alignment or basecalling, the outputs will be saved to your output directory as BAM instead of CRAM.
executor >  local (7)
[6c/cf34d9] process > decompress_ref                  [  0%] 0 of 1
[-        ] process > index_ref_fai                   -
[36/f4201e] process > bam_ingress:samtools_index (1)  [100%] 1 of 1, failed: 1 ✘
[-        ] process > bam_ingress:check_for_alignment -
[-        ] process > bam_ingress:cram_to_bam         -
[-        ] process > bam_ingress:minimap2_alignment  -
[-        ] process > getGenome                       -
[-        ] process > cram_cache                      -
[-        ] process > getAllChromosomesBed            -
[-        ] process > mosdepth_input                  -
[-        ] process > readStats                       -
[bc/5f0176] process > getVersions                     [100%] 1 of 1, failed: 1 ✘
[88/e7157b] process > getParams                       [100%] 1 of 1, failed: 1 ✘
[-        ] process > get_coverage                    -
[-        ] process > makeAlignmentReport             -
[-        ] process > failedQCReport                  -
[-        ] process > cnv:callCNV                     -
[c0/e519bd] process > cnv:getVersions                 [  0%] 0 of 1
[e8/e4517c] process > cnv:getParams                   [  0%] 0 of 1
[-        ] process > cnv:makeReport                  -
[-        ] process > output_cnv                      -
[-        ] process > configure_jbrowse               -
[a0/75192d] process > publish_artifact (1)            [100%] 1 of 1, failed: 1
ERROR ~ Error executing process > 'getVersions'

Caused by:
  Process `getVersions` terminated with an error exit status (127)

Command executed:

  mosdepth --version | sed 's/ /,/' >> versions.txt
  bamstats --version | awk '{print "bamstats,"$1}' >> versions.txt

Command exit status:
  127

Command output:
  (empty)

Command error:
  .command.run: line 291: docker: command not found

Work dir:
  /home/nabi/work/bc/5f0176be86489634f8dedeed8cddae

Tip: you can try to figure out what's wrong by changing to the process work dir and showing the script file named `.command.sh`

 -- Check '.nextflow.log' file for details
WARN: Killing running tasks (3)

The printout suggests it fails at "get versions"
Command error: .command.run: line 291: docker: command not found

Please how do I get the versions and or the docker command.

Any suggestion on this please?

### Describe the solution you'd like

I will like to understand what "getversions" means and how to solve it and also how to get the docker command

### Describe alternatives you've considered

I have also ran this command on the wf-cnv and came up with an error message
N E X T F L O W  ~  version 23.04.3
Launching `https://github.com/epi2me-labs/wf-cnv` [small_minsky] DSL2 - revision: 956b861764 [master]

||||||||||   _____ ____ ___ ____  __  __ _____      _       _
||||||||||  | ____|  _ \_ _|___ \|  \/  | ____|    | | __ _| |__  ___
|||||       |  _| | |_) | |  __) | |\/| |  _| _____| |/ _` | '_ \/ __|
|||||       | |___|  __/| | / __/| |  | | |__|_____| | (_| | |_) \__ \
||||||||||  |_____|_|  |___|_____|_|  |_|_____|    |_|\__,_|_.__/|___/
||||||||||  wf-cnv v0.0.9-g956b861
--------------------------------------------------------------------------------
Core Nextflow options
  revision       : master
  runName        : small_minsky
  containerEngine: docker
  launchDir      : /srv/nabi/EPIMOL_Malaria/copy_number
  workDir        : /srv/nabi/EPIMOL_Malaria/copy_number/work
  projectDir     : /home/nabi/.nextflow/assets/epi2me-labs/wf-cnv
  userName       : nabi
  profile        : standard
  configFiles    : /home/nabi/.nextflow/assets/epi2me-labs/wf-cnv/nextflow.config

Input Options
  bam            : /srv/nabi/EPIMOL_Malaria/BAM_hg38/isolate03.bam

Advanced Options
  map_threads    : 4

!! Only displaying parameters that differ from the pipeline defaults !!
--------------------------------------------------------------------------------
If you use epi2me-labs/wf-cnv for your analysis please cite:

* The nf-core framework
  https://doi.org/10.1038/s41587-020-0439-x

--------------------------------------------------------------------------------
This is epi2me-labs/wf-cnv v0.0.9-g956b861.
--------------------------------------------------------------------------------
ERROR ~ wf-cnv is now deprecated and will no longer receive updates, please use wf-human-variation

 -- Check '.nextflow.log' file for details
Checking input.
Single file input detected.
executor >  local (4)
[c9/877038] process > handleSingleFile (1)   [  0%] 0 of 1
[8e/d6092f] process > pipeline:getVersions   [100%] 1 of 1, failed: 1 ✘
executor >  local (4)
[c9/877038] process > handleSingleFile (1)   [100%] 1 of 1, failed: 1 ✘
[8e/d6092f] process > pipeline:getVersions   [100%] 1 of 1, failed: 1 ✘
[a7/352ea1] process > pipeline:getParams     [100%] 1 of 1, failed: 1 ✘
[-        ] process > pipeline:samtoolsIndex -
[51/89689e] process > pipeline:getGenome (1) [100%] 1 of 1, failed: 1 ✘
[-        ] process > pipeline:bamStats      -
[-        ] process > pipeline:callCNV       -
[-        ] process > pipeline:makeReport    -
[-        ] process > output                 -
ERROR ~ Error executing process > 'pipeline:getVersions'

Caused by:
  Process `pipeline:getVersions` terminated with an error exit status (127)

Command executed:

  python -c "import pysam; print(f'pysam,{pysam.__version__}')" >> versions.txt
  fastcat --version | sed 's/^/fastcat,/' >> versions.txt
  R --version | grep -w R | grep version | cut -f3 -d" " | sed 's/^/R,/' >> versions.txt
  minimap2 --version | sed 's/^/minimap2,/' >> versions.txt
  samtools --version | head -n 1 | sed 's/ /,/' >> versions.txt
  R --slave -e 'packageVersion("QDNAseq")' | cut -d\' -f2 | sed 's/^/QDNAseq,/' >> versions.txt

Command exit status:
  127

Command output:
  (empty)

Command error:
  .command.run: line 290: docker: command not found

Work dir:
  /srv/nabi/EPIMOL_Malaria/copy_number/work/8e/d6092f34f7d6f921ef53f6e2d5b257

Tip: view the complete command output by changing to the process work dir and entering the command `cat .command.out`

 -- Check '.nextflow.log' file for details
ERROR ~ wf-cnv is now deprecated and will no longer receive updates, please use wf-human-variation

 -- Check '.nextflow.log' file for details
WARN: Failed to render execution report -- see the log file for details
WARN: Failed to render execution timeline -- see the log file for details

**Comment by SamStudio8** [comment]
@Ligerd5 I see this line in your log:
```
Command error: .command.run: line 291: docker: command not found
```

Our workflows use [Docker](https://www.docker.com/products/docker-desktop/) to simplify the distribution and running of bioinformatics software needed by the workflow. You need to install Docker into your environment to allow the workflow to run.

Installing Docker is beyond the scope of our ability to support you through this channel but for local execution (eg. your laptop or desktop) we would recommend trying our [EPI2ME desktop application](https://labs.epi2me.io/installation/). When first run EPI2ME will guide you through installing Docker and check that it has been installed correctly. If you want to run our workflows on your institution’s cluster, you should speak to your system administrator about “how to run Docker or Singularity images”.
