### ISSUE TITLE
Is phase_sv implemented in 1.7.1?

### ISSUE THREAD

**Issue by ymcki** [epi2me-labs/wf-human-variation#74]
### Operating System

Ubuntu 22.04

### Workflow Version

v1.7.1

### Workflow Execution

Command line

### Workflow Execution - CLI Execution Profile

None

### What happened?

Is phase_sv really added to 1.7.1. When I grep, it appears only in CHANGELOG.md

### Relevant log output

```shell
/wf-human-variation-1.7.1$ grep -rn phase_sv *
CHANGELOG.md:28:- Perform Sniffles SV phasing with `--phase_sv`
```
```


### Application activity log entry

_No response_

**Comment by SamStudio8** [comment]
Hi @ymcki, thanks for pointing out this mistaken log line in our CHANGELOG, the option is you need is called `--phase_vcf`.

**Comment by ymcki** [comment]
Thanks for your reply. --phase_vcf seems to be able phase both the snp vcf generated by clair3 as well as the sv vcf generated by sniffles. Is that true?

**Comment by SamStudio8** [comment]
That's right. Let us know how you get on with it.

**Comment by ymcki** [comment]
I think it works as expected. Thanks for the clarification.
