### ISSUE TITLE
Allowing fastq input

### ISSUE THREAD

**Issue by parkerpayne** [epi2me-labs/wf-human-variation#75]
### Is your feature related to a problem?

Our lab currently has a sequencer capable of performing live basecalling, and therefore the files we have on hand are all in fastq format. We want to use this workflow, as it has cnv support and other nice-to-haves.

### Describe the solution you'd like

It would be really great if fastq or fastq.gz files were acceptable input, so that we can take the basecalled files and input them directly into this workflow.

### Describe alternatives you've considered

The only other solution is to run minimap independently of the workflow, and then use the bam as input.

**Comment by parkerpayne** [comment]
I have one more question regarding this, you mentioned supplying an unaligned bam to the workflow, does providing an aligned bam result in a shorter runtime, or would this workflow run minimap regardless? Thanks!

**Comment by SamStudio8** [comment]
The workflow will use the alignments from the BAM (skipping alignment),
unless the header of the BAM conflicts with the reference provided.
