### ISSUE TITLE
Tips for filtering modbam2bed data from workflow

### ISSUE THREAD

**Issue by carolinehey** [epi2me-labs/wf-human-variation#76]
### Ask away!

I want to compare my nanopore data to data from EPIC array (850k) at 850k positions. I am trying different filtering steps (coverage, scores ect.) to obtain only the valid positions from my nanopore data. I would like to know how other people filter their methylation data and if anyone have some experience comparring to EPIC array?.

**Comment by cjw85** [comment]
I've never personally made comparisons to EPIC data but I have produced comparisons to bisulphite before (e.g. https://labs.epi2me.io/gm24385-5mc-remora/)

The plots there were made by intersecting the Nanopore BED files with bisulphite bed files based on (indexed on co-ordinates) and then filtering to sites where both sequencing methods had >20 spanning reads.

@artrand or @marcus1487 might have other suggestions.

**Comment by cjw85** [comment]
We have no further suggestions.

**Comment by marcus1487** [comment]
I would add that the recommended tool for aggregating modified base calls from BAM files is now [modkit](https://github.com/nanoporetech/modkit). But stating from aggregated results the simple coverage filter mentioned by @cjw85 is the only filter recommended.
