### ISSUE TITLE
seq_cache_populate.pl: command not found

### ISSUE THREAD

**Issue by ShawnSimp** [epi2me-labs/wf-human-variation#79]
### Operating System

Other Linux (please specify below)

### Other Linux

Ubuntu  22.04

### Workflow Version

v1.7.1

### Workflow Execution

Command line

### CLI command run

 nextflow run epi2me-labs/wf-human-variation -w /scratch/nanopore_data/nf-human-v/workspace_mod -profile standard --sv --cnv --bam /scratch/dorado_analysis/basecalled/sample.bam --ref refs/human/dna/hg38.fa --sample_name Test_sample --out_dir /scratch/nanopore_data/nf-human-v/ --threads 20

### Workflow Execution - CLI Execution Profile

standard (default)

### What happened?

Workflow crashes , error states seq_cache_populate.pl: command not found.  I can see that it exists in my samtools bin in the correct Misc directory. This is being run in conda, so i figured maybe its not accessing the the global samtools installation and tried a local conda installation but that didn't fix the issue

### Relevant log output

```shell
ERROR ~ Error executing process > 'cram_cache (1)'
Caused by:
 Process `cram_cache (1)` terminated with an error exit status (127)
Command executed:
 # Invoke from binary installed to container PATH
 seq_cache_populate.pl -root ref_cache/ hg38.fa
 REF_PATH="ref_cache/%2s/%2s/%s"
Command exit status:
 127
Command output:
 (empty)
Command error:
 .command.sh: line 3: seq_cache_populate.pl: command not found
Work dir:
 /scratch/nanopore_data/nf-human-v/workspace/ab/d65d7fd753b225e751f66209652d14
Tip: view the complete command output by changing to the process work dir and entering the command `cat .command.out`
 -- Check '.nextflow.log' file for details
```

**Comment by SamStudio8** [comment]
Hi @ShawnSimp, our workflows do not support installation of dependencies through conda, `-profile standard` should run the workflow using Docker. Has the workflow configuration been modified to run without Docker or Singularity?

**Comment by ShawnSimp** [comment]
No the workflow configuration hasn't been modified to run without Docker and the error occur also without installing the dependencies on conda. I believe it must be some issue with the nextflow installation of the cluster's environment, as I was able to get the workflow and the same inputs working on a different cluster.

**Comment by SamStudio8** [comment]
@ShawnSimp Thanks for confirming. This shouldn't be related to your conda environment if the workflow is correctly running with Docker, as the dependencies are installed inside the Docker containers used by the workflow. You won't need to install any dependencies yourself to get the workflow running as the Docker images containing all the workflow dependencies will be automatically downloaded by Nextflow.

I've double checked that the base image is correctly shipping the `seq_cache_populate.pl` script.

```
 % docker run docker.io/ontresearch/wf-human-variation:sha0337567399c09ef14d1ab9cc114f77de86398e12 seq_cache_populate.pl
Usage: /home/epi2melabs/conda/bin/seq_cache_populate.pl -root <dir> [-subdirs <n>] input1.fasta ...
       /home/epi2melabs/conda/bin/seq_cache_populate.pl -root <dir> [-subdirs <n>] -find <dir>
```

If this is working elsewhere, it does look like in this case that the workflow instance is trying to run locally (ie. without docker). Is it possible the cluster you are using has a Nextflow config set in your user home at `$HOME/.nextflow/config`? I would suggest checking with your cluster administrator if there are any existing configurations or any requirements to use Docker on your cluster.

**Comment by ShawnSimp** [comment]
@SamStudio8 Its strange, I am the admin of the clusters(perks haha). There is no existing configurations and docker works perfectly and there is no nextflow config in $HOME/.nextflow/.

**Comment by SamStudio8** [comment]
Can you send the full .nextflow.log to see if there is anything that may
help us out here?

**Comment by ShawnSimp** [comment]
Would  nextflow process selectors work if I wanted to increase the # of threads for minimap? and can you feed basecalled fastqs as input instead of bam or fast5?

**Comment by ShawnSimp** [comment]
Perfect, One final query,  is i found for some samples the workflow would stop due to the coverage being below the minimum coverage threshold of 20x required for the analysis. Could this be due to the bam format? its a merge bam(samtools merge) from multiple dorado base-called bam files, the sequencing was perfect so I'm surprise by the coverage. Is there a way to change the minimum coverage threshold?  Thank you

**Comment by cjw85** [comment]
```
nextflow run epi2me-labs/wf-human-variation --help
```

is your friend. The option `--bam_min_coverage` can be used to change this setting. However I really would advise against lowering this further. For adequate variant calling a coverage of 40X is required.
