### ISSUE TITLE
Error in cnv in wf-human-variation

### ISSUE THREAD

**Issue by JbaptisteLam** [epi2me-labs/wf-human-variation#80]
### Operating System

Ubuntu 22.04

### Workflow Version

v1.3.0

### Workflow Execution

EPI2ME Desktop application

### EPI2ME Version

v5.1.1

### Workflow Execution - CLI Execution Profile

None

### What happened?

Hi,

First thank you for providing this bunch of software, it's really helpfull,
We are using EPI2ME desktop application to launch workflows but it raise an error in R plot generation in cnv pipeline in human-variation workflow,
We are working with amplicon data aligned on hg38 so all chromosomes are not covered, perhaps that's the problem,
without using cnv detection in human workflow, analysis worked well

Best regards,

Jean-Baptiste

### Relevant log output

```shell
août-30 12:46:44.706 [Task monitor] ERROR nextflow.processor.TaskProcessor - Error executing process > 'cnv:callCNV (1)'

Caused by:
  Process `cnv:callCNV (1)` terminated with an error exit status (1)

Command executed:

  run_qdnaseq.r --bam amplicon_01_cecile_gaetan_alignment_hg38-sample1.sorted.aligned.bam --out_prefix sample1 --binsize 500 --reference hg38
  cut -f5 sample1_calls.bed | paste sample1_bins.bed - > sample1_combined.bed
  check=`awk -F "	" 'NF != 6' sample1_segs.seg`
  
  if [ -n "${check}" ]; then             echo "vcf is malformed";             workflow-glue fix_vcf --vcf sample1_calls.vcf --fixed_vcf sample1_calls_fixed.vcf --sample_id sample1;             workflow-glue fix_vcf --vcf sample1_segs.vcf --fixed_vcf sample1_segs_fixed.vcf --sample_id sample1; 
      rm sample1_calls.vcf
      mv sample1_calls_fixed.vcf sample1_calls.vcf
      rm sample1_segs.vcf
      mv sample1_segs_fixed.vcf sample1_segs.vcf
  fi

Command exit status:
  1

Command output:
  [1] "sample1_raw_bins.bed"

Command error:
  Loaded bin annotations for genome 'hg38', bin size 500 kbp, and experiment type 'SR50' from annotation package QDNAseq.hg38 v1.0.0
      amplicon_01_cecile_gaetan_alignment_hg38-sample1.sorted.aligned (1 of 1): extracting reads ... binning ...
  Plotting sample amplicon_01_cecile_gaetan_alignment_hg38-sample1.sorted.aligned (0 reads) (1 of 1) ...
  Highlighted 871 bins.
  6,188	total bins
  5,760	of which in selected chromosomes
  5,549	of which with reference sequence
  4,678	final bins
  Plotting sample amplicon_01_cecile_gaetan_alignment_hg38-sample1.sorted.aligned median read counts
  Calculating correction for GC content and mappability
      Calculating fit for sample amplicon_01_cecile_gaetan_alignment_hg38-sample1.sorted.aligned (1 of 1) ...
  Done.
  Error in plot.window(...) : need finite 'xlim' values
  Calls: noisePlot ... plot -> plot -> plot.default -> localWindow -> plot.window
  Execution halted
```

**Comment by vlshesketh** [comment]
Hi @JbaptisteLam, we're pleased that the workflow is working well for you!

The plotting error you're seeing is most likely due to the fact that QDNAseq works best with WGS data, but you can try adjusting the --bin_size parameter to see if this makes a difference - we have published some recommendations for bin size here: https://labs.epi2me.io/copy-number-calling-update/.

**Comment by vlshesketh** [comment]
Hi @JbaptisteLam - as we've not heard back I'll close this for now, but please feel free to re-open if you require further help.
