### ISSUE TITLE
Are there any compatibility issues with any specific reference sequences?

### ISSUE THREAD

**Issue by parkerpayne** [epi2me-labs/wf-human-variation#82]
### Ask away!

I have been tasked with ensuring the compatibility of a specific reference sequence with the workflow:

https://github.com/marbl/CHM13

While I understand that this may not be a direct concern of the workflow itself, I wanted to inquire if there have been any reported compatibility issues or if there are structural aspects of the reference sequence that might potentially affect its functionality within the workflow.

I do recognize that, in the event of any issues, they could likely stem from the tools or programs used within the workflow rather than the workflow's core design. I genuinely appreciate any insights or information you can provide on this matter, but please do not feel obligated to investigate or respond if it falls outside the scope of your expertise.

**Comment by SamStudio8** [comment]
Hi @parkerpayne, please see the "Genome build compatibility" section of the README. Several subcomponents of the workflow are dependent on the use of hg19/hg38 specifically. Other than those caveats, the workflow itself is compatible with any reference genome.
