### ISSUE TITLE
unable to run nextflow epi2me/wf-human-variation

### ISSUE THREAD

**Issue by israelAntman** [epi2me-labs/wf-human-variation#86]
### Ask away!

i run
 nextflow run epi2me/wf-human-variation --help
 and get:
 N E X T F L O W  ~  version 23.04.2
Pulling epi2me/wf-human-variation ...
WARN: Cannot read project manifest -- Cause: Remote resource not found: https://api.github.com/repos/epi2me/wf-human-variation/contents/nextflow.config
Remote resource not found: https://api.github.com/repos/epi2me/wf-human-variation/contents/main.nf

how to solv this problem???

**Comment by SamStudio8** [comment]
@israelAntman The namespace for our workflows is "epi2me-labs", please try:
```
nextflow run epi2me-labs/wf-human-variation --help
```
