### ISSUE TITLE
where is the haplotagged bam?

### ISSUE THREAD

**Issue by carolinehey** [epi2me-labs/wf-human-variation#90]
### Is your feature related to a problem?

Before when you ran phase_methyl, you would get a haplotagged BAM file. Now, there is nothing when using v.1.8.1 and phase_mod. Is it possible to get the haplotagged BAM file back?

### Describe the solution you'd like

the haplotagged .bam

### Describe alternatives you've considered

none

**Comment by carolinehey** [comment]
My concern is that the haplotagged BAM is NOT in the output folder when using --phase_mod.

**Comment by RenzoTale88** [comment]
@carolinehey apologies, my mistake. Could you please check whether you can find the `merge_haplotagged_contigs` in the `.nextflow.log` file, or alternatively check if it appears in the execution reports within the `execution` directory?
Could you also share the content of the output directory with `ls -al`?

**Comment by carolinehey** [comment]
1. nextflow run epi2me-labs/wf-human-variation -r v1.8.1 -w /data/wf_C -profile standard --mod --phase_mod -c /longread/resources/increase_memory.config --bam_min_coverage 1 --bam wf-human-variation_Hg38/112523978771_PAO53414.bam --ref /longread/resources/reference_genomes/GRCh38_Hg38/GRCh38_decoy_no_alt.fasta --sample_name 112523978771_hg38 --out_dir modkit/
2. the merge_haplotagged_contigs appears in the report 
![image](https://github.com/epi2me-labs/wf-human-variation/assets/98043249/99fbe7ad-242f-42e4-9e90-782c2638c650)
3.   ls -al
total 5414028
drwxrwxrwx 2 root root          0 Sep 26 13:47 .
drwxrwxrwx 2 root root          0 Sep 26 08:17 ..
-rwxrwxrwx 1 root root  304827095 Sep 26 13:29 112523978771_hg38_1.bed.gz
-rwxrwxrwx 1 root root  305026130 Sep 26 13:29 112523978771_hg38_2.bed.gz
-rwxrwxrwx 1 root root    2244455 Sep 26 08:49 112523978771_hg38.mosdepth.global.dist.txt
-rwxrwxrwx 1 root root     181109 Sep 26 08:49 112523978771_hg38.mosdepth.summary.txt
-rwxrwxrwx 1 root root  747991486 Sep 26 10:37 112523978771_hg38.readstats.tsv.gz
-rwxrwxrwx 1 root root    1087034 Sep 26 08:49 112523978771_hg38.regions.bed.gz
-rwxrwxrwx 1 root root    1423225 Sep 26 08:49 112523978771_hg38.thresholds.bed.gz
-rwxrwxrwx 1 root root 1024344534 Sep 26 13:29 112523978771_hg38_ungrouped.bed
drwxrwxrwx 2 root root          0 Sep 26 13:29 execution
-rwxrwxrwx 1 root root 3150409646 Sep 26 08:20 GRCh38_decoy_no_alt.fasta
-rwxrwxrwx 1 root root     123147 Sep 26 08:19 GRCh38_decoy_no_alt.fasta.fai
-rwxrwxrwx 1 root root         72 Sep 26 08:17 input.1
-rwxrwxrwx 1 root root       2032 Sep 26 08:20 jbrowse.json
drwxrwxrwx 2 root root          0 Sep 26 08:44 ref_cache
-rwxrwxrwx 1 root root    6274654 Sep 26 10:41 wf-human-variation-alignment-report.html

**Comment by RenzoTale88** [comment]
Does the `output_snp`  process appears too?

**Comment by carolinehey** [comment]
No, not as far as i see

**Comment by RenzoTale88** [comment]
@carolinehey I can confirm that a patch is coming up in the next release. Thank you for spotting this.

**Comment by SamStudio8** [comment]
This should be fixed in 1.8.2
