### ISSUE TITLE
POD5 present but asking for POD5_pass**.fast5

### ISSUE THREAD

**Issue by endomatic** [epi2me-labs/wf-human-variation#93]
### Operating System

Other Linux (please specify below)

### Other Linux

Ubuntu 20.04

### Workflow Version

Human variation 1.8.1

### Workflow Execution

EPI2ME Desktop application

### EPI2ME Version

v23.09-01

### Workflow Execution - CLI Execution Profile

None

### What happened?

N E X T F L O W  ~  version 23.04.2
Launching `/home/dwarner/epi2melabs/workflows/epi2me-labs/wf-human-variation/main.nf` [jolly_noether] DSL2 - revision: 83b01a84e9
||||||||||   _____ ____ ___ ____  __  __ _____      _       _
||||||||||  | ____|  _ \_ _|___ \|  \/  | ____|    | | __ _| |__  ___
|||||       |  _| | |_) | |  __) | |\/| |  _| _____| |/ _` | '_ \/ __|
|||||       | |___|  __/| | / __/| |  | | |__|_____| | (_| | |_) \__ \
||||||||||  |_____|_|  |___|_____|_|  |_|_____|    |_|\__,_|_.__/|___/
||||||||||  wf-human-variation v1.8.1
--------------------------------------------------------------------------------
Core Nextflow options
  runName         : jolly_noether
  containerEngine : docker
  container       : ontresearch/wf-human-variation:sha1b503961726c6e02b6b908297a9797db953b46a3
  launchDir       : /home/dwarner/epi2melabs/instances/wf-human-variation_01HAWHCDHV3S3D670P4KV9TQQ4
  workDir         : /home/dwarner/epi2melabs/instances/wf-human-variation_01HAWHCDHV3S3D670P4KV9TQQ4/work
  projectDir      : /home/dwarner/epi2melabs/workflows/epi2me-labs/wf-human-variation
  userName        : dwarner
  profile         : standard
  configFiles     : /home/dwarner/epi2melabs/workflows/epi2me-labs/wf-human-variation/nextflow.config
Workflow Options
  sv              : true
  snp             : true
  cnv             : true
  str             : true
  mod             : true
Main options
  fast5_dir       : /mnt/0425efb9-9336-4def-af16-2ffcef2efde1/ONT_Output/Jeff_AS_Attempt1/Homo_sapiens/20230726_1438_P2S-00725-A_PAO97641_e57ca34a/pod5_pass
  ref             : /home/dwarner/Downloads/hg38.fa.gz
  bam_min_coverage: 5
  bed             : /home/dwarner/Downloads/ONT_Friche_Gwas_Hits.bed
  out_dir         : /home/dwarner/epi2melabs/instances/wf-human-variation_01HAWHCDHV3S3D670P4KV9TQQ4/output
!! Only displaying parameters that differ from the pipeline defaults !!
--------------------------------------------------------------------------------
If you use epi2me-labs/wf-human-variation for your analysis please cite:
* The nf-core framework
  https://doi.org/10.1038/s41587-020-0439-x
--------------------------------------------------------------------------------
This is epi2me-labs/wf-human-variation v1.8.1.
--------------------------------------------------------------------------------
WARN: CNV calling subworkflow does not support CRAM. You don't need to do anything, but we're just letting you know that:
WARN: - If your input file is CRAM, it will be converted to a temporary BAM inside the workflow automatically.
WARN: - If your input requires alignment or basecalling, the outputs will be saved to your output directory as BAM instead of CRAM.
[9a/3e1219] Submitted process > decompress_ref
[fe/37fc45] Submitted process > cnv:getVersions
[0a/fa0caa] Submitted process > publish_artifact (1)
[c0/c0209e] Submitted process > sv:runReport:getParams
[1b/bed7ea] Submitted process > basecalling:wf_dorado:make_mmi
[f0/75614e] Submitted process > str:getParams
[0c/214dff] Submitted process > report_snp:getVersions
[52/da7ffe] Submitted process > str:getVersions
[1a/286f57] Submitted process > report_snp:getParams
[cd/ce5330] Submitted process > getParams
[6d/2d3c83] Submitted process > lookup_clair3_model (1)
[07/d123dd] Submitted process > getVersions
[ac/59ac47] Submitted process > cnv:getParams
ERROR ~ No files match pattern `pod5_pass**.fast5` at path: /mnt/0425efb9-9336-4def-af16-2ffcef2efde1/ONT_Output/Jeff_AS_Attempt1/Homo_sapiens/20230726_1438_P2S-00725-A_PAO97641_e57ca34a/
 -- Check '/home/dwarner/epi2melabs/instances/wf-human-variation_01HAWHCDHV3S3D670P4KV9TQQ4/nextflow.log' file for details
WARN: Alignment files do not contain modified base tags. Skipping mod aggregation and reporting.
WARN: Killing running tasks (13)

### Relevant log output

```shell
N E X T F L O W  ~  version 23.04.2
Launching `/home/dwarner/epi2melabs/workflows/epi2me-labs/wf-human-variation/main.nf` [jolly_noether] DSL2 - revision: 83b01a84e9
||||||||||   _____ ____ ___ ____  __  __ _____      _       _
||||||||||  | ____|  _ \_ _|___ \|  \/  | ____|    | | __ _| |__  ___
|||||       |  _| | |_) | |  __) | |\/| |  _| _____| |/ _` | '_ \/ __|
|||||       | |___|  __/| | / __/| |  | | |__|_____| | (_| | |_) \__ \
||||||||||  |_____|_|  |___|_____|_|  |_|_____|    |_|\__,_|_.__/|___/
||||||||||  wf-human-variation v1.8.1
--------------------------------------------------------------------------------
Core Nextflow options
  runName         : jolly_noether
  containerEngine : docker
  container       : ontresearch/wf-human-variation:sha1b503961726c6e02b6b908297a9797db953b46a3
  launchDir       : /home/dwarner/epi2melabs/instances/wf-human-variation_01HAWHCDHV3S3D670P4KV9TQQ4
  workDir         : /home/dwarner/epi2melabs/instances/wf-human-variation_01HAWHCDHV3S3D670P4KV9TQQ4/work
  projectDir      : /home/dwarner/epi2melabs/workflows/epi2me-labs/wf-human-variation
  userName        : dwarner
  profile         : standard
  configFiles     : /home/dwarner/epi2melabs/workflows/epi2me-labs/wf-human-variation/nextflow.config
Workflow Options
  sv              : true
  snp             : true
  cnv             : true
  str             : true
  mod             : true
Main options
  fast5_dir       : /mnt/0425efb9-9336-4def-af16-2ffcef2efde1/ONT_Output/Jeff_AS_Attempt1/Homo_sapiens/20230726_1438_P2S-00725-A_PAO97641_e57ca34a/pod5_pass
  ref             : /home/dwarner/Downloads/hg38.fa.gz
  bam_min_coverage: 5
  bed             : /home/dwarner/Downloads/ONT_Friche_Gwas_Hits.bed
  out_dir         : /home/dwarner/epi2melabs/instances/wf-human-variation_01HAWHCDHV3S3D670P4KV9TQQ4/output
!! Only displaying parameters that differ from the pipeline defaults !!
--------------------------------------------------------------------------------
If you use epi2me-labs/wf-human-variation for your analysis please cite:
* The nf-core framework
  https://doi.org/10.1038/s41587-020-0439-x
--------------------------------------------------------------------------------
This is epi2me-labs/wf-human-variation v1.8.1.
--------------------------------------------------------------------------------
WARN: CNV calling subworkflow does not support CRAM. You don't need to do anything, but we're just letting you know that:
WARN: - If your input file is CRAM, it will be converted to a temporary BAM inside the workflow automatically.
WARN: - If your input requires alignment or basecalling, the outputs will be saved to your output directory as BAM instead of CRAM.
[9a/3e1219] Submitted process > decompress_ref
[fe/37fc45] Submitted process > cnv:getVersions
[0a/fa0caa] Submitted process > publish_artifact (1)
[c0/c0209e] Submitted process > sv:runReport:getParams
[1b/bed7ea] Submitted process > basecalling:wf_dorado:make_mmi
[f0/75614e] Submitted process > str:getParams
[0c/214dff] Submitted process > report_snp:getVersions
[52/da7ffe] Submitted process > str:getVersions
[1a/286f57] Submitted process > report_snp:getParams
[cd/ce5330] Submitted process > getParams
[6d/2d3c83] Submitted process > lookup_clair3_model (1)
[07/d123dd] Submitted process > getVersions
[ac/59ac47] Submitted process > cnv:getParams
ERROR ~ No files match pattern `pod5_pass**.fast5` at path: /mnt/0425efb9-9336-4def-af16-2ffcef2efde1/ONT_Output/Jeff_AS_Attempt1/Homo_sapiens/20230726_1438_P2S-00725-A_PAO97641_e57ca34a/
 -- Check '/home/dwarner/epi2melabs/instances/wf-human-variation_01HAWHCDHV3S3D670P4KV9TQQ4/nextflow.log' file for details
WARN: Alignment files do not contain modified base tags. Skipping mod aggregation and reporting.
WARN: Killing running tasks (13)
```

**Comment by RenzoTale88** [comment]
@endomatic could you add the `--dorado_ext pod5` option to your command line and try again?

**Comment by endomatic** [comment]
Andrea,
I was using the GUI where that option is not available. We had problems
with the command line and docker. The FAS told us to use the GUI.
If we go back to the command line, can we run the whole pipeline at the
same time like with GUI?

Jeff

**Comment by julibeg** [comment]
Hi Jeff!
The option can be found in the "Basecalling options" section in the desktop app. Please let us know if that resolved the issue for you.

![image](https://github.com/epi2me-labs/wf-human-variation/assets/37619875/c3549c2c-f7b4-4431-97d0-0fdd9019cbe0)

**Comment by endomatic** [comment]
Julian,
We have POD5 files not Fast5 files. This is for the human variation
workflow in the GUI and I didn't see any option for Dorado input.

Jeff

**Comment by julibeg** [comment]
HI Jeff,
When you scroll down on the left, you should see "Basecalling options" coming up. You can select this to select pod5 from the dropdown menu. Please see the screenshot attached.

![image](https://github.com/epi2me-labs/wf-human-variation/assets/37619875/6a295c51-2867-47e5-9c85-e18c86b6233a)

Best,
Julian

**Comment by endomatic** [comment]
Julian,
Thanks I'll give that a try!

Jeff

**Comment by endomatic** [comment]
Julian,
We tried your suggestion and this is the error we get:


   - N E X T F L O W ~ version 23.04.2
   - Launching
   `/home/dwarner/epi2melabs/workflows/epi2me-labs/wf-human-variation/
   main.nf` [gallant_almeida] DSL2 - revision: 83b01a84e9
   -

   - |||||||||| _____ ____ ___ ____ __ __ _____ _ _
   - |||||||||| | ____| _ \_ _|___ \| \/ | ____| | | __ _| |__ ___
   - ||||| | _| | |_) | | __) | |\/| | _| _____| |/ _` | '_ \/ __|
   - ||||| | |___| __/| | / __/| | | | |__|_____| | (_| | |_) \__ \
   - |||||||||| |_____|_| |___|_____|_| |_|_____| |_|\__,_|_.__/|___/
   - |||||||||| wf-human-variation v1.8.1
   -
   --------------------------------------------------------------------------------
   - Core Nextflow options
   - runName : gallant_almeida
   - containerEngine : docker
   - container :
   ontresearch/wf-human-variation:sha1b503961726c6e02b6b908297a9797db953b46a3
   - launchDir :
   /home/dwarner/epi2melabs/instances/wf-human-variation_01HB6K9Z0Y4E3ZCG8B01TGMKNS
   - workDir :
   /home/dwarner/epi2melabs/instances/wf-human-variation_01HB6K9Z0Y4E3ZCG8B01TGMKNS/work
   - projectDir :
   /home/dwarner/epi2melabs/workflows/epi2me-labs/wf-human-variation
   - userName : dwarner
   - profile : standard
   - configFiles :
   /home/dwarner/epi2melabs/workflows/epi2me-labs/wf-human-variation/nextflow.config
   -

   - Workflow Options
   - sv : true
   - snp : true
   - cnv : true
   - str : true
   - mod : true
   -

   - Main options
   - sample_name : SAMPLE_Test_V1
   - fast5_dir :
   /mnt/0425efb9-9336-4def-af16-2ffcef2efde1/ONT_Output/Jeff_AS_Attempt1/Homo_sapiens/20230726_1438_P2S-00725-A_PAO97641_e57ca34a/pod5_pass
   - ref : /home/dwarner/Downloads/hg38_references.fasta
   - bam_min_coverage: 5
   - bed : /home/dwarner/Downloads/ONT_Friche_Gwas_Hits.bed
   - out_dir :
   /home/dwarner/epi2melabs/instances/wf-human-variation_01HB6K9Z0Y4E3ZCG8B01TGMKNS/output
   -

   - Basecalling options
   - dorado_ext : pod5
   -

   - !! Only displaying parameters that differ from the pipeline defaults !!
   -
   --------------------------------------------------------------------------------
   - If you use epi2me-labs/wf-human-variation for your analysis please
   cite:
   -

   - * The nf-core framework
   - https://doi.org/10.1038/s41587-020-0439-x
   -

   -

   -
   --------------------------------------------------------------------------------
   - This is epi2me-labs/wf-human-variation v1.8.1.
   -
   --------------------------------------------------------------------------------
   - WARN: CNV calling subworkflow does not support CRAM. You don't need to
   do anything, but we're just letting you know that:
   - WARN: - If your input file is CRAM, it will be converted to a
   temporary BAM inside the workflow automatically.
   - WARN: - If your input requires alignment or basecalling, the outputs
   will be saved to your output directory as BAM instead of CRAM.
   - [f0/ddae14] Submitted process > str:getVersions
   - [13/9db196] Submitted process > cram_cache (1)
   - [a9/2e6fb4] Submitted process > report_snp:getVersions
   - [da/562e1d] Submitted process > getVersions
   - [06/74488d] Submitted process > lookup_clair3_model (1)
   - [bc/d9d59c] Submitted process > sv:runReport:getParams
   - [d0/dbc1fd] Submitted process > report_snp:getParams
   - [a5/cb8b77] Submitted process > str:getParams
   - [15/997d22] Submitted process > sv:runReport:getVersions
   - [7c/d1b092] Submitted process > publish_artifact (1)
   - [e4/7c241a] Submitted process > index_ref_fai (1)
   - [30/5bb501] Submitted process > getParams
   - [c5/b2e2f2] Submitted process > basecalling:wf_dorado:make_mmi
   - [d4/fce6ca] Submitted process > cnv:getVersions
   - [01/1cd86b] Submitted process > cnv:getParams
   - Autoselected Clair3 model: r1041_e82_400bps_sup_v410
   - [ba/46312c] Submitted process > basecalling:wf_dorado:dorado (10)
   - [73/2f2c14] Submitted process > basecalling:wf_dorado:dorado (12)
   - ERROR ~ Error executing process > 'basecalling:wf_dorado:dorado (10)'
   -

   - Caused by:
   - Process `basecalling:wf_dorado:dorado (10)` terminated with an error
   exit status (125)
   -

   - Command executed:
   -

   - set +e
   - source /opt/nvidia/entrypoint.d/*-gpu-driver-check.sh # runtime driver
   check msg
   - set -e
   - dorado basecaller ***@***.***
   . --device cuda:all | samtools view --no-PG -b -o 9.ubam -
   -

   - Command exit status:
   - 125
   -

   - Command output:
   - (empty)
   -

   - Command error:
   - docker: Error response from daemon: could not select device driver ""
   with capabilities: [[gpu]].
   - time="2023-09-25T10:38:48-06:00" level=error msg="error waiting for
   container: "
   -

   - Work dir:
   -
   /home/dwarner/epi2melabs/instances/wf-human-variation_01HB6K9Z0Y4E3ZCG8B01TGMKNS/work/ba/46312cc4f5bf97ee81154ca84b5096
   -

   - Tip: view the complete command output by changing to the process work
   dir and entering the command `cat .command.out`
   -

   - -- Check
   '/home/dwarner/epi2melabs/instances/wf-human-variation_01HB6K9Z0Y4E3ZCG8B01TGMKNS/nextflow.log'
   file for details
   - WARN: Alignment files do not contain modified base tags. Skipping mod
   aggregation and reporting.
   - WARN: Killing running tasks (4)



So we thought it could be due to us wanting the SNP's called so we removed
that options and get the error below:
N E X T F L O W ~ version 23.04.2

   -
   - Launching
   `/home/dwarner/epi2melabs/workflows/epi2me-labs/wf-human-variation/
   main.nf` [adoring_roentgen] DSL2 - revision: 83b01a84e9
   -

   - |||||||||| _____ ____ ___ ____ __ __ _____ _ _
   - |||||||||| | ____| _ \_ _|___ \| \/ | ____| | | __ _| |__ ___
   - ||||| | _| | |_) | | __) | |\/| | _| _____| |/ _` | '_ \/ __|
   - ||||| | |___| __/| | / __/| | | | |__|_____| | (_| | |_) \__ \
   - |||||||||| |_____|_| |___|_____|_| |_|_____| |_|\__,_|_.__/|___/
   - |||||||||| wf-human-variation v1.8.1
   -
   --------------------------------------------------------------------------------
   - Core Nextflow options
   - runName : adoring_roentgen
   - containerEngine : docker
   - container :
   ontresearch/wf-human-variation:sha1b503961726c6e02b6b908297a9797db953b46a3
   - launchDir :
   /home/dwarner/epi2melabs/instances/wf-human-variation_01HB6M6MX2N0CVYKCK4ZH4BRGZ
   - workDir :
   /home/dwarner/epi2melabs/instances/wf-human-variation_01HB6M6MX2N0CVYKCK4ZH4BRGZ/work
   - projectDir :
   /home/dwarner/epi2melabs/workflows/epi2me-labs/wf-human-variation
   - userName : dwarner
   - profile : standard
   - configFiles :
   /home/dwarner/epi2melabs/workflows/epi2me-labs/wf-human-variation/nextflow.config
   -

   - Workflow Options
   - sv : true
   - cnv : true
   - str : true
   - mod : true
   -

   - Main options
   - sample_name : SAMPLE_V2
   - fast5_dir :
   /mnt/0425efb9-9336-4def-af16-2ffcef2efde1/ONT_Output/Jeff_AS_Attempt1/Homo_sapiens/20230726_1438_P2S-00725-A_PAO97641_e57ca34a/pod5_pass
   - ref : /home/dwarner/Downloads/hg38.fa.gz
   - bam_min_coverage : 5
   - bed : /home/dwarner/Downloads/ONT_Friche_Gwas_Hits.bed
   - out_dir :
   /home/dwarner/epi2melabs/instances/wf-human-variation_01HB6M6MX2N0CVYKCK4ZH4BRGZ/output
   -

   - Basecalling options
   - dorado_ext : pod5
   - basecaller_basemod_threads: 30
   -

   - !! Only displaying parameters that differ from the pipeline defaults !!
   -
   --------------------------------------------------------------------------------
   - If you use epi2me-labs/wf-human-variation for your analysis please
   cite:
   -

   - * The nf-core framework
   - https://doi.org/10.1038/s41587-020-0439-x
   -

   -

   -
   --------------------------------------------------------------------------------
   - This is epi2me-labs/wf-human-variation v1.8.1.
   -
   --------------------------------------------------------------------------------
   - WARN: CNV calling subworkflow does not support CRAM. You don't need to
   do anything, but we're just letting you know that:
   - WARN: - If your input file is CRAM, it will be converted to a
   temporary BAM inside the workflow automatically.
   - WARN: - If your input requires alignment or basecalling, the outputs
   will be saved to your output directory as BAM instead of CRAM.
   - [4e/de30e0] Submitted process > publish_artifact (1)
   - [56/b072ca] Submitted process > basecalling:wf_dorado:dorado (32)
   - [a2/d2ed44] Submitted process > lookup_clair3_model (1)
   - [fb/be255a] Submitted process > sv:runReport:getVersions
   - [a2/2080f6] Submitted process > getParams
   - [5d/4cc222] Submitted process > sv:runReport:getParams
   - [d8/e00b36] Submitted process > getVersions
   - [13/3dbfff] Submitted process > cnv:getParams
   - [43/20294e] Submitted process > str:getVersions
   - [f0/5d7feb] Submitted process > cnv:getVersions
   - [24/f257b4] Submitted process > decompress_ref
   - Autoselected Clair3 model: r1041_e82_400bps_sup_v410
   - [ac/dd64d7] Submitted process > basecalling:wf_dorado:dorado (3)
   - ERROR ~ Error executing process > 'basecalling:wf_dorado:dorado (32)'
   -

   - Caused by:
   - Process `basecalling:wf_dorado:dorado (32)` terminated with an error
   exit status (125)
   -

   - Command executed:
   -

   - set +e
   - source /opt/nvidia/entrypoint.d/*-gpu-driver-check.sh # runtime driver
   check msg
   - set -e
   - dorado basecaller ***@***.***
   . --device cuda:all | samtools view --no-PG -b -o 31.ubam -
   -

   - Command exit status:
   - 125
   -

   - Command output:
   - (empty)
   -

   - Command error:
   - docker: Error response from daemon: could not select device driver ""
   with capabilities: [[gpu]].
   - time="2023-09-25T10:54:25-06:00" level=error msg="error waiting for
   container: "
   -

   - Work dir:
   -
   /home/dwarner/epi2melabs/instances/wf-human-variation_01HB6M6MX2N0CVYKCK4ZH4BRGZ/work/56/b072ca38ea63570e85b4fdfaf1ba89
   -

   - Tip: view the complete command output by changing to the process work
   dir and entering the command `cat .command.out`
   -

   - -- Check
   '/home/dwarner/epi2melabs/instances/wf-human-variation_01HB6M6MX2N0CVYKCK4ZH4BRGZ/nextflow.log'
   file for details
   - WARN: Alignment files do not contain modified base tags. Skipping mod
   aggregation and reporting.
   - WARN: Killing running tasks (9)


Thoughts?

Thanks,
Jeff

**Comment by julibeg** [comment]
Hi Jeff,

Just to confirm, you are running this on a Ubuntu machine and not on Windows with WSL, right?

Could you please run `nvidia-smi` on the command line and send the output?

Do you have `nvidia-container-toolkit` installed? If not, please refer to the documentation on the [wf-human-variation github repo](https://github.com/epi2me-labs/wf-human-variation#linux) on how to install it.

Best,
Julian

**Comment by endomatic** [comment]
Julian,
I'm going to forward this to Derek Warner who runs the machine and see if
he'll run those commands.
If not I'll go back over and do it.

THanks,
Jeff

**Comment by endomatic** [comment]
Julian,
Here is what we get running nvidia-smi:

Running 520.61.05

CUDA Version:  11.8

RTX A6000 graphics card with 48GB of memory

**Comment by julibeg** [comment]
Hi Jeff, thanks for the info. Do you have `nvidia-container-toolkit` installed? If not, please refer to the documentation on the [wf-human-variation github repo](https://github.com/epi2me-labs/wf-human-variation#linux) on how to install it.

Cheers,
Julian

**Comment by julibeg** [comment]
Also, is basecalling through the workflow a requirement for your analysis?

**Comment by endomatic** [comment]
Julian,
Good question. I'll find out and let you know.
Jeff

**Comment by endomatic** [comment]
Julian,
Basecalling would be great as we do want to know specific snps and their
genotypes as well as methylation status.

We can do it via command line if that is a better option.

Jeff

**Comment by RenzoTale88** [comment]
Hi @endomatic, could you please confirm the following:
1. Are you running the workflow in:
    1. a Windows system with WSL and the EPI2ME app
    2. a Linux system and the EPI2ME app
2. You have installed the `nvidia-container-toolkit`

Please note that the installation instructions for a Windows machine and Linux differ a bit. So as mentioned by @julibeg be sure to follow the appropriate installation instructions in this page [here](https://github.com/epi2me-labs/wf-human-variation#support-for-basecalling-on-gpu).

If you would be ok with running the basecalling step separately, and then pass the basecalled bam files as inputs, you can try using the `wf-basecalling` workflow [here](https://github.com/epi2me-labs/wf-basecalling), which is designed specifically for this task. You can also provide it with a reference genome to perform the alignments and obtained a fully preprocessed bam file, ready for `wf-human-variation`.

**Comment by endomatic** [comment]
Andrea,
We're running it in Ubuntu and I believe we have the nvidia-container-toolkit
installed.
Is there a way to check?
Jeff

**Comment by julibeg** [comment]
>Is there a way to check?

You can run `which nvidia-container-toolkit`

**Comment by endomatic** [comment]
Julian,
It's says it's in /usr/bin/

Jeff

**Comment by julibeg** [comment]
Could you check that the file `/etc/docker/daemon.json` exists and if so, send its contents? This file will be created / modified during the configuration of the docker runtime by the container toolkit.

Cheers,
Julian

**Comment by endomatic** [comment]
Julian,
I have attached an image of the .json file.


Jeff

**Comment by SamStudio8** [comment]
Hi @endomatic, Github won't include file attachments from an email so we can't see your configuration here.

Can you confirm that you (or Derek) have followed all the commands on the nvidia-container-toolkit install guide, particularly [the instructions for configuring Docker after installing the toolkit](https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/latest/install-guide.html#configuring-docker)? Once you have configured Docker to use your GPU using those instructions, you can [test your configuration with a sample CUDA container](https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/latest/sample-workload.html#running-a-sample-workload-with-docker).

If you are able to run the sample CUDA container, the workflow should then be ready to use. If you are unable to run the sample CUDA container, I am afraid we have no further advice other than to speak to your system administrator, and get them to help you debug your nvidia-container-tookit and Docker installation.

**Comment by endomatic** [comment]
Sam,
Here is what was in the file attachment I tried to send before:

    "runtimes": {
        "nvidia": {
            "args": [],
            "path": "nvidia-container-runtime"
        }
    }
}

I'm going to run through the commands for configuring Docker after
installing the toolkit.

Jeff

   -
      -

   -

**Comment by endomatic** [comment]
Confirmed Derek did this and confirmed the test container works.

**Comment by endomatic** [comment]
Just so you can see it, here is the output:

***@***.***:/$ sudo docker run --rm --runtime=nvidia --gpus all
ubuntu nvidia-smi
Unable to find image 'ubuntu:latest' locally
latest: Pulling from library/ubuntu
445a6a12be2b: Pull complete
Digest:
sha256:aabed3296a3d45cede1dc866a24476c4d7e093aa806263c27ddaadbdce3c1054
Status: Downloaded newer image for ubuntu:latest
Wed Sep 27 21:32:43 2023
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 520.61.05    Driver Version: 520.61.05    CUDA Version: 11.8
  |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr.
ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute
M. |
|                               |                      |               MIG
M. |
|===============================+======================+======================|
|   0  NVIDIA RTX A6000    On   | 00000000:51:00.0  On |
 Off |
| 30%   33C    P8    17W / 300W |  47247MiB / 49140MiB |      0%
 Default |
|                               |                      |
 N/A |
+-------------------------------+----------------------+----------------------+


+-----------------------------------------------------------------------------+
| Processes:
   |
|  GPU   GI   CI        PID   Type   Process name                  GPU
Memory |
|        ID   ID                                                   Usage
   |
|=============================================================================|
+-----------------------------------------------------------------------------+

**Comment by julibeg** [comment]
Hi Jeff,

>  sudo docker run --rm --runtime=nvidia --gpus all

Could you also try the above without `sudo` please? Your user should be in the `docker` group, allowing it to run docker without root permissions.

**Comment by endomatic** [comment]
Julian,
I asked Derek if he would run that command. I'm away from the machine right
now.
What did you think of the daemon.json file?

Thanks,
Jeff

**Comment by endomatic** [comment]
Julian,
I think we have made some progress, but we are still running into issues.

Here is the latest attempt and the error:

   - N E X T F L O W ~ version 23.04.2
   - Launching
   `/home/dwarner/epi2melabs/workflows/epi2me-labs/wf-human-variation/
   main.nf` [thirsty_heisenberg] DSL2 - revision: 83b01a84e9
   -

   - |||||||||| _____ ____ ___ ____ __ __ _____ _ _
   - |||||||||| | ____| _ \_ _|___ \| \/ | ____| | | __ _| |__ ___
   - ||||| | _| | |_) | | __) | |\/| | _| _____| |/ _` | '_ \/ __|
   - ||||| | |___| __/| | / __/| | | | |__|_____| | (_| | |_) \__ \
   - |||||||||| |_____|_| |___|_____|_| |_|_____| |_|\__,_|_.__/|___/
   - |||||||||| wf-human-variation v1.8.1
   -
   --------------------------------------------------------------------------------
   - Core Nextflow options
   - runName : thirsty_heisenberg
   - containerEngine : docker
   - container :
   ontresearch/wf-human-variation:sha1b503961726c6e02b6b908297a9797db953b46a3
   - launchDir :
   /home/dwarner/epi2melabs/instances/wf-human-variation_01HBRQG0CFX8TXWGN2XNC06W00
   - workDir :
   /home/dwarner/epi2melabs/instances/wf-human-variation_01HBRQG0CFX8TXWGN2XNC06W00/work
   - projectDir :
   /home/dwarner/epi2melabs/workflows/epi2me-labs/wf-human-variation
   - userName : dwarner
   - profile : standard
   - configFiles :
   /home/dwarner/epi2melabs/workflows/epi2me-labs/wf-human-variation/nextflow.config
   -

   - Workflow Options
   - sv : true
   - snp : true
   - cnv : true
   - str : true
   - mod : true
   -

   - Main options
   - sample_name : Bacode01
   - bam :
   /mnt/0425efb9-9336-4def-af16-2ffcef2efde1/ONT_Output/Jeff_AS_Attempt1/Barcode01_V2_merge_All.bam
   - ref : /home/dwarner/Downloads/hg38.fa.gz
   - basecaller_cfg : ***@***.***
   - bam_min_coverage: 5
   - bed : /home/dwarner/Downloads/ONT_Friche_Gwas_Hits.bed
   - out_dir :
   /home/dwarner/epi2melabs/instances/wf-human-variation_01HBRQG0CFX8TXWGN2XNC06W00/output
   -

   - Small variant calling options
   - phase_vcf : true
   -

   - !! Only displaying parameters that differ from the pipeline defaults !!
   -
   --------------------------------------------------------------------------------
   - If you use epi2me-labs/wf-human-variation for your analysis please
   cite:
   -

   - * The nf-core framework
   - https://doi.org/10.1038/s41587-020-0439-x
   -

   -

   -
   --------------------------------------------------------------------------------
   - This is epi2me-labs/wf-human-variation v1.8.1.
   -
   --------------------------------------------------------------------------------
   - WARN: CNV calling subworkflow does not support CRAM. You don't need to
   do anything, but we're just letting you know that:
   - WARN: - If your input file is CRAM, it will be converted to a
   temporary BAM inside the workflow automatically.
   - WARN: - If your input requires alignment or basecalling, the outputs
   will be saved to your output directory as BAM instead of CRAM.
   - [24/233cbe] Submitted process > sv:runReport:getVersions
   - [7e/b309ca] Submitted process > cnv:getParams
   - [e0/15290a] Submitted process > report_snp:getVersions
   - [65/80ef67] Submitted process > lookup_clair3_model (1)
   - [dc/2c3c54] Submitted process > str:getVersions
   - [58/93990a] Submitted process > getVersions
   - [2d/02ea2b] Submitted process > decompress_ref
   - [ec/4da1d9] Submitted process > report_snp:getParams
   - [84/559f8e] Submitted process > getParams
   - [6f/009f78] Submitted process > sv:runReport:getParams
   - [9b/7e0bd9] Submitted process > cnv:getVersions
   - [9e/d52f8e] Submitted process > str:getParams
   - [90/50d9f1] Submitted process > publish_artifact (1)
   - Autoselected Clair3 model: r1041_e82_400bps_sup_v420
   - [6a/5c19c0] Submitted process > index_ref_fai
   - [98/1a9804] Submitted process > cram_cache
   - [91/bbd4fc] Submitted process > bam_ingress:check_for_alignment (1)
   - [61/7cc2ea] Submitted process > bam_ingress:minimap2_alignment (1)
   - [81/ff4229] Submitted process > publish_artifact (4)
   - ERROR ~ Error executing process > 'bam_ingress:minimap2_alignment (1)'
   -

   - Caused by:
   - Process `bam_ingress:minimap2_alignment (1)` terminated with an error
   exit status (1)
   -

   - Command executed:
   -

   - samtools bam2fq -@ 1 -T 1 Barcode01_V2_merge_All.bam | minimap2 -y -t
   8 -ax map-ont hg38.fa - | samtools sort -@ 3 --write-index -o
   Bacode01.bam##idx##Bacode01.bam.bai -O bam --reference hg38.fa -
   -

   - Command exit status:
   - 1
   -

   - Command output:
   - (empty)
   -

   - Command error:
   - WARNING: Your kernel does not support swap limit capabilities or the
   cgroup is not mounted. Memory limited without swap.
   - [M::mm_idx_gen::32.838*1.66] collected minimizers
   - [M::mm_idx_gen::37.437*2.42] sorted minimizers
   - [M::main::37.437*2.42] loaded/built the index for 455 target
   sequence(s)
   - [M::mm_mapopt_update::38.570*2.38] mid_occ = 728
   - [M::mm_idx_stat] kmer size: 15; skip: 10; is_hpc: 0; #seq: 455
   - [M::mm_idx_stat::39.100*2.36] distinct minimizers: 100202295 (37.96%
   are singletons); average occurrences: 5.732; average spacing: 5.587; total
   length: 3209286105
   - [M::worker_pipeline::103.111*5.60] mapped 895907 sequences
   - [M::worker_pipeline::166.580*6.54] mapped 896550 sequences
   - [E::sam_parse1] SEQ and QUAL are of different length
   - samtools sort: truncated file. Aborting
   -

   - Work dir:
   -
   /home/dwarner/epi2melabs/instances/wf-human-variation_01HBRQG0CFX8TXWGN2XNC06W00/work/61/7cc2eae7676fa3512f1c6e012e5e0a
   -

   - Tip: view the complete command output by changing to the process work
   dir and entering the command `cat .command.out`
   -

   - -- Check
   '/home/dwarner/epi2melabs/instances/wf-human-variation_01HBRQG0CFX8TXWGN2XNC06W00/nextflow.log'
   file for details
   - [b6/10f65b] Submitted process > publish_artifact (2)
   - WARN: Alignment files do not contain modified base tags. Skipping mod
   aggregation and reporting.
   - [bc/15ca5e] Submitted process > publish_artifact (3)
   - WARN: Killing running tasks (3)
   -

**Comment by SamStudio8** [comment]
Hi @endomatic, sorry for the slow response. I am glad you have managed to get up and running on your GPU. Can you please open a new bug report as this is a different issue.
