### ISSUE TITLE
Which configuration should I use for SV calling?

### ISSUE THREAD

**Issue by ekushele** [epi2me-labs/wf-human-variation#94]
### Ask away!

Hello,

I'm trying to run the latest version of the pipeline on my bam file.
This is a bam file that was generated using guppy basecaller (`v6.4.6+ae70e8f`) with the configuration: `dna_r9.4.1_450bps_modbases_5mc_cg_fast_mk1c.cfg`

What configuration should I use for small variant calling?
Will "dna_r9.4.1_e8_fast@v3.4" be suitable?

**Comment by SamStudio8** [comment]
@ekushele If your BAM has been basecalled with Guppy and not Dorado, you'll want to use the legacy basecaller options which all start with "clair3:". Unfortunately, wf-human-variation does not support variant calling with data basecalled with the `fast` mode. I would strongly recommend re-basecalling your data with `hac` to enable variant calling with wf-human-variation.
