### ISSUE TITLE
Docker unable to find image locally (ontresearch/wf-common)

### ISSUE THREAD

**Issue by fidibidi** [epi2me-labs/wf-human-variation#98]
### Operating System

Other Linux (please specify below)

### Other Linux

Ubuntu 22,01

### Workflow Version

v1.8.1

### Workflow Execution

Command line

### CLI command run

    time ./nextflow run epi2me-labs/wf-human-variation \
    -w ${OUTPUT}/workspace \
    -profile standard \
    --snp --sv --mod \
    --dorado_ext pod5 \
    --fast5_dir data/pod5s/ \
    --basecaller_cfg 'dna_r9.4.1_e8_hac@v3.3'  \
    --remora_cfg 'custom' \
    --remora-model_path dorado-model/dna_r9.4.1_e8_hac@v3.3_5mCG_5hmCG@v0/ \
    --ref references/GCA_000001405.15_GRCh38_no_alt_analysis_set.fna \
    --out_dir ${OUTPUT}

### Workflow Execution - CLI Execution Profile

standard (default)

### What happened?

Started wf-human-variation analysis, and after ~24 hours of processing encountered error: 

```
Error from nextflow!

ERROR ~ Error executing process > 'readStats (1)'

Caused by:
  Process `readStats (1)` terminated with an error exit status (125)

Command executed:

  bamstats -s SAMPLE -u -f SAMPLE.flagstat.tsv --threads 3 "SAMPLE.pass.cram" | gzip > "SAMPLE.readstats.tsv.gz"

Command exit status:
  125

Command output:
  (empty)

Command error:
  Unable to find image 'ontresearch/wf-common:sha0a6dc21fac17291f4acb2e0f67bcdec7bf63e6b7' locally
  docker: Error response from daemon: Head "https://registry-1.docker.io/v2/ontresearch/wf-common/manifests/sha0a6dc21fac17291f4acb2e0f67bcdec7bf63e6b7": received unexpected HTTP status: 503 Service Unavailable.
  See 'docker run --help'.

Work dir:
  /home/ubuntu/data/wf-human-var-A1170/workspace/17/e55fb0b03e133f9ef18e8b0bdf4001

Tip: view the complete command output by changing to the process work dir and entering the command `cat .command.out`

 -- Check '.nextflow.log' file for details
WARN: Killing running tasks (3)`
```

I saw a similar error in the bug issues, however this is for a different docker module. 

Any suggestions what might be the issue? 

I saw that docker installation instructions were recommended in the other post, so I will attempt to perform them, then re-run. 

```
sudo apt update
sudo apt install -y docker.io
sudo usermod -aG docker ${USER}
sudo systemctl restart docker

````

### Relevant log output

```shell
==> .command.log <==
Unable to find image 'ontresearch/wf-common:sha0a6dc21fac17291f4acb2e0f67bcdec7bf63e6b7' locally
docker: Error response from daemon: Head "https://registry-1.docker.io/v2/ontresearch/wf-common/manifests/sha0a6dc21fac17291f4acb2e0f67bcdec7bf63e6b7": received unexpected HTTP status: 503 Service Unavailable.
See 'docker run --help'.

==> .command.out <==

==> .command.run <==
#!/bin/bash
# NEXTFLOW TASK: readStats (1)
set -e
set -u
NXF_DEBUG=${NXF_DEBUG:=0}; [[ $NXF_DEBUG > 1 ]] && set -x
NXF_ENTRY=${1:-nxf_main}

nxf_tree() {
    local pid=$1


==> .command.sh <==
#!/bin/bash -euo pipefail
bamstats -s SAMPLE -u -f SAMPLE.flagstat.tsv --threads 3 "SAMPLE.pass.cram" | gzip > "SAMPLE.readstats.tsv.gz"
ubuntu@ip-172-31-58-72:~/data/wf-human-var-A1170/workspace/17/e55fb0b03e133f9ef18e8b0bdf4001$ cat .command.*
Unable to find image 'ontresearch/wf-common:sha0a6dc21fac17291f4acb2e0f67bcdec7bf63e6b7' locally
docker: Error response from daemon: Head "https://registry-1.docker.io/v2/ontresearch/wf-common/manifests/sha0a6dc21fac17291f4acb2e0f67bcdec7bf63e6b7": received unexpected HTTP status: 503 Service Unavailable.
See 'docker run --help'.
Unable to find image 'ontresearch/wf-common:sha0a6dc21fac17291f4acb2e0f67bcdec7bf63e6b7' locally
docker: Error response from daemon: Head "https://registry-1.docker.io/v2/ontresearch/wf-common/manifests/sha0a6dc21fac17291f4acb2e0f67bcdec7bf63e6b7": received unexpected HTTP status: 503 Service Unavailable.
See 'docker run --help'.
```

**Comment by cjw85** [comment]
The 503 error suggests there was a temporary issue pulling the docker image from dockerhub to your AWS instance. You may wish to try running the workflow again with nextflow's resume functionality.

**Comment by fidibidi** [comment]
Ok, 

It seems like using the resume boils down to:

- Being in same dir as where you started. 
- adding `-resume` to the end of the original command

Will try. 

-- UPDATE -- 
```
OUTPUT=data/wf-human-var-A1170
time ./nextflow run epi2me-labs/wf-human-variation \
    -w ${OUTPUT}/workspace \
    -profile standard \
    --snp --sv --mod \
    --dorado_ext pod5 \
    --fast5_dir data/pod5s/ \
    --basecaller_cfg 'dna_r9.4.1_e8_hac@v3.3'  \
    --remora_cfg 'custom' \
    --remora_model_path dorado-model/dna_r9.4.1_e8_hac@v3.3_5mCG_5hmCG@v0/ \
    --ref references/GCA_000001405.15_GRCh38_no_alt_analysis_set.fna \
    --out_dir ${OUTPUT} \
    -resume  #idk, why but its only 1 hyphen
```

I tried this, and accidentally pasted the comment marker + comment after the -resume, and the resume apparently wasn't registered. As it started from the beginning with basecalling... 

:')

So just a  warning to others to be more careful than me lol. 

As for the docker 503 error will see if it happens again.

**Comment by fidibidi** [comment]
If I have the Sample.pass.cram from the initial run; is it possible to just run the 
snp, sv, modkit steps on this file? 

Would the command look like this?

```
time ./nextflow run epi2me-labs/wf-human-variation \
    -w ${OUTPUT}/workspace \
    -profile standard \
    --snp --sv --mod \
    --bam data/${PASS_CRAM} \
    --basecaller_cfg 'dna_r9.4.1_e8_hac@v3.3'  \
    --remora_cfg 'custom' \
    --remora_model_path dorado-model/dna_r9.4.1_e8_hac@v3.3_5mCG_5hmCG@v0/ \
    --ref references/GCA_000001405.15_GRCh38_no_alt_analysis_set.fna \
    --out_dir ${OUTPUT} \
```


OUTPUT=output

**Comment by fidibidi** [comment]
Not sure whether it was just that there was a network issue, or re-installing docker using the steps recommended, but a re-run on a test set of data passed. So will close.
